### PR TITLE
Bug 1653115 - Fix Percentage text position and add tooltip for showing details of each section

### PR DESCRIPTION
**Pull request by SuyashSalampuria**
1. Fixed the height to relative box to keep the center text in place
2. Add victory tooltip to show the details of each section

### CODE REVIEW

**Comment by SuyashSalampuria** [comment]
@camd Could you please see if the way in which tooltip has been implemented now is right. I am try for better in case its not satisfactory

**Comment by camd** [comment]
I'll take a look Friday.  :)

**Comment by camd** [comment]
Looking now

**Comment by SuyashSalampuria** [comment]
> Also.. The text of the tooltips is really tiny. Too small to be read-able. Is there a way to make it larger?

Yes, I will do it
It was actually looking good on my screen

**Comment by camd** [comment]
I will review any updates to this on Monday.

**Comment by SuyashSalampuria** [comment]
> Screenshot 2020-07-17 13 41 46

Could you give me one such URL in this happening. It seems currently fine on this URL
and I am unable to find why this might be happening at that time on that URL

**Comment by camd** [comment]
Looking into this now.

**Comment by camd** [comment]
@SuyashSalampuria : Here is another case of this happening.  Seems to be when there are quite a few commits:
https://treeherder.mozilla.org/pushhealth.html?repo=try&revision=5ba839342c6a28a163138a5c8b159fa29d0c71fc

**Comment by camd** [comment]
Screenshot 2020-07-20 16 04 04

**Comment by camd** [comment]
I think part of the issue is you need to have a strict height and width value on the `.relative` class.  Try adding a `min-width: 200px` and `max-height: 200px` on that class.  That makes it look much better to me.

**Pull request merged**
