### PR TITLE
Restore the switch from CoreAPI to OpenAPI/ReDoc

### PR DESCRIPTION
**Pull request by EvaBardou**
Split from #7743

### CODE REVIEW

**Comment by EvaBardou** [comment]
@Archaeopteryx Great news! It looks like this is perfectly working on [prototype](https://prototype.treeherder.nonprod.cloudops.mozgcp.net/) (see the [docs](https://prototype.treeherder.nonprod.cloudops.mozgcp.net/docs/) page). :smile: 

Please, test on your side and if you agree, we can merge this part and we'll just have to debug the remaining problem in #7747, we now know for sure that it comes from the **WhiteNoise** bump.

**Comment by Archaeopteryx** [comment]
Thanks for narrowing down the regressor. Please vendor the dependencies of the `redoc` file to be served locally from Treeherder as [explained in PR 7730](https://github.com/mozilla/treeherder/pull/7730#issuecomment-1625055248).

**Comment by La0** [comment]
So @EvaBardou needs to:
1. setup a new JS output for api display in webpack build
2. add `redoc@next` in package.json and in that output

**Comment by La0** [comment]
@Archaeopteryx With the latest commit, redoc is shipped inside the main react app, so vendored in, and exposed as `/docs`

A size limit is raised by webpack in the docker build, i'm unsure how you want to approach that (separate chunk for redoc maybe ?)

**Comment by Archaeopteryx** [comment]
Yes, `redoc` should be called rarely and a new chunk is the best approach.

**Review by Archaeopteryx — APPROVED** [review]

**Pull request merged**
