### PR TITLE
Bug1619724 Alert name should not be in table

### PR DESCRIPTION
**Pull request by kingsham**

### CODE REVIEW

**Comment by yogmel** [comment]
Hi, thanks for working on this.
This, however, is not the correct solution.
You should remove the entire row in the Alert Table and add it on top, maintaining its style and layout.

The file you should be modifying is https://github.com/mozilla/treeherder/blob/master/ui/perfherder/alerts/AlertTable.jsx#L203 as shown in the [bug description](https://bugzilla.mozilla.org/show_bug.cgi?id=1619724).

Also, do make sure all tests pass, as written in [Treeherder documentation](https://treeherder.readthedocs.io/testing.html).

**Comment by sarah-clements** [comment]
@kingsham Are you planning to finish this pr?

**Comment by kingsham** [comment]
I need some help with it

**Comment by sarah-clements** [comment]
> I need some help with it

Ok, what do you need help with? :) Please explain in detail what you are stuck on and what you've tried that didn't work.

**Comment by sarah-clements** [comment]
This was actually dealt with in #6860.

**Pull request closed without merging**
