### PR TITLE
 Get rid of trailing `opt` on non-build platforms. 

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by edmorley** [comment]
Hi! Thank you for the PR.

I agree it would be good to avoid the unnecessary `opt` for jobs where it doesn't make sense. It turns out we have a bug on file for this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1291689

However I'm not sure hardcoding a list of jobs that shouldn't use the `platform.option` is the right way to do this. Ideally the task schema would be adjusted so they didn't have to specify opt in the first place :-)

@camd, thoughts?

**Comment by tomprince** [comment]
I definitely think that the solution in that bug is a better long-term solution. However, in making this patch, it appeared that it would be a large change to implement, and require code changes spanning multiple repositories.

Given that ideal solution is complex, and the immediate benefit is comparatively small, it is sensible that fixing it slow priority (as evidenced by the bug being open for ~2 years).

This change solves the immediate comprehension problem for people looking at treeherder, and is non-invasive and easy to remove later, once the ideal solution as been implemented, and all producers updated. Thus, I think it makes sense to apply this less than ideal, but simple patch, as a stop-gap until the ideal solution can be implemented.

**Comment by edmorley** [comment]
> Thus, I think it makes sense to apply this less than ideal, but simple patch, as a stop-gap until the ideal solution can be implemented.

Fair point :-)

**Comment by tomprince** [comment]
Updated.

**Pull request merged**
