### PR TITLE
Update serializers.py

### PR DESCRIPTION
**Pull request by Shivansh2407**
Remove NoOpSerializer from serializers.py #5886

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@klahnakoski , @sarah-clements , @armenzg  Please review the PR.

**Comment by klahnakoski** [comment]
@ionutgoldan   I saw json-in-a-column during your perfherder presentation:  You have a test that will fail if we start messing with stuff like this?

**Comment by klahnakoski** [comment]
@Shivansh2407 Please ensure you can run the test suite locally:    https://github.com/klahnakoski/treeherder/blob/debug/tests/README.md

You appeared to have removed an important part, and now tests are failing.

**Comment by ionutgoldan** [comment]
> 
> 
> @ionutgoldan I saw json-in-a-column during your perfherder presentation: You have a test that will fail if we start messing with stuff like this?

As the automated tests show: things will break. [Bug 1444093](https://bugzilla.mozilla.org/show_bug.cgi?id=1444093) is 2 years old & no longer relevant. It was filed because back then, people realized they didn't need `JSONField` anymore. This code's only purpose was to support it.

Since we've started work on automating backfills, we needed to readd `JSONField`. Thus, this code shouldn't be deleted.

**Pull request closed without merging**
