### PR TITLE
Bug 1678329 - Retrigger button should not use retrigger-multiple action

### PR DESCRIPTION
**Pull request by camd**
This seemed a little too simple.  Not sure if I'm missing something, but I don't think so.  I tested this on try and it worked great.

### CODE REVIEW

**Comment by sarah-clements** [comment]
> This seemed a little too simple. Not sure if I'm missing something, but I don't think so. I tested this on try and it worked great.

Would you mind testing it out in Push Health? :bgrins was trying to retrigger (using one of the icons in-line) and he got an error message `wrong version of actions.json`. I'm wondering if that is because of this bug.

**Review by sarah-clements — APPROVED** [review]
It may be simple, but if the shoe fits... :)

**Comment by sarah-clements** [comment]
One question though, does the task id need to be passed in any place per https://bugzilla.mozilla.org/show_bug.cgi?id=1672967#c12? I recall there being multiple places to retrigger a job.

**Comment by camd** [comment]
> > This seemed a little too simple. Not sure if I'm missing something, but I don't think so. I tested this on try and it worked great.
> 
> Would you mind testing it out in Push Health? :bgrins was trying to retrigger (using one of the icons in-line) and he got an error message `wrong version of actions.json`. I'm wondering if that is because of this bug.

Yeah, it works great in Push Health, too.

**Comment by camd** [comment]
> One question though, does the task id need to be passed in any place per https://bugzilla.mozilla.org/show_bug.cgi?id=1672967#c12? I recall there being multiple places to retrigger a job.

As I understand it, it just needs the task `label` which is the same as the `job_type.name` for us.  It does pass in the `task_id` of the Decision Task, though.  iiuc, that's the only `task_id` that it will need.  It appears to be the case, since the retriggers work well like this.

**Pull request merged**
