### PR TITLE
Bug 1193804 - Break up treeherder.css - global.css

### PR DESCRIPTION
**Pull request by tojonmz**
This fixes part 8 of Bugzilla bug [1193804](https://bugzilla.mozilla.org/show_bug.cgi?id=1193804).

This cleans up *treeherder.css* and renames it to a new file, `treeherder-global.css`.

I intentionally chose this rename so it encourages folks to consider the appropriate location for a new addition ("is it global?, or is it a component?") rather than just adding things into treeherder.css again.

I did a bunch of other cleanup, removed unused classes, converted to 2 space indent, relocated a couple of attributes, and commented and re-ordered the entries so they were easier to find. The appearance of Treeherder, Logviewer, UserGuide, and their related UI should be unchanged:

Treeherder:

globalunchanged

UserGuide:

userguideunchanged

Logviewer:

logviewerunchanged

Everything seems fine and matches in blink testing between my local branch and stage.

Tested on OSX 10.10.5:
Release **44.0a1 (2015-09-25)**
Chrome Latest Release **45.0.2454.99 (64-bit)**

Adding @camd for review.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1008)

### CODE REVIEW

**Comment by tojonmz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[ui/css/treeherder-global.css, line 9 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/1008#-K-4kClk6U0FtqiFrBXx)** ([raw file](https://github.com/mozilla/treeherder/blob/0fca53582bcafa5e70c3875e05cd1fe24a3c5969/ui/css/treeherder-global.css#L9)):</sup>
Maybe this sentence is stating the obvious, but I thought it might be helpful. :) I could remove it if we prefer.

---

<sup>**[ui/css/treeherder.css, line 148 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/1008#-K-4lGx849D5B5dMaoag)** ([raw file](https://github.com/mozilla/treeherder/blob/7ace34b09bc62ca156a1d02d20c0d15e6a412bef/ui/css/treeherder.css#L148)):</sup>
These three above were moved to `-pinboard` since they are unique to its save UI.

---

<sup>**[ui/css/treeherder.css, line 160 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/1008#-K-4l7BxlqPU745iBKqU)** ([raw file](https://github.com/mozilla/treeherder/blob/7ace34b09bc62ca156a1d02d20c0d15e6a412bef/ui/css/treeherder.css#L160)):</sup>
These two above were moved to `-info-panel` since they are unique to the job details pane.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/1008)

**Comment by camd** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[ui/css/treeherder-global.css, line 9 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/1008#-K-4kClk6U0FtqiFrBXx)** ([raw file](https://github.com/mozilla/treeherder/blob/0fca53582bcafa5e70c3875e05cd1fe24a3c5969/ui/css/treeherder-global.css#L9)):</sup>
I like it.  :)

---

<sup>**[ui/css/treeherder-global.css, line 75 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/1008#-K-5Z9QuR2wBep2eyLqo)** ([raw file](https://github.com/mozilla/treeherder/blob/0fca53582bcafa5e70c3875e05cd1fe24a3c5969/ui/css/treeherder-global.css#L75)):</sup>
I know the raw-log-icon is used by the log viewer itself, but wouldn't the log viewer icon belong in the info-panel.css?  Maybe I'm forgetting it's used elsewhere though...  :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/1008)

**Comment by tojonmz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[ui/css/treeherder-global.css, line 75 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/1008#-K-5Z9QuR2wBep2eyLqo)** ([raw file](https://github.com/mozilla/treeherder/blob/0fca53582bcafa5e70c3875e05cd1fe24a3c5969/ui/css/treeherder-global.css#L75)):</sup>
Yup, you are right. Although the logviewer icon .svg and raw log icon `fa` make appearances in both the UserGuide and Logviewer, these particular classes are only used in the info panel. I think for these I was guessing they might be leveraged elsewhere, later. Similar to `cancel-job-icon` below which is used in the info panel and the resultset action bar.

We could move them to `info-panel.css` though, if you prefer. :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/1008)

**Comment by tojonmz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[ui/css/treeherder-global.css, line 75 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/1008#-K-5Z9QuR2wBep2eyLqo)** ([raw file](https://github.com/mozilla/treeherder/blob/0fca53582bcafa5e70c3875e05cd1fe24a3c5969/ui/css/treeherder-global.css#L75)):</sup>
Re: my comments above, I re-checked these again. I think if devs create logviewer .svg / raw log icons elsewhere outside the info panel like we do with`cancel-job-icon` perhaps these 'global' classes would come in handy. Without them they don't present in a consistent size, or optimal dimension for rendering the `fa` on some systems. If it's ok I'd like to leave them where they are? That way devs might choose these `-global` ones first, rather than immediately writing new css elsewhere.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/1008)

**Pull request merged**
