### PR TITLE
Fix import of force-pushes from github

### PR DESCRIPTION
**Pull request by SimonSapin**
When `git push -f` is used, the "base" commit of the github push event is whatever was previously in that branch. That commit is likely not part of the history of the new branch, so using the "List commits" API will not allow to find it as a starting point. Instead, if the API did not force pagination, we’d get the entire repository history!

Using the "Compare two commits" API instead lets GitHub’s server figure out which commits reachable from the new branch that were not before, which is exactly the set of commits we need to be "part of a push".

### CODE REVIEW

**Comment by SimonSapin** [comment]
I don’t have an easy way to run the test suite or otherwise exercise the code I’ve modified, so this PR is submitted "blind" and I’m counting on Travis-CI to report errors.

Is `GithubPushTransformer` covered by the test suite?

**Comment by SimonSapin** [comment]
Looks like yes! https://travis-ci.org/mozilla/treeherder/jobs/455653561

**Comment by camd** [comment]
This code looks good to me.  But I just want to make sure this has been tested locally.  I'm running it now, but if there are no new pushes, I obviously won't see anything.  :)  When you have some time, please ping me in IRC and we can coordinate doing some testing of this branch.

https://treeherder.readthedocs.io/installation.html#server-and-full-stack-development

**Comment by SimonSapin** [comment]
Hi @camd. I’m in the UTC+1 time zone. I haven’t gone through the whole install process to be able to run the backend code on my machine. In case you left an instance running on yours, I’ve just run `git commit --amend --date=now && git push upstream HEAD:try-taskcluster -f` again in my Servo repo now. On https://treeherder.allizom.org/#/jobs?repo=servo-try-taskcluster it shows up as:

screenshot from 2018-11-16 08-29-26

Many commits are considered to be "part of" this push. With this PR applied, I’d expect only one.

**Comment by edmorley** [comment]
@SimonSapin hi! This and the other related PRs are now deployed in production.

Though I am still seeing exceptions on stage?
https://screenshots.firefox.com/BlwaP0Zozaezu200/rpm.newrelic.com

(Happy to send a New Relic account invite to your email if that would be of use?)

**Comment by SimonSapin** [comment]
Hi. I was not aware of this exception. I assume it occurs when the "compare" API returns an empty list of commits, but I’m not sure exactly when that can happen. At this point in the code, do we still have the metadata for the "head" commit from the push event? Using that instead of `commits[-1]` might help.

With the change proposed in https://bugzilla.mozilla.org/show_bug.cgi?id=1509181, the head commit wouldn’t be used anymore for the date. Maybe we should also do something similar for the author, and instead use the "pusher" from the event data https://developer.github.com/v3/activity/events/types/#pushevent

**Pull request merged**
