### PR TITLE
Bug 1284432 - Delete failure lines from es in chunks to prevent slow queries.

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1699)

### CODE REVIEW

**Comment by edmorley** [comment]
I really don't find this very readable, but I can't spend any more time trying to figure it out, so I'm just going to trust it's doing the right thing.

**Comment by edmorley** [comment]
ie without cross-referencing against the schema and re-reading several times, `es_delete_data[len(es_delete_data) - 1][0] - 1` is pretty magic.

**Comment by jgraham** [comment]
I'm not sure what the less magic way of saying "the id one less than the minimum id returned by the current query (which returns (id, test) tuples)", but I"m happy to change it if you have a good idea.

**Comment by edmorley** [comment]
Well, when reading this:
```python
failure_line_max_id = es_delete_data[len(es_delete_data) - 1][0] - 1
```
One has to:
(a) skim back to figure out what `es_delete_data` actually is (a list of `(id, test)` tuples)
(b) realise that then means the `[0]` is actually referring to the `id`
(c) realise that `es_delete_data[len(es_delete_data) - 1]` is actually a verbose way of writing `es_delete_data[-1]`
(d) realise that due to the `.order_by("-id")`, that `es_delete_data[len(es_delete_data) - 1]` actually corresponds to "the lowest id returned by the current query"

Some things that would help:
* Splitting calculations up rather than nesting them, and using clear variable names for the intermediate values
* Using `es_delete_data[-1]` rather than `es_delete_data[len(es_delete_data) - 1]`
* Using `.values()` rather than `.values_list()`, so you can reference `['id']` rather than `[0]` (though I'd be interested to know how this affects memory usage)

**Pull request merged**
