### PR TITLE
Bug 1178232 - Remove support for multiple Datasources of the same type

### PR DESCRIPTION
**Pull request by edmorley**
The datasource table has a 'dataset' field, to allow for multiple datasources of the same type (for partitioning; eg the "1" in `mozilla-central_jobs_1`). However we have never used it, so let's just remove it.

Unfortunately the tests are failing during the `init_master_db` call, since it is trying to apply the migrations on top of the SQL in `treeherder.sql.tmpl`, which now no longer contains the field in question.

I guess this stems from our weird use of a combination of both raw SQL for DB init, plus DB migrations (in the form of 0001_initial.py).

@maurodoglio what do you suggest to resolve this? I could:
* Leave `treeherder.sql.tmpl` unchanged (so the migrations apply cleanly on top of it), but this seems suboptimal since it now no longer reflects the desired end state of the schema.
* Or I could remove the `call_command("migrate")` here:
https://github.com/mozilla/treeherder/blob/master/treeherder/model/management/commands/init_master_db.py#L74 (but then I'm presuming things would still break if migrate was run manually later?)
* Or we could get rid of the reference data SQL file and only use the Django model representation of it?

The latter seems like the cleanest solution perhaps? (And given https://bugzilla.mozilla.org/show_bug.cgi?id=1178225#c2 it seems like we need to clean up models.py since some things are missing there compared to the SQL).

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/693)

### CODE REVIEW

**Comment by maurodoglio** [comment]
I would honestly hold on this to see if we can get rid of the datasource table at all. Looking back on the (manual) way we have been doing migrations so far I think it was a bad idea to try to use south. As a short term solution I would get rid of the migrations folder inside treeherder.model.

**Comment by edmorley** [comment]
Migrations being broken also affects some of the other bugs I have lined up (that don't involve the datasource table), so even if I hold on this, I need a solution to the overall problem. Will try deleting the migrations folder and see how that goes :-)

**Comment by edmorley** [comment]
> As a short term solution I would get rid of the migrations folder inside treeherder.model.

Doing this fails with:
` CommandError: App 'model' does not have migrations (you cannot selectively sync unmigrated apps)`

**Comment by edmorley** [comment]
Oh, due to the test teardown calling migrate:
https://github.com/mozilla/treeherder/blob/d5ae8deb9f041ce538eee1a5d8d05c60f09e56be/tests/conftest.py#L99

I think the best way forwards is just to modify `0001_initial.py` rather than deleting it entirely or creating a `0002_foo.py`

**Comment by maurodoglio** [comment]
:shipit:

**Pull request merged**
