### PR TITLE
Bug 1600932 - Avoid CCing all Perf sheriffs

### PR DESCRIPTION
**Pull request by alexandru-io**
Due to the recent expansion of the sheriffing team, I updated the regression template to avoid spamming all team members when a regression bug is open from an alert.

### CODE REVIEW

**Comment by alexandru-io** [comment]
> Looks good, but there appears to be a conflict.

I rebased. @ionutgoldan please let me know if you can merge this, otherwise I'll make another PR. thanks

**Comment by ionutgoldan** [comment]
FYI @karlht.

**Comment by alexandru-io** [comment]
> I don't really have the context to say whether this is the right thing to do or not. But I trust that you do. :)

Thanks. Can someone please merge this?

**Comment by alexandru-io** [comment]
@ionutgoldan can you merge this, please?

**Pull request merged**
