### PR TITLE
Bug 1602781 - Upgrade MySql version

### PR DESCRIPTION
**Pull request by SuyashSalampuria**
Updated mysql version to 8.0.19
Update jx-mysql version to 3.60.20091 and corresponding hashes
upgrade test-extract-sql according ton new information schema

### CODE REVIEW

**Comment by SuyashSalampuria** [comment]
@armenzg @klahnakoski 
Could you please review this

**Comment by armenzg** [comment]
@SuyashSalampuria @klahnakoski I'm actually unsure as to how to move forward with this bug.
We can't switch Heroku Review apps and the Docker set up without moving the production systems at the same time.

I was thinking that perhaps we want to test a MySql 8 set up on Travis (run tests for both MySql 5 & 8) and/or run a Heroku instance side by side using MySql 8.

Perhaps we can ask IT to upgrade prototype to version 8.

@klahnakoski I was thinking that perhaps we should take some of the changes in this PR wrt to Python packages and tests if they work on both MySql 5 & 8. What do you think?

Whatever we plan we need to discuss it through the rest of the team.

**Comment by armenzg** [comment]
Could you also please merge master if you haven't? I landed some changes recently that was preventing us from deploying to Heroku Review apps.

**Comment by SuyashSalampuria** [comment]
> Could you also please merge master if you haven't? I landed some changes recently that was preventing us from deploying to Heroku Review apps.

Done

**Comment by klahnakoski** [comment]
@armenzg I think we should:

* ensure it works on mysql8
* change nothing in CI; continue testing withmysql5
* merge these changes

These are small changes, and we demonstrate the code is ready to move to mysql8.  Consider this PR a MySQL8 pre-check.  

When we are ready for the mysql8 transition, we will do what we would normally, but with less problems because they were solved here.

**Comment by klahnakoski** [comment]
@SuyashSalampuria please make the changes I requested.  When it looks good, I will have you switch the version back to 5.7, and then we merge.  We will know the code is "version 8 ready"

**Comment by klahnakoski** [comment]
@SuyashSalampuria I neglected to "subimt" the review.  that's why you could not see my suggestions.

**Comment by armenzg** [comment]
I think we learned enough through this work.
I believe we can close it and we can revisit the bug if we decide we need to pursue it.

**Pull request closed without merging**
