### PR TITLE
Bug 1254711 - De-emphasize tier information in job group display

### PR DESCRIPTION
**Pull request by wlach**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1339)

### CODE REVIEW

**Comment by wlach** [comment]
Here's what it looks like:

screen shot 2016-03-08 at 5 28 07 pm

**Comment by wlach** [comment]
vs before:

screen shot 2016-03-08 at 5 29 54 pm

**Comment by tojon** [comment]
Looks nicer. :) I also wonder if it might be beneficial to remove the `-` (would cumulatively save space on a line) and/or lowercase the leading T (so it doesn't compete so much with its job or abut the `[` ).

An example below with just `tier3`.

tier3_1

**Comment by wlach** [comment]
@tojon: I like the idea of removing the '-', but it seems to make it a little harder to read. I think I'll just replace it with a space, which seems a little less obtrusive.

**Comment by wlach** [comment]
Updated the PR to handle case where some groups within a job had different tiers, and then pushed.

**Pull request merged**
