### PR TITLE
Set up Sentry

### PR DESCRIPTION
**Pull request by armenzg**
This enables error and performance reporting.

### CODE REVIEW

**Comment by sarah-clements** [comment]
Can you rebase? That should get the python tests passing. I'll look at this pr in detail Monday or Tuesday.

**Comment by armenzg** [comment]
Happy to jump on a call to go over this to make sure you understand the ins and outs.
I can show you a demo of the product.

**Comment by armenzg** [comment]
I'm satisfied with this. There's few more things that could be added but we're good for now.

**Comment by sarah-clements** [comment]
I didn't get to setting up an account today so I'll look at this early next week and add a commit with the new dsn. Thanks again for the demo and pr!

**Comment by armenzg** [comment]
👍🏻

**Comment by armenzg** [comment]
Hi @sarah-clements would you or someone else be able to review this? You can speak with Marco or Ben since I believe they use Sentry. It would really make your work much easier.

I can fix the conflicts once you say one way or another.

**Comment by sarah-clements** [comment]
> Hi @sarah-clements would you or someone else be able to review this? You can speak with Marco or Ben since I believe they use Sentry. It would really make your work much easier.
> 
> I can fix the conflicts once you say one way or another.

Hi Armen, Treeherder is in maintenance mode indefinitely with only a few people doing any work on it so this is very low priority, which is why I haven't gone and set up an account and alerts. If @Archaeopteryx or @beatrice-acasandrei @esanuandra think this would be better than the existing tools we have - logs and New Relic - based on the work they do, then I can do it. But I'm in the middle of a major project so again, its low priority.

**Comment by armenzg** [comment]
@jmaher @bhearsum @Archaeopteryx or @beatrice-acasandrei @esanuandra let me know if you would like me to fix this up so you and others can see FE and BE errors or performance data. Adding this would allow debugging issues.

I would be happy to rebase if you want me to.

**Pull request closed without merging**
