### PR TITLE
Bug 1473875 - Remove Unused APIs

### PR DESCRIPTION
**Pull request by ghickman**
This removes the FailureLine and ClassifiedFailure APIs since they appear to be unused and were causing confusion when I was trying to work out where some other methods were used.

### CODE REVIEW

**Comment by edmorley** [comment]
Good spot - these came up in bug 1437078 too, though I was less sure at that point whether they were definitely unused. Would you mind filing a new bug that's marked as blocking bug 1437078 for their removal? That way if anyone was using them periodically (via eg a local script) they can see the Bugmail (if they are component-watching) and/or have something in Bugzilla to search against when they wonder why they are getting 404s.

I seem to remember these APIs used the `ExtendedRouter` -- perhaps worth checking if they are the last consumer of it. (Also, that always seems like a bit of a hack to me, perhaps d-r-f has a better way?)

**Comment by edmorley** [comment]
Re the new bug -- no need to create the link attachment (given the bot only makes it at initial PR opening) - I'll watch for the review here. Just make sure the PR title and commit message include the bug number, and when the PR is merged, the other bot will still comment with the commit URL.

**Comment by ghickman** [comment]
@edmorley – commit titles updated, bug created and set to blocking 1437078.

The extended router is still in use by the TextLogError endpoint.  However all it does is tell the router to use the `update_many` method for PUTs which I suspect we could do manually in the handler.  Shall I remove that router as part of this change?

**Comment by ghickman** [comment]
@edmorley – updated to a) pass the tests (always useful!) and b) pull out the custom router instead of removing it.

I investigated removing the router entirely and handling it inside the ViewSet like one might with a standard class-based view but DRF doesn't really provide a way to modify that behaviour outside the Router.  Instead I've pulled the custom Router out of our default routing block so it's clear what we're using it for.

**Pull request merged**
