### PR TITLE
Bug 1273616 - Add the NSS repository

### PR DESCRIPTION
**Pull request by ttaubert**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1499)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by edmorley** [comment]
Tweaking the PR summary to add the bug number (if this is present, autolander will create the Bugzilla attachment for you) and also to reflect the fact that this won't just add it for Treeherder staging, but production too (this is expected, they both use the same fixtures file).

If you could adjust the commit message accordingly, and switch the group to '7' (since I think 'other' is probably the most appropriate, since '1' is used for gecko development. see https://github.com/mozilla/treeherder/blob/a2a989705348ae53a89b1938339d11fcfc0f3bc2/treeherder/model/fixtures/repository_group.json#L57) - then we should be good to go :-)

**Comment by ttaubert** [comment]
> If you could adjust the commit message accordingly, and switch the group to '7' then we should be good to go :-)

Done, thanks!

**Pull request merged**
