### PR TITLE
Reconfigure Renovate

### PR DESCRIPTION
**Pull request by armenzg**
I'm using this configuration for AWFY and the Health dashboard.

* Move config to a dot file
* Schedule package updates early on Mondays
* Avoid taking minor packages
* Update patch releases independently from minor releases
* Auto merge patch releases silently if tests pass, otherwise, open PR
* Auto merge lock file maintenance if tests pass. Always open PR

### CODE REVIEW

**Comment by armenzg** [comment]
If you need to check the docs they're located [here](https://docs.renovatebot.com/).

**Comment by sarah-clements** [comment]
I think this is Ok to me. Breaking changes tend to be mostly in major releases, correct?

**Comment by armenzg** [comment]
Unfortunately, I've been bitten twice with minor releases. It should be as you say but packages with little coverage can have that problem once in a while.

**Comment by armenzg** [comment]
@camd since Sarah and I have dealt with most JS package updates I will go with her review. If you want to add something after the fact by all means and I will follow up with it on another PR.

**Pull request merged**
