### PR TITLE
Bug 1443331 - Add a checkbox to hide results that don't have data for both the old and new revisions

### PR DESCRIPTION
**Pull request by tomrittervg**
Basically I searched for 'showOnlyConfident' and cargo-culted that code everywhere.  I ran it with `yarn start` and it seems to work fine for me.

### CODE REVIEW

**Comment by wlach** [comment]
Normally we require a bug for larger pull requests like these. Could you file one, attach this pull request to the bug, and then r?rwood on it?

https://bugzilla.mozilla.org/enter_bug.cgi?product=Tree%20Management&component=Perfherder

**Comment by edmorley** [comment]
@rwood-moz, when merging please add the bug number to the commit message using the "squash and merge" feature, if it's not added before :-)

**Comment by jmaher** [comment]
thanks @tomrittervg I looked over the changes and they look good.  @wlach do you have any concerns with me merging this in?

**Comment by wlach** [comment]
No real concerns, as long as you've tested it and it works. I feel like we have too many of these checkboxes but I can see the need for this one. Maybe we can think of a better solution in the future.

**Comment by edmorley** [comment]
> when merging please add the bug number to the commit message using the "squash and merge" feature, if it's not added before :-)

The merged commit is missing the bug number.

**Comment by jmaher** [comment]
sorry about that.  I had see the bug number at the top of this page and assumed it was all good.

**Pull request merged**
