### PR TITLE
Bug 1428045 - Make flake8 linter pass under Python 3

### PR DESCRIPTION
**Pull request by kevinmgagnon**

### CODE REVIEW

**Comment by edmorley** [comment]
Hi! Sorry for the delayed reply.

It looks like some changes from the master branch got accidentally bundled into this PR. Could you rebase on master and remove them? :-)

**Comment by edmorley** [comment]
@kevinmgagnon if there's anything we can do to help, let us know :-)

**Comment by kevinmgagnon** [comment]
Thanks, I've been caught up with school stuff recently but I'll try to get some more progress on this

**Comment by edmorley** [comment]
Hi! Someone else has opened a PR to continue this work (#3347) so closing this out for now. Thank you for taking a look though, and we'd happily accept any further contributions in the future :-)

**Pull request closed without merging**
