### PR TITLE
Bug 1253341 - Support linux64-vm platform type

### PR DESCRIPTION
**Pull request by jmaher**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1338)

### CODE REVIEW

**Comment by edmorley** [comment]
The tests are failing (I've retriggered the initial infra failure).
Could you also add a test for the new platform name?

**Comment by edmorley** [comment]
Given https://bugzilla.mozilla.org/show_bug.cgi?id=1264759#c7 for the Windows 7 VM jobs, should these be on the same line as the existing Linux jobs, or are these going to be run in parallel (unlike for win7)?

Also, could you:
* combine the groups where there is now a duplicate entry with the same 'os_platform' value?
* file a separate bug for this change (we tend to avoid lumping treeherder changes in with the main releng bug since it's harder to track vs deployment and also breaks things like autolander)
* rebase against master and remove the merge commits included in the PR
* fix up the tests

Alternatively if you let me know about the grouping question above and point me to a list of buildernames, I'm happy to open a PR to finish this up for you :-)

**Comment by jmaher** [comment]
I think we will want to follow the path of win7 and keep everything on the same line.  Possibly we don't need to do anything codewise for this PR?

**Comment by edmorley** [comment]
> I think we will want to follow the path of win7 and keep everything on the same line. Possibly we don't need to do anything codewise for this PR?

Is the list of buildernames in https://bugzilla.mozilla.org/show_bug.cgi?id=1253341#c80 still accurate?

I can add a testcase for these to confirm everything is working and prevent regressions.

**Comment by edmorley** [comment]
Closing given https://bugzilla.mozilla.org/show_bug.cgi?id=1253341#c105

**Pull request closed without merging**
