### PR TITLE
Bug 1281820 - Remove all bug suggestion artifact storage code + tests

### PR DESCRIPTION
**Pull request by wlach**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1927)

### CODE REVIEW

**Comment by jgraham** [comment]
Seems like there are still some references to the artifacts in the UI code.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[treeherder/model/error_summary.py, line 24 at r1](https://reviewable.io:443/reviews/mozilla/treeherder/1927#-KUMQQV5BVyqxgvWUQcX:-KUMQQV6bPfoIQgyzX2R:b-pan2s5) ([raw file](https://github.com/mozilla/treeherder/blob/a9552e40ddfadd986ea2ddb270a76c0c6ea839c0/treeherder/model/error_summary.py#L24)):*
> ```Python
>     # if we don't have any text log errors, we don't want to cache
>     # (since this might be an incomplete job)
>     if TextLogError.objects.filter(step__job_id=job_id).exists():
> ```

I wonder to what extent this negates the benefits of the cache (not related to this PR, but I just noticed it). Presumably the ideal logic would be "return the cached copy if one exists, but only populate the cache if there is actual data). Anyway, not important for now; just a passing comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1927#-:-KUMYd6JmDSnUtcsBe5u:bcqhpg5)*

**Comment by edmorley** [comment]
> Presumably the ideal logic would be "return the cached copy if one exists, but only populate the cache if there is actual data).

We could either use the `unless` parameter to `@memoize`, or else after we parse the log call `delete_memoized()`:
http://pythonhosted.org/django-memoize/#api

O

**Comment by wlach** [comment]
Yeah, I was meaning to file a seperate bug. The artifact stuff in the UI code isn't specifically related to bug suggestions.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[treeherder/model/error_summary.py, line 24 at r1](https://reviewable.io:443/reviews/mozilla/treeherder/1927#-KUMQQV5BVyqxgvWUQcX:-KUMioTGARxps27xZ4FP:b-qxw2mv) ([raw file](https://github.com/mozilla/treeherder/blob/a9552e40ddfadd986ea2ddb270a76c0c6ea839c0/treeherder/model/error_summary.py#L24)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I wonder to what extent this negates the benefits of the cache (not related to this PR, but I just noticed it). Presumably the ideal logic would be "return the cached copy if one exists, but only populate the cache if there is actual data). Anyway, not important for now; just a passing comment.
</details>
True, though simple mysql queries like this are very fast (~1-5ms) according to new relic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1927#-:-KUMigZaAWU07DQZx0wn:by1e0ea)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1927)*

**Pull request merged**
