### PR TITLE
Bug 1669416 - Improve wording of Perfherder Bugzilla message

### PR DESCRIPTION
**Pull request by esanuandra**

### CODE REVIEW

**Comment by esanuandra** [comment]
image

**Review by ionutgoldan — CHANGES_REQUESTED** [review]
weird-layout

There's a weird line hanging on the top right side of each table.

Also, I think we should add one newline after the regressions table, such that it's easier to distinguish the improvements. Currently, they're too close to one another.

Another small tweaks to the table's headers:
* we should capitalize & bold them
* the last column could use a title as well. Maybe *Absolute values (old vs new)*
* the column with values such as *e10s stylo* should also have a title, like *Options*
* for the 1st column, we should provide the *Ratio* title
* instead of test/subtest, we could use suite/test instead

**Comment by ionutgoldan** [comment]
I still see the line hanging on the top right sides.

**Comment by ionutgoldan** [comment]
I'd say a level 3 heading would be nice.

**Comment by ionutgoldan** [comment]
I'm not sure what to do with the top border... I'm not happy with presenting it. We should further investigation this & find a fix somehow. On Stackoverflow I noticed a bunch of things we can try out (using raw HTML, wrapping the markdown in a <div/> & applying inline CSS rules etc).

@sarah-clements did you happen to come across problems with markdown tables formatting?

**Comment by ionutgoldan** [comment]
After talking with Dave, it seems like this PR's improvements outweigh the visual glitch's problem.
@kimberlythegeek are you ok with this or do you have other opinions?

**Review by kimberlythegeek — APPROVED** [review]
looks good to me!

**Review by ionutgoldan — APPROVED** [review]

**Review by camd — APPROVED** [review]

**Pull request merged**
