### PR TITLE
Bug 1733943 - Expose Sherlock backfill tasks by status

### PR DESCRIPTION
**Pull request by beatrice-acasandrei**
https://bugzilla.mozilla.org/show_bug.cgi?id=173394
expose jobs by status

### CODE REVIEW

**Review by esanuandra — APPROVED** [review]
Frontend part looks good

**Review by airimovici — APPROVED** [review]
On the backend side looks good. We also have tests for most of the cases we can be in 👍

**Comment by beatrice-acasandrei** [comment]
@sarah-clements Please take a look on the db changes when you can. Thanks.

**Review by sarah-clements — COMMENTED** [review]
Looks ok to me

**Pull request merged**
