### PR TITLE
Reenable camelcase

### PR DESCRIPTION
**Pull request by eralwen**
Put back camelcase linting for issue #5457.

### CODE REVIEW

**Comment by armenzg** [comment]
@eralwen there are some [tests failing](https://travis-ci.org/mozilla/treeherder/jobs/605679765?utm_medium=notification&utm_source=github_status); could you please look into it?

**Comment by eralwen** [comment]
I think these errors are caused because some other files still have some variable names such as "job_group_name" that don't get caught in the lint process when I have changed them. Should I be changing all these files to camel case respectively, so it doesn't cause undefined? I don't fully understand where this undefined is coming from.

**Comment by armenzg** [comment]
> @armenzg I think these errors are caused because some other files still have some variable names such as "job_group_name" that don't get caught in the lint process when I have changed them. Should I be changing all these files to camel case respectively, so it doesn't cause undefined? I don't fully understand where this undefined is coming from.

@eralwen yes, all instances across the code base need updating.

**Comment by eralwen** [comment]
I'm closing this myself as I am busy and this is actually a lot of work (at least for me). I hope someone else can do this instead.

**Pull request closed without merging**
