### PR TITLE
Bug 1182464 followup

### PR DESCRIPTION
**Pull request by maurodoglio**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/944)

### CODE REVIEW

**Comment by edmorley** [comment]
The current PR doesn't give us a way to tell if the error summary was truncated (like we do for the standard log parser). I know log_iter being an iterable makes this harder than it would be otherwise, but do we think this is still something we want?

(I've not yet reviewed the model changes, but will submit this in the meantime)

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/log_parser/management/commands/store_error_summary.py, line 33 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/944#-JycswlIy9XWBdvTjlrJ)** ([raw file](https://github.com/mozilla/treeherder/blob/6d11ddc4c6fec0b92aaf4edacbbf908d5969fa5c/treeherder/log_parser/management/commands/store_error_summary.py#L33)):</sup>
We don't need the `getattr`, it's always going to be set in base.py.

---

<sup>**[treeherder/settings/base.py, line 445 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/944#-JyctEOb9udM08p5lKu7)** ([raw file](https://github.com/mozilla/treeherder/blob/6d11ddc4c6fec0b92aaf4edacbbf908d5969fa5c/treeherder/settings/base.py#L445)):</sup>
Please place this near the existing `PARSER_MAX_SUMMARY_LINES`.
Also, I don't think we need this to be an environment variable - let's just set it to 35?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/944)

**Comment by jgraham** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/model/models.py, line 596 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/944#-JygFqKCY4obVwHRnz4q)** ([raw file](https://github.com/mozilla/treeherder/blob/6d11ddc4c6fec0b92aaf4edacbbf908d5969fa5c/treeherder/model/models.py#L596)):</sup>
I was imagining score in the range 0-2 with 0-1 being for autostar scores and 1-2 being for manual scores (obviously there are other ways of encoding similar information). Therefore we would only need 1 digit before the decimal, not 3. The idea was that this would provide a natural way of sorting manual scores before autostar scores. But it might also make sense to have a seperate column to indicate a manual override.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/944)

**Comment by maurodoglio** [comment]
I'll add a fake log line number zero to indicate that the list was truncated

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/model/models.py, line 596 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/944#-JygFqKCY4obVwHRnz4q)** ([raw file](https://github.com/mozilla/treeherder/blob/6d11ddc4c6fec0b92aaf4edacbbf908d5969fa5c/treeherder/model/models.py#L596)):</sup>
To indicate a human decision we could use a`manual` Matcher AND use the score convention you proposed. I'll change the max_digits to 3.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/944)

**Comment by edmorley** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/log_parser/management/commands/store_error_summary.py, line 36 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/944#-Jygkh61xn9I-k-kFQqo)** ([raw file](https://github.com/mozilla/treeherder/blob/d63b2e52cacbd324fb5a0dd117a33ab8d98db41a/treeherder/log_parser/management/commands/store_error_summary.py#L36)):</sup>
We can drop this conditional

---

<sup>**[treeherder/log_parser/management/commands/store_error_summary.py, line 40 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/944#-JyglMc1LD0kxX3xH8Np)** ([raw file](https://github.com/mozilla/treeherder/blob/d63b2e52cacbd324fb5a0dd117a33ab8d98db41a/treeherder/log_parser/management/commands/store_error_summary.py#L40)):</sup>
The comment says we're adding a line, but in fact we're changing the last element in the list. The latter is what we want to do (since we've deliberately returned N+1 lines so we can differentiate between truncated and matching the limit by cooincidence) - so I think the comment should say something like:
``# Alter the N+1th log line to indicate the list was truncated``

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/944)

**Comment by jgraham** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/log_parser/management/commands/store_error_summary.py, line 41 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/944#-Jygmvp4CFys91_EuaeY)** ([raw file](https://github.com/mozilla/treeherder/blob/d63b2e52cacbd324fb5a0dd117a33ab8d98db41a/treeherder/log_parser/management/commands/store_error_summary.py#L41)):</sup>
If you want to store this like this rather than as an e.g. boolean column, I would prefer a specific action to indicate truncation rather than (ab)using "log". I would also sumewhat prefer that the recorded line is the line that the next error message would have been on, rather than another magic signil.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/944)

**Comment by jgraham** [comment]
Reviewed 2 of 3 files at r3.
Review status: 2 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/944)

**Pull request merged**
