### PR TITLE
 Bug 1212177 - l10n repacks should be displayed in treeherder properly 

### PR DESCRIPTION
**Pull request by kmoir**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1359)

### CODE REVIEW

**Comment by edmorley** [comment]
I'd recommend creating a branch for each PR, rather than using master - since a PR is a dynamic comparison between two repo/branch combinations, and so by using master you tie up that repo whilst the PR is open.

Prior to this being closed the tests were failing fwiw:
https://travis-ci.org/mozilla/treeherder/builds/117559282

**Comment by kmoir** [comment]
I created a new branch.  I can't get the tests to run in my local environment, this is why I am creating pull requests to test them.

**Comment by edmorley** [comment]
If you could file a bug or pastebin the issues running the tests, I'd be happy to help :-) (And it may save other contributors problems).

Using Travis to run the tests is no problem though - if it helps, the same PR can be updated multiple times (by force pushing), which avoids the creation of lots of PRs (which result in email notifications to all the watchers).

**Comment by kmoir** [comment]
Here is the test failure

https://travis-ci.org/mozilla/treeherder/jobs/117732350

https://pastebin.mozilla.org/8864635

I'm not sure how to fix it so help is appreciated

**Comment by edmorley** [comment]
I pulled the PR locally and the regex has additional spaces around the underscores, which would explain the test failures.

Strangely those same spaces don't appear in the web UI above.

However since the source repo has been deleted it makes this very hard to figure out :-(

**Comment by edmorley** [comment]
Oh I see this isn't the newest PR, it is instead #1361.
The multiple PRs is making this pretty confusing.

**Pull request closed without merging**
