### PR TITLE
Bug 1620326 - add pretty label for linux1804-64-tsan

### PR DESCRIPTION
**Pull request by worldomonation**
Add a Treeherder pretty label for linux1804-64-tsan/opt tests.

### CODE REVIEW

**Comment by worldomonation** [comment]
Tagging @sarah-clements for review and merge if checks pass.

**Comment by sarah-clements** [comment]
@worldomonation There's some little quirk that's preventing these tests showing as complete even though they passed. Can you either click into the travis Details link and restart the tests or do a rebase and force push to restart the tests?

**Comment by worldomonation** [comment]
I will try closing and reopening the PR.

**Comment by worldomonation** [comment]
Didn't seem to work, will rebase.

**Comment by sarah-clements** [comment]
Opening and closing doesn't generally work. You need to rebase from upstream and force push. I think that will trigger new tests since it's a new commit (or else just make a minor adjustment to the commit message and force push).

**Pull request closed without merging**
