### PR TITLE
Bug 1171757 - create a vagrant .bash_aliases with helpful functions

### PR DESCRIPTION
**Pull request by camd**
I've used versions of these functions in my day-to-day work.  I wanted to share them with the team.  This adds them to the vagrant env by default.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/609)

### CODE REVIEW

**Comment by tojonmz** [comment]
Maybe just me but I always liked terse aliases :)
eg.
*tvlogs
tdlogs
tqueues
tqpurge
treset*

And perhaps out of scope, but I wondered if we should provide visibility of the aliases on login with a login message? Like, 'for a list of treeherder aliases type thelp'.

**Comment by edmorley** [comment]
Review status: 2 of 3 files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- puppet/files/treeherder/.bash_aliases @ r2
- puppet/manifests/vagrant.pp @ r1

---

<sup>**[puppet/manifests/classes/treeherder.pp, line 23 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-Jr3o6fh93yYSK292iTX)** ([raw file](https://github.com/mozilla/treeherder/blob/93f02f4b68512c29e7ef9b5a6a4f35fc857a19d8/puppet/manifests/classes/treeherder.pp#L23)):</sup>
For files, puppet has a specific class/type/whatever it's called, which keeps content up to date. We should use that instead of a |cp| in an exec (since it does an MD5 of the file and if it's unchanged, will skip the step - whereas the |exec cp| will run every time). For example, see:
https://github.com/mozilla/treeherder/blob/4bafb7c9c620f7b5b86185f47dcf5820744e9c51/puppet/manifests/classes/apache.pp#L34-L39

---

<sup>**[puppet/manifests/classes/treeherder.pp, line 28 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-Jr3oLJvaYjhvbefJjLO)** ([raw file](https://github.com/mozilla/treeherder/blob/93f02f4b68512c29e7ef9b5a6a4f35fc857a19d8/puppet/manifests/classes/treeherder.pp#L28)):</sup>
We don't need to add this, since the stock .bashrc already does:
```bash
# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/609)

**Comment by camd** [comment]
Review status: 2 of 3 files reviewed, 2 unresolved discussions, some commit checks pending.

---

<sup>**[puppet/manifests/classes/treeherder.pp, line 28 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-Jr3oLJvaYjhvbefJjLO)** ([raw file](https://github.com/mozilla/treeherder/blob/93f02f4b68512c29e7ef9b5a6a4f35fc857a19d8/puppet/manifests/classes/treeherder.pp#L28)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/609)

**Comment by camd** [comment]
Review status: 2 of 3 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[puppet/manifests/classes/treeherder.pp, line 23 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-Jr3o6fh93yYSK292iTX)** ([raw file](https://github.com/mozilla/treeherder/blob/93f02f4b68512c29e7ef9b5a6a4f35fc857a19d8/puppet/manifests/classes/treeherder.pp#L23)):</sup>
Ahh, that's cool.  Thanks for the tip.  OK, modified to do that.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/609)

**Comment by camd** [comment]
@tojonmz : those aliases are a little too terse for my tastes, personally.  But point well taken.  I took out the underscores, because those are a pain to type.  so with tab-completion it should be pretty good this way.  Agreed about help.  I'll add that in.

**Comment by edmorley** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- puppet/files/treeherder/.bash_aliases @ r3
- puppet/manifests/classes/treeherder.pp @ r3
- puppet/manifests/vagrant.pp @ r3

---

<sup>**[puppet/files/treeherder/.bash_aliases, line 14 \[r3\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-JrKrE0oGoAw2OlCRYHO)** ([raw file](https://github.com/mozilla/treeherder/blob/1806e111c9e040a3d5f6ef70afae8a23a4a544de/puppet/files/treeherder/.bash_aliases#L14)):</sup>
This doesn't do anything for me? (different console emulator admittedly) Though happy to leave as is if it works for you - doesn't hurt :-)

---

<sup>**[puppet/manifests/classes/treeherder.pp, line 30 \[r3\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-JrKqK_F9-SeyhNUtmDq)** ([raw file](https://github.com/mozilla/treeherder/blob/1806e111c9e040a3d5f6ef70afae8a23a4a544de/puppet/manifests/classes/treeherder.pp#L30)):</sup>
Since we don't need the file to be pre-processed, we can use:
``file => "/foo/bar",``
rather than this pattern:
``content => template("/foo/bar"),``

See: 
https://github.com/mozilla/treeherder/blob/e20a80ddcb5585f06868429a9ea540fa2d57423c/puppet/manifests/classes/mysql.pp#L35
https://docs.puppetlabs.com/references/latest/type.html#file-attribute-source

---

<sup>**[puppet/manifests/vagrant.pp, line 14 \[r3\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-JrKraAHpddW1HBBJOvh)** ([raw file](https://github.com/mozilla/treeherder/blob/1806e111c9e040a3d5f6ef70afae8a23a4a544de/puppet/manifests/vagrant.pp#L14)):</sup>
This doesn't change my prompt - I presume this is only defining `PS1` as a puppet variable and not in the shell environment.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/609)

**Comment by camd** [comment]
Review status: 2 of 3 files reviewed, 3 unresolved discussions, some commit checks pending.

---

<sup>**[puppet/files/treeherder/.bash_aliases, line 14 \[r3\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-JrKrE0oGoAw2OlCRYHO)** ([raw file](https://github.com/mozilla/treeherder/blob/1806e111c9e040a3d5f6ef70afae8a23a4a544de/puppet/files/treeherder/.bash_aliases#L14)):</sup>
yeah, must be a windows thing, I guess.  :/

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/609)

**Comment by camd** [comment]
Review status: 2 of 3 files reviewed, 3 unresolved discussions, some commit checks pending.

---

<sup>**[puppet/manifests/vagrant.pp, line 14 \[r3\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-JrKraAHpddW1HBBJOvh)** ([raw file](https://github.com/mozilla/treeherder/blob/1806e111c9e040a3d5f6ef70afae8a23a4a544de/puppet/manifests/vagrant.pp#L14)):</sup>
Oops.  My bad.  That got lost in the shuffle, somehow.  Fixed now.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/609)

**Comment by camd** [comment]
Review status: 2 of 3 files reviewed, 3 unresolved discussions, some commit checks pending.

---

<sup>**[puppet/manifests/classes/treeherder.pp, line 30 \[r3\]](https://reviewable.io:443/reviews/mozilla/treeherder/609#-JrKqK_F9-SeyhNUtmDq)** ([raw file](https://github.com/mozilla/treeherder/blob/1806e111c9e040a3d5f6ef70afae8a23a4a544de/puppet/manifests/classes/treeherder.pp#L30)):</sup>
Thanks, good point.  OK, fixed now

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/609)

**Comment by camd** [comment]
Review status: 2 of 3 files reviewed, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/609)

**Pull request merged**
