### PR TITLE
Bug 1644347 - Perfhderder: Add new test modal - order alphabetically the platforms dropdown

### PR DESCRIPTION
**Pull request by alexandru-io**
This PR is just sorting the option in platform dropdown from add new test modal

### CODE REVIEW

**Comment by alexandru-io** [comment]
> This looks good. But it's lacking test coverage.
> We should take care of that also, so this won't break in the future.

How do you recommend adding coverage? The sort is more of UX, I'm not sure I can call it functional. I also see that the repo dropdown is ordered. Are there coverage tests for that?

**Comment by ionutgoldan** [comment]
> > This looks good. But it's lacking test coverage.
> > We should take care of that also, so this won't break in the future.
> 
> How do you recommend adding coverage? The sort is more of UX, I'm not sure I can call it functional.

Indeed, this is not a functional test. It's a standard UI/UX test.
There's no rule stating that UI/UX tests aren't to be automated (especially if it's possible).
Treeherder doesn't leverage dedicated testing tools for this case (e.g. some mentioned [here](https://testfort.com/blog/why-your-project-needs-ui-ux-testing)). Still, our jest + react-testing-library integrations are capable of doing something very similar to those dedicated tools.

There's a big move from the Treeherder team to focus on UI/UX. Ideally, Perfherder should follow that move at some point. This implies we treat UI/UX matters as first-class-citizens.

> I also see that the repo dropdown is ordered. Are there coverage tests for that?

Not yet. But we have [a WIP PR](https://github.com/mozilla/treeherder/pull/6092) for that specifically.

**Comment by alexandru-io** [comment]
That sounds great. But what I can do for the time being is file a bug so this test be covered at some point. Otherwise, you know I'm time limited for the moment in terms of perfherder development.
> Not yet. But we have a WIP PR for that specifically.

Should I ask kimberly kindly to try and cover this?

**Comment by ionutgoldan** [comment]
Yes, you can file a bug for that. Mark it as good first bug, with me as a mentor.
No need to needinfo? Kimberly on this, as she's focused with the PerfSheriffBot.

**Pull request merged**
