### PR TITLE
Bug 1765755 - Remove any `-vismet` task specific code from all frontends

### PR DESCRIPTION
**Pull request by beatrice-acasandrei**
This should be merged once we have the approval of @gmierz to do so, since these changes depend on the changes he's working on.

### CODE REVIEW

**Comment by jmaher** [comment]
this python test failure is a test issue that seems to be time related- it is showing up on all pull requests now.  please don't spend time investigating this.

**Comment by jmaher** [comment]
if you rebase this revision the tests should pass again.

**Comment by alexandru-io** [comment]
this is the PR where I added the vismet code you need to remove https://github.com/mozilla/treeherder/pull/6964

**Review by gmierz — APPROVED** [review]
Looks good, thanks!

**Review by alexandru-io — APPROVED** [review]

**Pull request merged**
