### PR TITLE
Bug 1212937 - Remove support for OAuth credentials

### PR DESCRIPTION
**Pull request by edmorley**
See individual commits.

This won't be merged until the last of the submitters to Treeherder's API have migrated from using OAuth to the new Hawk credentials (in bug 1212936).

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1087)

### CODE REVIEW

**Comment by maurodoglio** [comment]
Reviewed 3 of 3 files at r1, 25 of 26 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[deployment/update/update.py, line 64 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1087#-K3-ZIeFAr2Zvk3Al8i7)** ([raw file](https://github.com/mozilla/treeherder/blob/bcd0a6aacf52af21899a8a0b1f9cf5734726fd1d/deployment/update/update.py#L64)):</sup>
Can you please explain why we should use a different node?


---

<sup>**[docker/init.sh, line 9 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1087#-K3-lpMN4v7AVbYIIFtM)** ([raw file](https://github.com/mozilla/treeherder/blob/bcd0a6aacf52af21899a8a0b1f9cf5734726fd1d/docker/init.sh#L9)):</sup>
I think we should get rid of the thbootstrap service and run it as a one-off command on the web container. The sleep infinity below makes me very sad.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/1087)

**Comment by maurodoglio** [comment]
A couple of minor comments, but this is a really good patch! I love when you delete so many lines :smiley:

**Comment by edmorley** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[deployment/update/update.py, line 64 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1087#-K3-ZIeFAr2Zvk3Al8i7)** ([raw file](https://github.com/mozilla/treeherder/blob/bcd0a6aacf52af21899a8a0b1f9cf5734726fd1d/deployment/update/update.py#L64)):</sup>
I can't remember exactly the reasoning now, but tbh we're not going to make this change prior to switching to Heroku, so I might as well delete the comment entirely :-)


---

<sup>**[docker/init.sh, line 9 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1087#-K3-lpMN4v7AVbYIIFtM)** ([raw file](https://github.com/mozilla/treeherder/blob/bcd0a6aacf52af21899a8a0b1f9cf5734726fd1d/docker/init.sh#L9)):</sup>
If I remember correctly the sleep infinity trick is a workaround for the containers racing at start up with some of the other potential options for "one off" commands. The story for docker and docker-compose has improved since I played with docker-compose last though.

However since we don't use the docker config, and I didn't write it - I'd be open to either leaving this as is (it's orthogonal to this PR) or ripping out the docker project entirely now (it will always be available in the git log if we want to borrow parts of it in bug 1169263). For all I know the docker project is already broken.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/1087)

**Comment by maurodoglio** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[docker/init.sh, line 9 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1087#-K3-lpMN4v7AVbYIIFtM)** ([raw file](https://github.com/mozilla/treeherder/blob/bcd0a6aacf52af21899a8a0b1f9cf5734726fd1d/docker/init.sh#L9)):</sup>
I agree, we can get rid of it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/1087)

**Comment by edmorley** [comment]
Reviewed 1 of 3 files at r1, 12 of 27 files at r2, 5 of 13 files at r3, 18 of 18 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/1087)*

**Pull request merged**
