### PR TITLE
Bug 1364045 - Introduce Jest unit test framework

### PR DESCRIPTION
**Pull request by camd**
This also fixed a few things that were fixed with ``yarn lint --fix``

### CODE REVIEW

**Comment by edmorley** [comment]
Ah just remembered - could you add `eslint-plugin-jest` to dev dependencies and then add `'plugin:jest/recommended', 'plugin:jest/style'` to the end of the `.eslintrc.js` `extends` array?

**Comment by edmorley** [comment]
For the ESLint failure, I'd add an eslint-disable-line to the old test files for now.

**Comment by edmorley** [comment]
Clearing review for now since Travis failures.

**Comment by camd** [comment]
Not clear why one of the tests doesn't work with ``toHaveLength``.  But I punted and we can fix it when we convert the tests to Jest.

**Comment by camd** [comment]
Test failures cleared up.  :)

**Pull request merged**
