### PR TITLE
Bug 1509181 - Use the GitHub events API to find the date of a push 

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
The new `github_events.json` sample data file is unfortunately very synthetic. The API only returns recent events.

**Comment by SimonSapin** [comment]
Alright, I’m giving in and making a full Vagrant environment to be able to run the tests outside of Travis. I’ll reopen this once it’s ready.

**Comment by SimonSapin** [comment]
Ok, Vagrant took a while to do its thing but was otherwise fairly painless.

----

The "format" (which keys exist with what data) of various JSON blobs from GitHub (webhook data and API responses) is rather inconsistent and poorly documented… I’ve been creating sample data for tests based on the examples of:

* https://api.github.com/repos/servo/servo/events for the Events API
* https://tools.taskcluster.net/pulse-inspector?bindings[0][exchange]=exchange%2Ftaskcluster-github%2Fv1%2Fpush&bindings[0][routingKeyPattern]=%23 for push event messages transmitted by Taskcluster-GitHub integration
* https://tools.taskcluster.net/pulse-inspector?bindings%5B0%5D%5Bexchange%5D=exchange%2Ftaskcluster-github%2Fv1%2Fpull-request&bindings%5B0%5D%5BroutingKeyPattern%5D=%23 for PR messages transmitted by Taskcluster-GitHub integration

**Comment by SimonSapin** [comment]
@edmorley This PR should also fix the exception you mentioned in https://github.com/mozilla/treeherder/pull/4284#issuecomment-442065666 since `head_commit = commits[-1]` is not used anymore.

**Comment by SimonSapin** [comment]
I’ll exercising in staging once it’s there. I don’t have access to Sentry to see if there are Python exceptions, though.

**Comment by edmorley** [comment]
I'll temporarily deploy this to our dev/prototype instance prior to merging (should be deployed in 5 mins; hopefully the status will show up on the GitHub environments section in this PR).

I've also sent an invite to the New Relic account to your moco email :-)

**Comment by SimonSapin** [comment]
I just made three pushes of the "same" (amended) commit. Prod https://treeherder.mozilla.org/#/jobs?repo=servo-try-taskcluster shows all of them at date `Wed, Nov 28, 15:34:57` in an arbitrary order (which is what this PR is trying to fix), but dev https://treeherder-prototype.herokuapp.com/#/jobs?repo=servo-try-taskcluster only shows the first push at all. I don’t find a relevant error in New Relic.

**Comment by edmorley** [comment]
For now I've re-enabled auto-deploy from `master` for the Heroku prototype app.
If it would help with trying to resolve the issue seen above, we could give access to push to the upstream repo, which would mean we could select the branch in the auto-deploy settings, allowing quicker iteration (to test above I had to copy the branch over manually).

**Comment by tomprince** [comment]
I haven't looked at this in detail, but I'll note that the [documentation](https://developer.github.com/v3/activity/events/) indicates that only 300 events or 90 days are available through the API (whichever is less). So I think this may only work for recent pushes (and maybe only *very* recent pushes on a busy repository).

**Comment by SimonSapin** [comment]
This code is running when Treeherder ingests Pulse events about GitHub pushes, which should usually happen seconds after the push happened. Historical data is unchanged, only pushes that happen after this PR is deployed are affected. (The test cases only mention 2016 because we are re-using existing test data.)

Hundreds of events per day on a very busy repository is plausible, but I don’t think we need to worry about hundreds of events per minute. And even then, the code falls back to the current behavior when it cannot find the corresponding GitHub event. (See the `else` part of the `for` loop in `revisions_and_timestamp`.)

**Comment by camd** [comment]
@SimonSapin : Hey there.  Do you have time to rebase this?  I think it is ready to merge once the conflicts are resolved.

**Comment by SimonSapin** [comment]
I can rebase, but my understranding was this required more testing and investigation. In particular https://github.com/mozilla/treeherder/pull/4320#issuecomment-443158329 suggests this PR is buggy.

**Comment by SimonSapin** [comment]
Looks like I broke something in the rebase, but this is all very far out of cache in my head. I’ll leave it at this for today, anyone else feel free to pick it up.

**Comment by camd** [comment]
@SimonSapin : No worries.  I can pick it up.  I may create a branch in the mozilla/treeherder repo and work on it from there.  But I suppose the pertinent question is: Do we still want this feature?  If it is no longer important, we can drop it.

**Comment by SimonSapin** [comment]
Yes, I still think this is a bug that should be fixed. With the current behavior it’s easy to end up with pushes that are shown out of order.

**Comment by armenzg** [comment]
Merged fix:
https://github.com/mozilla/treeherder/pull/6070#event-3115939531

**Pull request closed without merging**
