### PR TITLE
Bug 1268802 - Add a servo repository for treeherder staging

### PR DESCRIPTION
**Pull request by shinglyu**
@wlach Based on https://github.com/servo/servo/issues/10452, we need a servo repository on treeherder staging. Thank you.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1434)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by shinglyu** [comment]
Do I need to open a bugzilla bug for that?

**Comment by tojon** [comment]
@shinglyu just noticed your query in passing :) Yes, if there isn't a bug already, you'd open a new bug in that `Bug [number] - [description]` format to represent the work, and add an r? for @wlach on the PR attachment in the bug. You could also modify this PR title to match if you wish.

**Comment by shinglyu** [comment]
Close and reopen to trigger autolander

**Comment by edmorley** [comment]
@wlach, for this, bug 1267277 and bug 1267716, do you think a new repository group of "other" makes sense? These repos aren't using taskcluster, so don't belong under that category, nor do they fall into the gecko-specific other categories. The repository group is only used for grouping in the UI and isn't saved in any other tables, so we can easily add new (more-specific) groups later if clusters of similar repos emerge.

**Comment by wlach** [comment]
@edmorley Yeah, adding an `other` repository group makes a ton of sense. Let's just do that, I'll make a new PR. :)

**Pull request closed without merging**
