### PR TITLE
Bug 1037670 - Hacks around missing options [wip]

### PR DESCRIPTION
**Pull request by lightsofapollo**
I have some tests locally (but primarily I tested this against some typo I made which omitted collections)

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder-service/332)

### CODE REVIEW

**Comment by maurodoglio** [comment]
https://github.com/mozilla/treeherder-service/pull/329 will completely remove the server side jobs grouping. I'll wait for that one to land before I close this one

**Comment by edmorley** [comment]
Do we still need this?

**Comment by edmorley** [comment]
@maurodoglio do we still need this?

**Comment by maurodoglio** [comment]
I don't think so. And if we find out we need it in the future, we can re-open it.

**Pull request closed without merging**
