### PR TITLE
fix(issue #5768): updating react-hotkeys

### PR DESCRIPTION
**Pull request by parshva-b**
@armenzg I have Updated the package of react-hotkeys to version 2.0.0 (lasted version),
however, even prior to updating the package to this version "Pressing U on the keyboard didn't result in displaying wpt6 jobs but toggling of unclassified jobs".

Attaching a gif to show change:

GIF

Also, there were some prompts which I am not sure I have been before (do let me know if they have occurred before and I don't have to fix them):

Screenshot 2020-01-22 at 8 10 24 PM

### CODE REVIEW

**Comment by armenzg** [comment]
It seems you might have used `npm` instead of `yarn`.
Try to blow away your node_modules/ and only use `yarn`.

Using a [this deployment](https://treeherder.allizom.org/#/jobs?repo=mozilla-central&revision=be3a05f615a557fd4c5171f789cc460688d9c3b8) might make it more clear as to what do "unclassified jobs". It's the orange jobs that don't have a star (starred jobs is done by humans on the production system). We're not looking for wpt6 jobs.

See [this](https://share.getcloudapp.com/04ug8Dxg) gif.

**Comment by parshva-b** [comment]
@armenzg I deleted node_modules/ and package-lock.json and did the configurations via yarn, and the site is working, do you want me to also handle the warnings? (mentioned in the screenshot image -- about react-hot-loader && the warning in red)

**Comment by armenzg** [comment]
If you can start other PRs for those issues it would be great! Thanks!

**Comment by armenzg** [comment]
I will show the correct behaviour and the invalid behaviour.
Start the app with `yarn start:stage` (this will give you a lot of jobs that are not classified - i.e. orange jobs without a star) and load this url: http://localhost:5000/#/jobs?repo=mozilla-central&revision=be3a05f615a557fd4c5171f789cc460688d9c3b8

Correct behaviour (no matter how many times I press U we will only see the R2 job):
Screen Recording 2020-01-22 at 02 17 PM

Invalid behaviour (it shows all orange jobs instead of just the R2 job):
Screen Recording 2020-01-22 at 02 14 PM

**Comment by armenzg** [comment]
The GIFs are simply an explanation of the test case explained in here:
https://github.com/mozilla/treeherder/issues/5786#issue-541784951

**Comment by parshva-b** [comment]
@armenzg, The second commit performed does the functioning described as above:

Attached GIF:
https://drive.google.com/open?id=1DK-zsLqa3PHBXovsoqBWpmS1VY9IxHv1

Content of package.json:
Screenshot 2020-01-23 at 10 50 44 PM

**Comment by armenzg** [comment]
Could you verify that the GIF was based on this branch rather than master?
I tried locally and it does not work. There are code changes besides just package.json/yarn.locl change. Upgrading this package has been backed out twice in the last couple of months.

Make sure these are the steps you follow:
```
git checkout parshva-b-react-hotkeys
yarn
yarn list react-hotkeys
yarn start:stage
```

**Comment by armenzg** [comment]
Closing as per https://github.com/mozilla/treeherder/issues/5786#issuecomment-582854806

**Pull request closed without merging**
