### PR TITLE
Bug 1178300 - Add unique Windows installation steps to RTD

### PR DESCRIPTION
**Pull request by klahnakoski**
I hope master is where this goes

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/684)

### CODE REVIEW

**Comment by tojonmz** [comment]
@klahnakoski curious, is there a bug we can reference for the PR/commit msg? I'm happy to enter a marker bug if needed.

**Comment by edmorley** [comment]
> I hope master is where this goes

Yup, master is correct.

Thank you for opening this PR - I really like improving the docs where possible :-)

A few thoughts:
* I'd recommend using msys ssh rather than putty, since it doesn't require converting the keys (or installing putty). It ships as part of git on Windows, so you just need to make sure the git bin directory is on the path - did the git installer not add the bin dir to your path?
* I think the `core.autocrlf` setting is something that would be great to add to the a-team bootcamp guide instead, so everyone can benefit from it. This guide is mentioned on the Treeherder wiki page ([here](https://wiki.mozilla.org/Auto-tools/Projects/Treeherder#Contributing)), but we should possibly also link to it at the top of http://treeherder.readthedocs.org/installation.html too. We can then link to that when mentioning cloning the repo (eg: "If you're new to Git, check your settings against <link> particularly if using Windows").

With these changes, there are only actually a few things that differ from the Windows and non-Windows installation pages - and as such, I think it makes sense to keep one page and just add a few notes to it for Windows:
* Linking to the bootcamp guide at the very start of the document
* Mentioning making sure the git bin directory is on the path for `ssh` (either by `vagrant ssh` or as a troubleshooting entry)
* Adding a troubleshooting entry for the error ``/home/vagrant/.bash_aliases: line 1: syntax error near unexpected token `$'{\r''``

If you'd rather me make the changes instead due to time contraints, that's ok too - just let me know :-)

**Comment by klahnakoski** [comment]
> did the git installer not add the bin dir to your path?
Git installed fine, but the installer adds `C:\Program Files (x86)\Git\cmd` to the path, not `C:\Program Files (x86)\Git\bin`, so I was never aware it got installed.  I will try that.

> I think the core.autocrlf setting is something that would be great to add to the a-team bootcamp guide
I agree, and I believe the Windows installation anomalies should be in the bootcamp guide for each of the requisite applications, with links from the installation docs.  This way I can refer to those instructions from other projects too.  Even VirtualBox requires detailed instructions (https://github.com/jmaher/alert_manager/blob/master/README_4_WINDOWS.md) which I glossed over.

>Linking to the bootcamp guide at the very start of the document
Agree, and with specific links to each required application

> If you'd rather me make the changes instead due to time constraints
Yes, please make the changes; you have reduced my instructions to a few lines.  I will spend effort on adding Windows install instructions to the bootcamp guide.

**Comment by edmorley** [comment]
> Even VirtualBox requires detailed instructions (https://github.com/jmaher/alert_manager/blob/master/README_4_WINDOWS.md) which I glossed over.

I'm not sure some of that guide is accurate - "Ensure you are HARD WIRED to your network: Virtualbox does not come with drivers that handle wireless networking." is not true, the "Settings->Network->port Forwarding` change isn't needed for Treeherder.

**Pull request closed without merging**
