### PR TITLE
Heroku deployment setup

### PR DESCRIPTION
**Pull request by maurodoglio**
This patch provides a starting point for a deployment on heroku.
The commit list can be squashed later, I figured it was easier to review it this way.
The only 2 addons required are memcachier and cloudamqp, but I think we can easily move to other providers if we need to.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/519)

### CODE REVIEW

**Comment by camd** [comment]
@maurodoglio thanks for doing this!  This is awesome!

Forgive my ignorance, but why was it necessary to use ``pylibmc``?

**Comment by camd** [comment]
Oops.  Now I see.  I just had to read the ``memcacheify`` docs to know.  :)  
https://pypi.python.org/pypi/django-heroku-memcacheify

**Comment by edmorley** [comment]
Reviewed files:
- bin/post_compile @ r1
- deployment/aws/combined-ca-bundle.pem @ r1
- Procfile @ r1
- requirements.txt @ r1
- requirements/common.txt @ r1
- requirements/heroku.txt @ r1
- runtime.txt @ r1
- treeherder/etl/management/commands/export_project_credentials.py @ r1
- treeherder/etl/oauth_utils.py @ r1
- treeherder/model/derived/refdata.py @ r1
- treeherder/model/models.py @ r1
- treeherder/settings/base.py @ r1
- treeherder/webapp/wsgi.py @ r1

---

<sup>**[bin/post_compile, line 2 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7Go3ssc2n113wlqPW)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/bin/post_compile#L2)):</sup>
Missing newline at end of file

---

<sup>**[Procfile, line 1 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7HGAQ4F_2dBMyypn3)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/Procfile#L1)):</sup>
The script in bin/ has a workers count of 5, by setting none here, we default to 1 or the value of WEB_CONCURRENCY. Reading the Heroku docs this should be set automatically for us to sensible defaults (https://devcenter.heroku.com/articles/python-gunicorn#basic-configuration) but I guess we'll want to check/tweak ourselves later.

---

<sup>**[Procfile, line 7 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7IiX2a74ImmdKE3-M)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/Procfile#L7)):</sup>
Missing newline at end of file

---

<sup>**[requirements.txt, line 4 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7Ikibja9TG3Jf50_O)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/requirements.txt#L4)):</sup>
Is there a reason we have both a heroku.txt and also pylibmc loose here?
Would it make sense to move pylibmc to heroku.txt?

---

<sup>**[treeherder/settings/base.py, line 385 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7KRtH70jxlyI90_xE)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/treeherder/settings/base.py#L385)):</sup>
The .format() is superfluous.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/519)

**Comment by maurodoglio** [comment]
Yeah pylibmc is the [suggested memcached client for the memcachier addon](https://devcenter.heroku.com/articles/memcachier#python). 

---





<sup>**[bin/post_compile, line 2 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7Go3ssc2n113wlqPW)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/bin/post_compile#L2)):</sup>
Oops

---

<sup>**[Procfile, line 1 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7HGAQ4F_2dBMyypn3)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/Procfile#L1)):</sup>
Yeah we can tweak WEB_CONCURRENCY once we know more about the load

---

<sup>**[Procfile, line 7 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7IiX2a74ImmdKE3-M)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/Procfile#L7)):</sup>
oops (again)

---

<sup>**[requirements.txt, line 4 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7Ikibja9TG3Jf50_O)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/requirements.txt#L4)):</sup>
Good question. It's a sort of hack that heroku requires to bootstrap the container with libmemcached installed. See the [memcachier docs for python](https://devcenter.heroku.com/articles/memcachier#python) for more info

---

<sup>**[treeherder/settings/base.py, line 385 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7KRtH70jxlyI90_xE)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/treeherder/settings/base.py#L385)):</sup>
Right, I left it by mistake

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/519)

**Comment by edmorley** [comment]
Reviewed files:
- bin/post_compile @ r2
- treeherder/settings/base.py @ r2

---

<sup>**[requirements.txt, line 4 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7Ikibja9TG3Jf50_O)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/requirements.txt#L4)):</sup>
Perhaps we should just move all of the heroku.txt entries to requirements.txt, so they are in one place?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/519)

**Comment by maurodoglio** [comment]
<sup>**[requirements.txt, line 4 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/519#-Jp7Ikibja9TG3Jf50_O)** ([raw file](https://github.com/mozilla/treeherder/blob/ca0bcd996e6c238fbbfe4f1bca93c782852f58ba/requirements.txt#L4)):</sup>
Good idea! This way we just have to remember that requirements.txt is for heroku only and everything will make sense :smiley: 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/519)

**Pull request merged**
