### PR TITLE
Bug 1568623 - [test isolation] Add web-platform-tests support, r=camd.

### PR DESCRIPTION
**Pull request by bclary**

### CODE REVIEW

**Comment by bclary** [comment]
@camd I see you have a similar failure to the one I have in https://travis-ci.org/mozilla/treeherder/jobs/563224032 

What is the correct way of resolving this? Also could you add yourself as a reviewer. I don't seem to have the ability to select reviewers for treeherder pull requests.

**Comment by camd** [comment]
Hi bob, yeah, I broke it by upgrading that rx package too far.  If you rebase this, it should work now.

**Comment by camd** [comment]
@bclary : I added you as a contributor.  You should be able to request reviews now.  :)

**Comment by camd** [comment]
@bclary : The diff on this one looks odd.  Would you be able to do a rebase instead of a merge?

**Comment by bclary** [comment]
> @bclary : I added you as a contributor. You should be able to request reviews now. :)

Thanks. That will help in the future.

**Comment by bclary** [comment]
I thought that is what I did.

In my local copy of bclary/treeherder
git checkout master
git pull upstream master # from mozilla/treeherder
git push origin master to bclary/treeherder
git checkout wpt-test-isolation
git rebase master

git push origin HEAD

# It rejected me.
# I then did

git pull --rebase origin wpt-test-isolation

I can just throw this branch away and try again. This is just a one line patch.

**Comment by camd** [comment]
Hrm, yeah, that looks right.  Not sure what happened there.  But thanks for making the new branch.  :)

**Pull request closed without merging**
