### PR TITLE
Bug 1610347- Vendor dump for BigQuery extract

### PR DESCRIPTION
**Pull request by klahnakoski**
This is a number of dependencies required for the next PR.  At this point, this is dead code.

### CODE REVIEW

**Comment by ionutgoldan** [comment]
@klahnakoski could we upload these dependencies to [Pypi](https://pypi.org/) & require them in our requirements.txt?

**Comment by klahnakoski** [comment]
@ionutgoldan Yes, I was wondering how we should do this: On one hand making a formal package requires extra work to upgrade, but on the other hand hides the code so that others need not read it.

@camd That's what I am look for in this review:  How best to include this block of code?

**Comment by camd** [comment]
@klahnakoski : Could we have a zoom chat about these?  I don't quite follow some of this.  (also asked in your other PR)

**Comment by armenzg** [comment]
After seeing these two PRs I believe the best place for all of this is a different repo rather than Treeherder.

For me, taking code dumps like this means that I would be willing to maintain such code when none of it follows any of the standards that most of us are used. Specially when most of this code will not even be used. I doubt this work will need these 48k lines of code.

**Comment by armenzg** [comment]
For the record, I initially recommended adding such work in Treeherder but I was not aware all other code that would come with it. I should have enquired more and recommended more input. My apologies about it.

**Comment by klahnakoski** [comment]
@armenzg 

I believe this pair of PRs is well behaved:

1. The vendor code is not accessible to the python machine unless it is specifically requested.  https://github.com/mozilla/treeherder/pull/5839/files#diff-ea8d7ce624e923bf52888c66a472298fR7
2. The `vendor` subdirectory is in the `extract` directory: Clearly supporting just one module, and it does not obfuscate the other code.
3. The extract verifies it generates the same SQL as the first run https://github.com/mozilla/treeherder/pull/5839/files#diff-0e7e32bc33e4bb8befee799c4a1037bbR67  Despite it capable of tracking schema changes, it ensures it runs the same every time; requiring a human confirm the new behaviour.
4. The tests specifically confirm the SQL and the generated JSON has not changed; https://github.com/mozilla/treeherder/pull/5839/files#diff-3204ac398d1af9eabc8319728a9b7dd1R45 https://github.com/mozilla/treeherder/pull/5839/files#diff-3204ac398d1af9eabc8319728a9b7dd1R52 requiring a human to confirm the the new behaviour.

So, no matter what chaos you may think in in the vendor lib, its behaviour is constrained on multiple fronts.

> these 48k lines of code.

That is not a fair characterization; with that logic, Treeherder is over a million lines of code. Humans make a distinction between application code and library code based on how specific it is to the application.  Whether the code is vendored, or packaged, is only a matter of style. 

PR https://github.com/mozilla/treeherder/pull/5839 depends on two trees of code: 

1. The treeherder code and 
2. the code found in this PR (at `treeherder/extract/vendor`). 

Here are the options I see for implementing the extract:

* as `vendor`ed code - which is this code, and my first suggestion - it looks like code, but really only runs when PR https://github.com/mozilla/treeherder/pull/5839 is run.  The only time this code needs change is when PR https://github.com/mozilla/treeherder/pull/5839 needs to change, if ever. In the rare event that this code needs to change, it can be done here.
* as a pypi package - Suggested by @ionutgoldan, which will hide the code of this PR in a pypi package. It is the same thing, but in different form. PR https://github.com/mozilla/treeherder/pull/5839 still requires this code.  On the rare case that this code must be change, a new pypi package must be released.  Adding this as a required package has the added detriment of obfuscating the fact that only the `extract` code needs this package.
* fork treeherder - If PR https://github.com/mozilla/treeherder/pull/5839 is not accepted to treeherder, then we must fork treeherder:  The tests in PR https://github.com/mozilla/treeherder/pull/5839 are ensuring the two codebases (the django schema, and the snowflake extraction) work together strictly as expected. 

This final option, which seems to be your suggestion, requires the most support.

**Comment by klahnakoski** [comment]
@ionutgoldan, @armenzg  In order to avoid the maintenance work of a pypi package (deployment scripts, hooking into travis, etc) I propose a `vendor.zip` file (as seen in https://github.com/mozilla/treeherder/pull/5839) which removes he need for this PR

**Pull request closed without merging**
