### PR TITLE
Bug 1619758 - Remove sorting in Intermittent Failures View Table

### PR DESCRIPTION
**Pull request by imskr**
Bug [ID](https://bugzilla.mozilla.org/show_bug.cgi?id=1619758)

@sarah-clements @yogmel

### CODE REVIEW

**Comment by yogmel** [comment]
@imskr it looks good to me. Thanks for the fix!
Sarah can tell you better, but you probably should wait for someone to assign you the bug, before working on it.

Also, Github automatically links the PR URL to Bugzilla, if you add its ID in the PR title.
For example: "Bug 1619758 - Remove sorting in Intermittent Failures View Table".

**Comment by imskr** [comment]
Thanks, @yogmel I already asked about this bug on Bugzilla

**Comment by sarah-clements** [comment]
> Thanks, @yogmel I already asked about this bug on Bugzilla

Yes, you asked about it - but next time please wait for it to be assigned. If no one respected this process, multiple people would submit patches for the same bug.

**Comment by imskr** [comment]
@sarah-clements according to `react-Table` docs using `sortable={false}` should work. But it's not working here

**Comment by yogmel** [comment]
@imskr we were discussing this issue on the public channel. It seems it will need to be changed in the **column header level**.

You can check an example in [Perfherder Health table](https://treeherder.mozilla.org/perf.html#/health) - Platforms and Projects columns are not sortable.

**Comment by imskr** [comment]
@sarah-clements @yogmel I have disabled the sorting.

**Comment by yogmel** [comment]
thanks! It still works for me.
Let's wait for Sarah's input.

**Comment by sarah-clements** [comment]
Looks good - thanks :)

**Pull request merged**
