### PR TITLE
Bug 1453588 - Improve Selenium tests by adding explicit waits

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by davehunt** [comment]
> Btw when I was working on a PR the other day, the selenium travis job was timing out after an hour or so, presumably since the API was raising exceptions and the driver waits were hitting their maximum timeouts for every test. Is there a way to reduce the impact of this? eg fail the run after N successive failures or reduce the default max wait time?

The timeout is 10 seconds, and there are currently 37 tests. Even if they all failed due to a timeout, the entire suite shouldn't take much longer than six minutes. TO answer your question, you can use `--maxfail=num` to stop after a certain number of failures. There's also a pytest-timeout plugin, but that works on the individual tests rather than the suite.

Also, I though Travis stopped any job running for more than 10 minutes without console output...

**Comment by edmorley** [comment]
Ah that's useful to know, thank you. Yeah Travis has the 10 minute with no output cutoff, but there was output in this case. I've managed to find an example log (I ended up cancelling this one):
https://travis-ci.org/mozilla/treeherder/jobs/364230654

**Comment by davehunt** [comment]
It looks like that might be more to do with the amount of console output rather than the time it takes for the tests to fail. We could add something to https://github.com/mozilla/treeherder/blob/master/tests/selenium/conftest.py#L5-L6 so that if a very basic check on the site is failing, we abort the entire suite. Would you like me to look into that?

**Comment by edmorley** [comment]
That's very kind but I think not worth the effort for now. My main concern was whether future warnings (eg pyup bot PR that updates us to a new version of a package that results in new `DeprecationWarning`s) might regularly result in long-running jobs clogging up the Travis queue and/or confusing people looking at the PRs. But may not even be an issue, so happy to leave for now :-)

**Pull request merged**
