### PR TITLE
Docs - README.md - tweaks (ToC, separators)

### PR DESCRIPTION
**Pull request by tiagomoraismorgado88**
## Docs - README.md - tweaks (ToC, separators)

**the current PR does basically aim at adding the following tweaks to the README.md file:**
- *ToC - table of contents*
- *separators*
- *thumbnail logo*
- *reviewing document hierarchical tree*

---

**motivaton for such:**
- *improving overall document accessebility*

---

</img> </img>

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by tiagomoraismorgado88** [comment]
a similar PR had already been closed. i didn't check so. my apologies. feel free to close this if you feel like so

**Comment by edmorley** [comment]
Hi! Yeah there are actually two previous PRs for this - #2807 and #2846, so I'll close this out for the same reasons there. I don't know if you're using a script to find READMEs to update, but if so, perhaps it could query to see if a previous PR exists? GitHub has a handy API to search for "issues" (which actually includes both issues and PRs) here:
https://developer.github.com/v3/search/#search-issues

Anyway, hope you have a great weekend :-)

**Comment by tiagomoraismorgado** [comment]
**you are right @edmorley:**

- *i should look better to see whether a pr has been previously closed*

---

**regarding the script**

- *i am doing it all manually;*
- *i am repeating iteratively some specific tasks as a mean to improve the way i contribute to mozilla repositories on github*

---

**regarding my future contributions to mozilla:**

- *i am planning to keep doing it on a regular basis (for instance, it has improved the lot the way i handle my own readme files.* 
- *maybe spacing my contributions a little wouldn't be a bad idea. while working on some personal projects that can also be used by mozilla.*
- *maybe finding some further field of depth while not repeating actions that have already been rejected.*

---

</img> </img>

**Pull request closed without merging**
