### PR TITLE
Bug-1584135-Perfherder-graph-change 

### PR DESCRIPTION
**Pull request by AlbionaHoti**
@sarah-clements I created a new branch and will close the old one, just started everything from the beginning, the only change is in the function `setRightPadding` I called the `checkDate` function in the return. Please let me know if there is something we can change.

### CODE REVIEW

**Comment by AlbionaHoti** [comment]
Here #5440 you can find the discussion and working path until we managed to solve the issue. 

I add the `checkDate` function in the return of `setRightPadding` function. 
@sarah-clements please, can you review the changes :)

**Comment by sarah-clements** [comment]
This is ready to merge but you first need to change the commit message and this pull request title to include the bug number that this pull request is for. It should include a brief description of the change, for example: 
```
Bug 123456 - Perfherder graph change 
set default date for graph x axis when there is not data
```

**Comment by AlbionaHoti** [comment]
@sarah-clements  Will continue to work on this, update the commit message and reopen pr.

**Comment by AlbionaHoti** [comment]
@sarah-clements It's ready I think now. Please can you review the code :)

**Comment by sarah-clements** [comment]
> @sarah-clements It's ready I think now. Please can you review the code :)

Sorry it took so long to respond - it's been a busy week. You still need to rename your commit, per my comment https://github.com/mozilla/treeherder/pull/5503#issuecomment-546022576

If you type `git log` in your terminal you can see (and also looking at the commit tab on this page) that it doesn't include the bug number - your commit currently says "set default date for graph x axis when there is no data". You need to include the bug number so that our bot adds it to your bugzilla bug. Once you do that, this will be ready to merge.

**Comment by AlbionaHoti** [comment]
> > @sarah-clements It's ready I think now. Please can you review the code :)
> 
> Sorry it took so long to respond - it's been a busy week. You still need to rename your commit, per my comment [#5503 (comment)](https://github.com/mozilla/treeherder/pull/5503#issuecomment-546022576)
> 
> If you type `git log` in your terminal you can see (and also looking at the commit tab on this page) that it doesn't include the bug number - your commit currently says "set default date for graph x axis when there is no data". You need to include the bug number so that our bot adds it to your bugzilla bug. Once you do that, this will be ready to merge.

@sarah-clements I did the change. Can you review it?

**Comment by sarah-clements** [comment]
@AlbionaHoti Were you planning to make the change camd requested? You're very close to getting this pr merged :)

**Comment by AlbionaHoti** [comment]
@sarah-clements @camd Thank you guys for your hints, and sorry for the delay.

**Comment by armenzg** [comment]
You can ignore the Snyk check.

**Comment by sarah-clements** [comment]
This has been merged @AlbionaHoti . Thanks for the great work!

**Pull request merged**
