### PR TITLE
Bug 1593917 - Add management script for cascade deleting old perf frameworks

### PR DESCRIPTION
**Pull request by ionutgoldan**

### CODE REVIEW

**Comment by ionutgoldan** [comment]
I've successfully tested this on my local database to confirm that it's indeed performing the cascade deletes.

**Comment by ionutgoldan** [comment]
@armenzg this is the followup script for [PR 5382](https://github.com/mozilla/treeherder/pull/5382). We need to merge this on master & then run the following command on all our environments.

```bash
./manage.py delete_unused_frameworks
```

It will perform a cascade delete & remove all rows related to perf frameworks we no longer use.
Initially, I was hoping a raw SQL query will do the trick & won't require me to add anything into Treeherder's source code. But I lately found out [Django doesn't ensure ON DELETE CASCADE](https://stackoverflow.com/questions/54751466/django-does-not-honor-on-delete-cascade) foreign key constraints at the database level.

**Comment by ionutgoldan** [comment]
FYI @karlht.

**Comment by ionutgoldan** [comment]
@armenzg great idea! Yes, please execute that REPL on all environments.

Regarding the old `performance_alert_summary`: we don't want to expire those, because many of them are still publicly displayed on Bugzilla. Plus, they don't consume that much space. The real data we were interested in expiring was the `performance_datum` table.

**Comment by armenzg** [comment]
I applied the change on `prototype` and `stage`.
In the morning please let me know if you're comfortable with me applying it on production.

**Pull request closed without merging**
