### PR TITLE
Bug 1212177 - l10n repacks should be displayed in treeherder properly

### PR DESCRIPTION
**Pull request by kmoir**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1361)

### CODE REVIEW

**Comment by edmorley** [comment]
The regex looks fine to me (and a simplistic test in the Python console works: https://emorley.pastebin.mozilla.org/8864670), strange. Perhaps try switching to the multiple regexes in a list style that the `build` type uses? (Since it's more consistent anyway)
https://github.com/mozilla/treeherder/blob/99bd93c4f61c42b1c66d743fdcf00975fbf21b5c/treeherder/etl/buildbot.py#L446-L454

**Comment by kmoir** [comment]
Hmm, that didn't work either, will look at this a bit later, have to work on other bugs now.

**Comment by KWierso** [comment]
FWIW, these changes get the test passing for me: https://github.com/KWierso/treeherder/commit/16d00b0595e1c7e67589544dda9efcae802ada7f

**Comment by camd** [comment]
We has a working PR for this issue.  Thanks for giving it a shot, Kim.  :)  I'll go with his.

**Pull request closed without merging**
