### PR TITLE
Enabled these 3 eslint rules: jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/control-has-associated-label, jsx-a11y/no-static-element-interactions

### PR DESCRIPTION
**Pull request by sabina-rohman**
1. FiltersMenu.jsx
 ================
 eslint rule: "jsx-a11y/no-noninteractive-element-interactions"
 Description: A non-interactive element does not support event handlers.
 In this case, li is a non-interactive element. So, I wrapped it's content in a div, moved the "onclick" event to the div and gave the div a presentation role.

 2. CompareTable.jsx
 ================
 eslint rule: "jsx-a11y/control-has-associated-label"
 Description: An interactive element needs to have a text label.
 In this case, the two table header(th) elements didn't contain any text label. The fix was to give it an aria-label.

 3. BugColumn.jsx
 ==============
 eslint rule: "jsx-a11y/no-static-element-interactions" 
 Description: Static elements must be given a role in order to add events handlers.
 In this case, the span had an onclick event. I added a presentation role to the span.

### CODE REVIEW

**Comment by sarah-clements** [comment]
I see that this branch is on master - it'd be best to create a new branch based off of master because you will eventually delete this branch locally once it's merged. You have merges and commits from your previous bug that shouldn't be included. You should only include the changes for the eslint rules. Use rebase _only_ to keep your branch up-to-date with master. Don't merge and pull (you should do a --force push when pushing to your branch and ignore the message to merge). Please remove all commits except for what pertains to the eslint rules. Then mention me here (@sarah-clements ) for review instead of the chat channel. Thanks!

**Comment by sabina-rohman** [comment]
@sarah-clements so just to be sure, I should be creating a branch (off master) in the mozilla repo itself (and not in the forked repo)? The master branch in the forked repo already contains my previous bug fixes.

**Comment by sarah-clements** [comment]
> @sarah-clements so just to be sure, I should be creating a branch (off master) in the mozilla repo itself (and not in the forked repo)? The master branch in the forked repo already contains my previous bug fixes.

Yes, you should be creating a branch of off the most recent mozilla master, not your forked repo (unless you are keeping that very up to date). Since your first bug was merged, it will of course show your changes in the code. But what I'm saying is since those have already been merged, they shouldn't be included as commits on this branch. You should only include commits relevant to this task. You will need to create a new branch called `a11y-eslint-changes` or similar off of your local master branch (again, this should be updated based on the most recent Mozilla master branch). I'd recommend reading up on Git and how it works - it can be confusing at first but it's important to understand. They are a lot of great resources on the web :)

**Comment by camd** [comment]
I don't think @sabina-rohman has access to create a branch on our main ``mozilla/treeherder`` repo.  I think what you will need to do is

1. create a branch on your fork with your changes.  You can just do ``git checkout -b eslint-fixes`` from your current master.  This new branch will have all your changes.  
2. Go BACK to ``sabina-rohman/treeherder:master`` on your fork and get it back in line with the latest upstream of ``mozilla/treeherder:master``.  This would be most easily done with ``git rebase -i HEAD~14`` where 14 is one more commit than what you've added.  You then delete all the lines for the commits you have added.  This gets you into a clean state that you can then pull down the latest commits we have on ``mozilla/treeherder:master``.

Does that make sense?  A bit complicated.  But, as Sarah says, there are good docs in Github about syncing a fork with ``upstream``.  https://help.github.com/en/articles/syncing-a-fork

**Comment by sarah-clements** [comment]
> I don't think @sabina-rohman has access to create a branch on our main `mozilla/treeherder` repo. I think what you will need to do is

Yeah, what I meant was she should do `fetch upstream` from mozilla/treeherder not the master of her forked repo. But maybe I misunderstood her question :) 

You're explanation is much clearer than mine - thanks!

**Comment by sabina-rohman** [comment]
@sarah-clements @camd I think I kind of got what to do here. My forked master is behind the mozilla master. I need to sync it first, then branch off the synced fork. Sorry about the confusion! And thanks for the detailed explanation :)

**Pull request closed without merging**
