### PR TITLE
Perfherder graphs view - change graphs color scheme

### PR DESCRIPTION
**Pull request by sarah-clements**
I've changed the graph color scheme to include high contrast colors that were previously removed, per feedback. @davehunt Please let me know what you think of these changes.

Screen Shot 2019-07-11 at 1 28 11 PM

### CODE REVIEW

**Comment by davehunt** [comment]
The colours are more distinct, but still seem washed out. It could be just that they were previously bold in the list, perhaps we could try increasing the font weight? Searching around, I found this interesting article on selecting a color palette for data visualisations: https://blog.graphiq.com/finding-the-right-color-palettes-for-data-visualizations-fcd4e707a283

**Comment by sarah-clements** [comment]
> The colours are more distinct, but still seem washed out. It could be just that they were previously bold in the list, perhaps we could try increasing the font weight? 

Making the text bold didn't look quite right.

For comparison, here's the old color palette which seems a bit randomly selected but certainly has some brighter colors:
Screen Shot 2019-07-12 at 10 00 24 AM

I'm wondering if the concern is how the colors from the very first screen shot look on the text rather than how they look on the graph? I've changed the legend style to how it was previously (ignore the odd angle to the borders - I'll need to do some CSS magic there):

Screen Shot 2019-07-12 at 11 05 43 AM

That article you found is interesting and I wish I had more time to spend on selecting a really dynamic color palette that works well for everyone. Le me know how you think we should proceed; If you want to go back to the original color palette and/or style that is fine with me.

**Comment by davehunt** [comment]
Thanks for showing the graph alongside the legend, this does indeed look better. Thanks!

**Comment by armenzg** [comment]
In production.

**Pull request merged**
