### PR TITLE
Bug 1602354 - Highlight alerts proposed for backfill/retrigger

### PR DESCRIPTION
**Pull request by octavian-negru**

### CODE REVIEW

**Comment by octavian-negru** [comment]
@sarah-clements please, review this work. @ionutgoldan is on PTO, returning in 2020, and @airimovici is on PTO until 17 December. It would be great for me to finish this work in time for the demo, which will be in January 2020. Besides, there are another Bugs which must be finished until then.

**Comment by octavian-negru** [comment]
FYI, @karlht

**Comment by sarah-clements** [comment]
@octavian-negru Do you want me to merge this?

**Comment by octavian-negru** [comment]
@sarah-clements yes, it would be nice :)

**Pull request merged**
