### PR TITLE
Bug 1619724 - Alert's name should not be inside the table

### PR DESCRIPTION
**Pull request by Sparsh-Bansal**
I have moved the `gray(header)` part out of the table with same styling as before.

### CODE REVIEW

**Comment by Sparsh-Bansal** [comment]
Screenshot from 2020-11-11 02-38-35
.
Preview after the changes

**Comment by yogmel** [comment]
@Sparsh-Bansal sorry for the late reply. I will try to take a look at it today.
Thanks for your PR!

**Review by yogmel — APPROVED** [review]
This looks great! Tested navigation with NVDA and it looks good :)

**Comment by yogmel** [comment]
Sorry for the late review. Please ask an admin/repo maintainer to review this to merge your PR. Thanks!

**Comment by Sparsh-Bansal** [comment]
@sarah-clements Please review this.

**Review by sarah-clements — APPROVED** [review]
Looks good. Thanks @Sparsh-Bansal and @yogmel :)

**Comment by yogmel** [comment]
@sarah-clements  you're welcome!
Miss you all. I hope you, Cameron, and the Treeherder team are well :)

**Comment by camd** [comment]
> @sarah-clements you're welcome!
> Miss you all. I hope you, Cameron, and the Treeherder team are well :)

Thanks Mellina.  I hope you are well, too!  :)

**Pull request merged**
