### PR TITLE
Bug 1142579 - Display only one log viewer icon for a job

### PR DESCRIPTION
**Pull request by sabina-rohman**

### CODE REVIEW

**Comment by sabina-rohman** [comment]
@camd :That makes sense. I will give it a try. Thanks!

**Comment by sabina-rohman** [comment]
Hi @camd. I used tiers dropdown as an example for building the two log dropdowns. 
I am displaying a dropdown if there are more than one log. If there is only one log url we just show the button.

Few points:

1. All jobs seem to have only one log. How can i find a job with two logs for testing(for now i just tested using fake data)?

2. In the dropdown items i have displayed using this format: log-name (log-id). Is that relevant?

3. As a next step we could build a new react component as we are repeating code in raw log and log viewer. What would you suggest?

**Comment by camd** [comment]
@sabina-rohman : Yes!  Excellent point.  Would you create a component that both lists could share?  Then perhaps pass in the appropriate icon to that component depending on whether it's raw or LogViewer related.  :)

**Comment by sabina-rohman** [comment]
Cool, i will give that a try. But otherwise is there anything else that may need changing code wise? Thanks :)

**Comment by camd** [comment]
This looks really good.  And it seems to work quite well, too.  The only issue I see is that the ``color`` of the raw log dropdown link (when there are multiple) is lighter than the rest of the buttons on that bar.  It should match.

https://www.dropbox.com/s/78rhea819csk7w0/Screenshot%202019-10-07%2017.31.38.png?dl=0

**Comment by sabina-rohman** [comment]
Hi @camd . As discussed, i have created a separate react component for reuse. Also, fixed the raw log button opacity issue (when it has multiple log urls).

**Comment by sabina-rohman** [comment]
Hello @camd. Thanks for merging and also for your help with the bug :)! Much appreciated. I will move to the second assignment now.

**Pull request merged**
