### PR TITLE
Bug 1582108 - Completely remove confirming state

### PR DESCRIPTION
**Pull request by octavian-negru**
23-27 September 2019: @octavian-negru PTO.
@ionutgoldan will make the changes after code review.

Important notice:
Review/change the code, but integrate only after the integration of the below bugs:
`Bug 1582692 - Ensure no one can add 'confirming' state from Perfherder`
`Bug 1582698 - Clean the database of 'confirming' state`

### CODE REVIEW

**Comment by ionutgoldan** [comment]
I experience some inconsistencies when changing status of alerts.
For example, suddenly marking all alerts to `invalid` doesn't update the summary to `invalid`.

Same thing happens for `acknowledged` state.

**Comment by ionutgoldan** [comment]
FYI @karlht

**Comment by ionutgoldan** [comment]
The SQL equivalent of the migration script looks like
```sql
BEGIN;
--
-- Alter field status on performancealert
--
--
-- Alter field status on performancealertsummary
--
COMMIT;
```

@camd I think we aren't really required to do any database migration backup plans. Wouldn't you agree?

**Comment by camd** [comment]
I'm only curious here about records that already are set to ``CONFIRMING``.  Do we need to modify those to a value that matches the new enum?  Or perhaps we don't have any.  :)

**Comment by camd** [comment]
Anyway, I think this is fine without a reverse migration.

**Comment by ionutgoldan** [comment]
> I'm only curious here about records that already are set to `CONFIRMING`. Do we need to modify those to a value that matches the new enum? Or perhaps we don't have any. :)

@camd good question. We won't merge this until [bug 1582698](https://bugzilla.mozilla.org/show_bug.cgi?id=1582698) isn't taken care of. **treeherde-staging** & **treeherder-production** still make use of `CONFIRMIG` states.

**Comment by camd** [comment]
> > I'm only curious here about records that already are set to `CONFIRMING`. Do we need to modify those to a value that matches the new enum? Or perhaps we don't have any. :)
> 
> @camd good question. We won't merge this until [bug 1582698](https://bugzilla.mozilla.org/show_bug.cgi?id=1582698) is taken care of. **treeherde-staging** & **treeherder-production** still make use of `CONFIRMIG` states at the database records level.

Great!  Thanks for clarifying.

**Comment by ionutgoldan** [comment]
@camd I see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1582698#c4) you've taken care of cleaning all environments of the old **CONFIRMING** state.
Thanks to that, we can now merge this to master.

**Pull request merged**
