### PR TITLE
Bug 1519991 - Convert graphs chooser controller to React

### PR DESCRIPTION
**Pull request by sarah-clements**
This pr converts the modal (in the graphs tab when you press the "add test data button") and all functionality inside of it to react, but for the sake of simplicity the original angular controller still exists solely to pass props to the component.

I've changed the modal layout and functionality quite a bit:
- The current implementation would fetch new platforms every time the framework or project was changed, followed by a fetch for series data (for the tests). I changed this by adding an 'update' button to cut down on the number of API calls (and thus rendering) - so the series data will only be retrieved when that's pressed. Refactoring the PerfSeriesModel so that OptionCollectionMap is only retrieved once and saved as a member on the class has also helped to reduce extra API calls.
- When clicking on a title for existing test data that's plotted on the graph ('addRelatedConfigs'), for example, I changed how those related tests are shown in the modal and the message shown if there aren't any.
- I haven't set the default values for framework, platform, etc to be based on the last test data added - only what the opening page default is ('talos', 'mozilla-central' and 'linux64'). If that is desired, I'll add those in.

@ionutgoldan Please test out the modal on prototype and let me know what you think of the changes.

I've temporarily disabled the selenium test that's used to test this modal's functionality because of an issue with that partial not appearing in the DOM (suspect it has to do with the use of react2angular). I'll be sure to get it updated and re-enabled when I finish converting this entire graphs section.

FYI @karlht and @davehunt

### CODE REVIEW

**Comment by ionutgoldan** [comment]
I really like the refreshed look & the snappy feeling!
I'm going to test this today & let you know.

**Comment by ionutgoldan** [comment]
Some small tweaks would possibly make this even better.
In the image bellow, you can see that really long test names are still tricky to cherry pick, as you cannot see the full name. Could we add horizontal scrollbars for both selects? I think this + the filter would address most problems problem nicely.

cannot-see-long-line

**Comment by ionutgoldan** [comment]
Could we bring back the filter-as-you-type functionality? The feedback would be faster & it doesn't cost us any extra API calls, as it only filters already fetched data.

**Comment by ionutgoldan** [comment]
#3 I'd really like to see some basic tooltips when hovering over each dropdown.
These would mean: **Framework**, **Project**, **Platform**.

It would ease things for newcomers a little bit.

**Comment by ionutgoldan** [comment]
#4 It would be nice to pop up from **Tests** sections the tests which we selected.

**Comment by sarah-clements** [comment]
> #3 I'd really like to see some basic tooltips when hovering over each dropdown.
> These would mean: **Framework**, **Project** & **Platform** respectively.
> 
> It would ease things for newcomers a little bit.

I'll add labels back in for those dropdowns.

**Comment by sarah-clements** [comment]
> #4 It would be nice to pop up from **Tests** sections the tests which we selected.

Not sure I follow. If you try to select a test that's already been added to `SelectedTests` you won't be able to add it again (basically you won't be able to add the same test multiple times).

**Comment by sarah-clements** [comment]
> #2 Could we bring back the filter-as-you-type functionality _(from the linux tp5o | filter input)_? The feedback would be faster & it doesn't cost us any extra API calls, as it only filters already fetched data.

Hrm... I enabled the 'enter' button to be used for the filter, not for the 'Plot Graphs' button (since I use the same InputFilter component for all of Perfherder). I could change it to filter-as-you go for this modal and then 'Plot Graphs' would have the enter/submit button functionality. I'm a tad concerned about potential render thrashing with filter-as-you-go but maybe using debounce would work out Ok (might have a slight lag).

**Comment by sarah-clements** [comment]
> Some small tweaks would possibly make this even better.
> #1 In the image bellow, you can see that really long test names are still tricky to cherry pick, as you cannot see the full name. Could we add horizontal scrollbars for both selects? I think this + the filter would address most problems nicely.
> 
> cannot-see-long-line

I ended up adding titles to all text area items (tests) and for the dropdowns so I didn't have to mess with the alignment. Does that work?

**Comment by davehunt** [comment]
Is there any way we can avoid the clicks for updating the framework and filter? This is quite a change in how the chooser works, and whilst it won't take long to retrain myself to click I do this this is more of a step back from the current approach.

I was also a little surprised when clicking on a selected test removed it from the list. Could we add a bit of text to explain this so users understand what's happening? Alternatively, maybe a delete icon next to each test?

Finally, I added a few tests and then tried removing one and it wasn't working. I've attached a screenshot, and I was trying to remove the 'raptor-tp6-google-firefox opt' test.

Screenshot_2019-06-12 Graphs

**Comment by sarah-clements** [comment]
> Is there any way we can avoid the clicks for updating the framework and filter? This is quite a change in how the chooser works, and whilst it won't take long to retrain myself to click I do this this is more of a step back from the current approach.
> 
Thanks for the feedback Dave (and @ionutgoldan!). I've refactored the filter to bring back its type-as-you-go functionality (since the compare and alerts views share the same component, they'll also get this functionality). 

> I was also a little surprised when clicking on a selected test removed it from the list. Could we add a bit of text to explain this so users understand what's happening? Alternatively, maybe a delete icon next to each test?

Can you elaborate on what you would expect to happen if you click on a test that's been added to the `selectedTest` section (rather than it being removed from the list)? It's not obvious to me so this is useful feedback on user behavior. :) I can certainly implement either of your suggestions and look into the bug you mentioned.

**Comment by davehunt** [comment]
> Can you elaborate on what you would expect to happen if you click on a test that's been added to the `selectedTest` section

I would just expect it to be highlighted. I understand that the only practical action here is to remove tests, I just found it a little suprising that the removal is actioned just by clicking on the test. If there was a "click to remove" prompt, this might be enough.

**Comment by sarah-clements** [comment]
> I would just expect it to be highlighted. I understand that the only practical action here is to remove tests, I just found it a little suprising that the removal is actioned just by clicking on the test. If there was a "click to remove" prompt, this might be enough.

I added explanatory text to the Selected Tests label. 

To your earlier question about whether clicking on a framework can result in an instant action as it was before, I'd like to stick with the update button for now. This new implementation will cut API calls down in half (per the old implementation, if a user were to change all three dropdowns at once, platforms is fetched twice and then the test data is fetched for each dropdown action). If it becomes a major pain point, please file a bug and we can come up with another solution in H2.

**Comment by davehunt** [comment]
> I added explanatory text to the Selected Tests label.

Thanks, I think that works well.

> To your earlier question about whether clicking on a framework can result in an instant action as it was before, I'd like to stick with the update button for now. This new implementation will cut API calls down in half (per the old implementation, if a user were to change all three dropdowns at once, platforms is fetched twice and then the test data is fetched for each dropdown action). If it becomes a major pain point, please file a bug and we can come up with another solution in H2.

Are the extra API calls causing a problem? If @ionutgoldan is happy with the extra clicks then let's go ahead as you suggest and see if we can improve it in H2. My concern is that this is not an obvious change from the previous behavior, and requires additional clicks. Perhaps there's a compromise, where 'include subtests' could trigger an update, but framework/repo/platform do not?

I did notice today that when the platform name is long, the update button is pushed down. See screesnhot below. Certainly not a blocker, of course.

Screenshot_2019-06-14 Graphs

**Comment by sarah-clements** [comment]
> Are the extra API calls causing a problem? If @ionutgoldan is happy with the extra clicks then let's go ahead as you suggest and see if we can improve it in H2. My concern is that this is not an obvious change from the previous behavior, and requires additional clicks. Perhaps there's a compromise, where 'include subtests' could trigger an update, but framework/repo/platform do not?

I'm erring on the side of 'if you don't need to make an API call, don't'. During the conversion work I've seen several cases of unnecessary API calls. I do see your point about the work flow change but I think it'd be potentially more confusing to have one button - 'include subtests' - be instant-action and the rest not. I'd like to keep it consistent either way. Perhaps rewording the update button to 'Update tests' or including an explanatory tooltip would add clarity?

> I did notice today that when the platform name is long, the update button is pushed down. See screesnhot below. Certainly not a blocker, of course.

This is expected behavior. I don't like the idea of setting fixed widths for those dropdowns since the name lengths can change and you either end up with widths not wide enough or excessively wide. The 'Include subtests' button will also wrap to the next row, along with the update button, based on certain selections.

**Comment by sarah-clements** [comment]
I've thought about the 'update' button more and since there's been a strong reaction to it, I've removed it and changed the dropdowns back to the instant-action functionality. Prioritizing the UX is probably the right decision here, since the API queries are quick and the instant-action doesn't seem to cause any performance issues.

**Pull request merged**
