### PR TITLE
Update dependency puppeteer to v19

### PR DESCRIPTION
**Pull request by jmaher**

### CODE REVIEW

**Comment by jmaher** [comment]
this is an upgrade from 8->19, many changes including breaking changes.  I have gone over the breaking changes and don't see anything that we are using.  This is really for jest tests.

**Review by Archaeopteryx — APPROVED** [review]
Also requested review from Alexandru because puppeteer is used for testing the graphs.

**Comment by alexandru-io** [comment]
> this is an upgrade from 8->19, many changes including breaking changes. I have gone over the breaking changes and don't see anything that we are using. This is really for jest tests.

can we have a link or so?

**Comment by jmaher** [comment]
@alexandru-io you can view all release notes here: https://github.com/puppeteer/puppeteer/releases.  In general ALL tests continue to pass.

here are the `breaking` changes:
 * https://github.com/puppeteer/puppeteer/releases/tag/v19.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v18.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v17.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v16.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v15.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v14.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v13.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v12.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v11.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v10.0.0
 * https://github.com/puppeteer/puppeteer/releases/tag/v9.0.0

**Review by alexandru-io — APPROVED** [review]

**Comment by jmaher** [comment]
@beatrice-acasandrei and @esanuandra, I don't like bugging people for reviews, but I don't like letting them sit for many days, will you be able to get to this review today/tomorrow?  Also if you don't feel the need to review this, please remove yourself from the reviewers list.

**Review by esanuandra — APPROVED** [review]

**Pull request merged**
