### PR TITLE
Bug 1195493 - Convert partials/main to 2 space indent

### PR DESCRIPTION
**Pull request by tojonmz**
This work fixes Bugzilla bug [1195493](https://bugzilla.mozilla.org/show_bug.cgi?id=1195493).

This converts all 4 space indent in partials/main to 2 space, and while there

* tidies up of long/wrapping lines to 80-100 chars
* consistently orders attributes in a few conspicuous cases
* removes dead closing tags
* adds a few more section comments for clarity

I need to do some blink testing of the affected areas comparing stage vs. this branch, and after that I think will be ready for merge.

Tested on OSX 10.10.3:
Nightly **43.0a1 (2015-08-18)**
Chrome Latest Release **44.0.2403.155 (64-bit)**

Adding @edmorley for review.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/880)

### CODE REVIEW

**Comment by tojonmz** [comment]
Ok, I finished UI blink testing this branch vs. stage and prod for the affected partials, about 45 min of checking and testing (navbars, menus, widgets, resultsets, filter panel, quick filter, sheriff panel). It seems ok.

**Comment by camd** [comment]
Reviewed 13 of 19 files at r1.
Review status: 13 of 19 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ui/partials/main/thMultiSelect.html, line 15 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/880#-Jx1ZM83fXUavjTXQQoW)** ([raw file](https://github.com/mozilla/treeherder/blob/7fcc25a57c8327fa5597750705ea62641091c8ed/ui/partials/main/thMultiSelect.html#L15)):</sup>
spoke in IRC.  May need fixing here.  jfrench doing testing on it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/880)

**Comment by camd** [comment]
Reviewed 6 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/880)

**Comment by tojonmz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ui/partials/main/thMultiSelect.html, line 15 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/880#-Jx1ZM83fXUavjTXQQoW)** ([raw file](https://github.com/mozilla/treeherder/blob/7fcc25a57c8327fa5597750705ea62641091c8ed/ui/partials/main/thMultiSelect.html#L15)):</sup>
Yup, this needs a tweak.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/880)

**Comment by camd** [comment]
<sup>**[ui/partials/main/thMultiSelect.html, line 15 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/880#-Jx1ZM83fXUavjTXQQoW)** ([raw file](https://github.com/mozilla/treeherder/blob/7fcc25a57c8327fa5597750705ea62641091c8ed/ui/partials/main/thMultiSelect.html#L15)):</sup>
This appears to have blades of glory.  Nice going.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/880)

**Pull request merged**
