### PR TITLE
Bug 1640024 - Support group_result in errorsummary.log files

### PR DESCRIPTION
**Pull request by camd**
This re-works the mapping of the `group` table.  It was formerly mapped from `FailureLine` entries when a `FailureLine` had a `group`.  But this was never used and doesn't meet our current needs for `Mozci`.

When Marco added `group_result` entries to that file, we chose to ignore them initially (because that `action` name was too large for the `action` field).  Plus, it would have greatly bloated the size of that table.

So what I have done here is to NOT ingest `group_result` entries as part of the `FailureLine` table, but instead add the `group` value to the `group` table, if it does not already exist.  And then I map from the `JobLog` of the `Job` to the `Group` and the `through` table holds the `status` as a smallint.  This sounds confusing, but I think the code will be better at explaining.  

My hope is that even though the table will have lots of records, each record will only have 3 ints, and therefore be very small.  I'm trying to avoid a huge table size.

This also adds an API endpoint to fetch these results, to make them available to `mozci`:

	GET /api/project/autoland/push/group_results/?revision=910e223290db98b81faeb79224fa4acb25ef29cc

	{
		"bbw5l4-zRTiqvsRzktDHsA": [
			{
				"group": "dom/events/test",
				"status": "OK"
			}
		],
		"dzl5yT2YRhmho5gOeo2euQ": [
			{
				"group": "browser/base/content/test/general",
				"status": "OK"
			},
			{
				"group": "toolkit/components/thumbnails/test",
				"status": "OK"
			}
		],
                ...
        }

UPDATE
--------
This has been on prototype for a few days.  The DB is growing at about the rate I would expect.  This will add some size to our entire DB, but not much.

### CODE REVIEW

**Comment by camd** [comment]
@marco-c : Will this API work for you?

**Comment by marco-c** [comment]
> @marco-c : Will this API work for you?

Yes, that looks like all I need!

**Comment by camd** [comment]
> > @marco-c : Will this API work for you?
> 
> Yes, that looks like all I need!

Great!  I wasn't sure if you'd need the task label as well.  But sounds like the `task_id` is enough, then.

**Comment by camd** [comment]
Taking Sarah off as a reviewer.  I should add this API to the Treeherer Client.  I also need to remove the ForeignKey from `Group` to `FailureLine` as that was never used and will no longer be populated.

**Comment by camd** [comment]
Actually, I will add support in the Treeherder client in a separate PR.

**Review by sarah-clements — APPROVED** [review]
lgtm

**Pull request merged**
