### PR TITLE
Add shippable variants

### PR DESCRIPTION
**Pull request by Callek**
This is adding support for the upcoming Shippable (🚢able) build/test type.

I have a try push showing some of this as it exists today in TH https://treeherder.mozilla.org/#/jobs?repo=try&revision=5f793987c39587be80626f53cf0f5c01b9fe8de2

I'm curious what the thought is behind me doing this, and if I need to use the HTML entity for shippable rather than the unicode char directly, or if I should instead write it out as "shippable"

This is not ready to merge yet, I likely have another platform or two (at least) to add to this map for this work.

### CODE REVIEW

**Comment by Callek** [comment]
CC: @KWierso @camd

**Comment by KWierso** [comment]
I checked out your branch (on Win10) and ran it via yarn, and it appears to work.
Here's what it looks like for me if I filter down to just things with the word "shippable":
screenshot_2019-03-05 99 - 31 try fuzzy query test -qr debug devedition linux win

Not my call to make, but I don't know if adding the emoji adds anything extra beyond just using the word 'shippable'. Without the ability to add a tooltip (which I don't think would work in the map) to explain what it means, I don't think it makes things easier to understand. It only saves one or two characters' worth of space.

**Comment by camd** [comment]
@Callek : Hey there.  Thanks for doing this!  Though I would have to agree with @KWierso about the use of an emoji or icon.  I think just having the word "shippable" would be better.  It comes down to knowing what something means right off the bat as well as screen-readers and such.  I had several complaints years ago about my use of "mystery icons" :)  I still have a few out there, but have leaned toward just using the words.  So my $.02 are to just go with the word "shippable." :)

**Comment by KWierso** [comment]
@Callek Out of curiosity, is the plan to eventually turn off normal opt builds in favor of these new shippable builds? Or at least move most of the testing over to them or something? With all of these new build variants, each push is taking up a lot of vertical space in Treeherder. Would be nice to consolidate things a bit, imo.

**Comment by Callek** [comment]
@camd This is now ready for review.

**Pull request merged**
