### PR TITLE
Bug 1851253 - adjust cache code to support two backends in the future…

### PR DESCRIPTION
**Pull request by jmaher**
…. r=aryx

### CODE REVIEW

**Comment by jmaher** [comment]
this is the same as https://github.com/mozilla/treeherder/pull/7818/files, but without the actual db; both caches are using the same redis cache.

**Review by Archaeopteryx — APPROVED** [review]
Approved as temporary.

**Comment by jmaher** [comment]
should I land this?  I am thinking on staging only

**Comment by Archaeopteryx** [comment]
Ok, please mention here when you revert it.

**Pull request merged**
