### PR TITLE
Bug 1522111: [SETA] Allow setting priority when querying taskcluster jobs.

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by edmorley** [comment]
Could you rebase this on `master`? (there was a force push)

**Comment by Callek** [comment]
CC @jmaher

**Comment by edmorley** [comment]
Those are due to needing a rebase (https://github.com/mozilla/treeherder/pull/4648#issuecomment-464340263)

**Comment by jmaher** [comment]
@edmorley I will let you merge this in and deploy it when you see fit.

**Pull request merged**
