### PR TITLE
Bug 1308990 -- added author_email field to both exclusion profile and…

### PR DESCRIPTION
**Pull request by kkrivera**
… job exclusion models. Added last modified on job exclusion model. Displayed this information. Always update author and last modified fields for both models

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1951)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by kkrivera** [comment]
@camd please review

**Comment by camd** [comment]
I think it's possible to add a ``fields`` section to the ``JobExclusionSerializer`` that is a "through" reference.  Something like ``fields=["name", "description", "info", "modified", "author__email"]``  Something like this should cause the endpoint to return the email of the author, not just the id.

**Comment by camd** [comment]
Hey Kris-- Please rebase on master at your earliest convenience.  There have been some other migrations merged in, so you'll have to tweak yours.

**Comment by kkrivera** [comment]
@camd I have made the necessary changes and tested my commit.

**Comment by camd** [comment]
Hey Kris--  I just tested this out on a DB that had no job exclusions or exclusion profiles.  I tried to create a job_exclusion and got this error:

[2016-11-09 21:15:58,581] ERROR [treeherder.webapp.api.exceptions:25] {'author': {u'non_field_errors': [u'Invalid data. Expected a dictionary, but got long.']}}
[2016-11-09 21:15:58,582] ERROR [treeherder.webapp.api.exceptions:26] Traceback (most recent call last):
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vagrant/treeherder/treeherder/webapp/api/refdata.py", line 129, in create
    return super(JobExclusionViewSet, self).create(request, *args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 221, in is_valid
    raise ValidationError(self.errors)
ValidationError: {'author': {u'non_field_errors': [u'Invalid data. Expected a dictionary, but got long.']}}

Would you be able to try that out?  Perhaps if you delete all your job exclusions and exclusion profiles and start over.  Or you can clean out your database by doing this:

in vagrant:
    
    thpurge

answer yes to all the prompts
drop the ``treeherder`` database (I use mysqlworkbench to do it)
exit vagrant and do:

    vagrant provision

Then, back in vagrant, use ``./manage.py inges_push mozilla-inbount <some recent revision sha you got from production>

**Comment by edmorley** [comment]
@kkrivera do you know if you'll get a chance to look at this? :-)

**Comment by edmorley** [comment]
Closing since the bug has since been wontfixed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1308990#c8

**Pull request closed without merging**
