### PR TITLE
Bug 1281820 - Stop using bug suggestions artifacts

### PR DESCRIPTION
**Pull request by wlach**
Instead, generate the data when required. We will store the return value
of this in memcache for a day to ensure things are responsive for the sheriffs
when classifying recent failures.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1871)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 4 of 8 files at r2, 10 of 19 files at r3.
Review status: 13 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[treeherder/model/error_summary.py, line 23 at r3](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSkoq72LFbqUQnI51dB:-KSkoq73WuedJdh4IaMA:b4si8jk) ([raw file](https://github.com/mozilla/treeherder/blob/0f6370ecb57aa23ba82698e21feb0b0a0ec1a9cd/treeherder/model/error_summary.py#L23)):*
> ```Python
> 
> 
> @memoize(timeout=BUG_SUGGESTION_CACHE_TIMEOUT)
> ```

Hmm

Did you verify that this works? The documentation specifically mentions accessing something multiple times in a single request, and it seems to use the object identity as the cache key, which will change between requests. I think it might work better if you passed `job_id` into this function?

I also note that we never invalidate the cache (for a job). Maybe we should when we call load_error_summary?

---

*[ui/plugins/failure_summary/controller.js, line 14 at r3](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSl18qx90GgVM6AcRRF:-KSl18qyHqc6fEd2SCV4:b-rhlut4) ([raw file](https://github.com/mozilla/treeherder/blob/5da40df112317f9008e711c32b1a0d7a381548bf/ui/plugins/failure_summary/controller.js#L14)):*
> ```JavaScript
>         $log.debug("bugs plugin initialized");
> 
>         var timeoutPromise = null;
> ```

It isn't quite clear to me why all this got removed (I'm not saying it's wrong, just trying to understand).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1871)*

**Comment by edmorley** [comment]
> I think it might work better if you passed job_id into this function?

We don't want the cache to be job-specific, but search-term specific.

**Comment by wlach** [comment]
Review status: 13 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[treeherder/model/error_summary.py, line 23 at r3](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSkoq72LFbqUQnI51dB:-KSm-t2anB1PrMysBnFs:bctp0g9) ([raw file](https://github.com/mozilla/treeherder/blob/0f6370ecb57aa23ba82698e21feb0b0a0ec1a9cd/treeherder/model/error_summary.py#L23)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Hmm
> 
> Did you verify that this works? The documentation specifically mentions accessing something multiple times in a single request, and it seems to use the object identity as the cache key, which will change between requests. I think it might work better if you passed `job_id` into this function?
> 
> I also note that we never invalidate the cache (for a job). Maybe we should when we call load_error_summary?
</details>
Yeah, I think switching to job_id makes sense, as discussed.

I'm not sure why you think we should invalidate the cache for a job when we call load_error_summary? (1) all that does is create a bug suggestions artifact, which we're doing only so we can revert this if needed (2) In almost every case there should be no cache entry when it is called (since it's one of the first things we do, after processing the text log summary).

In general the way I think it should work is that we should warm the error summary after the job is fully parsed (so the initial retrieval by a sheriff is fast). Right now this happens by coincidence because two tasks we run for every job do it (storing the bug suggestion artifact, cross reference error lines). Depending on how we change things in the future we might need to be more deliberate about it.

---

*[ui/plugins/failure_summary/controller.js, line 14 at r3](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSl18qx90GgVM6AcRRF:-KSm2YtpJ6YlW2N8CO6Q:b2etdbn) ([raw file](https://github.com/mozilla/treeherder/blob/5da40df112317f9008e711c32b1a0d7a381548bf/ui/plugins/failure_summary/controller.js#L14)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> It isn't quite clear to me why all this got removed (I'm not saying it's wrong, just trying to understand).
</details>
Formerly we had some logic to reload this tab if the job was loaded but we have no artifact ready. That isn't relevant with this new code (we just block until the bug suggestions are loaded dynamically).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1871)*

**Comment by jgraham** [comment]
Reviewed 4 of 9 files at r1, 1 of 19 files at r3, 3 of 8 files at r5, 19 of 19 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/autoclassify/utils.py, line 51 at r6](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSpaF3rlxUnc3LMqaGj:-KSpaF3rlxUnc3LMqaGk:b60irp9) ([raw file](https://github.com/mozilla/treeherder/blob/9918595d685b683ad18b5b6bc6d8d3cc0bc3f128/tests/autoclassify/utils.py#L51)):*
> ```Python
>     ]
> 
>     with ArtifactsModel(job.repository.name) as artifacts_model:
> ```

So I'm not sure why this patch doesn't remove the use of the artifacts model from here and the crossreference-error-lines code. Was the intent to do that in a followup?

---

*[tests/e2e/test_client_job_ingestion.py, line 10 at r6](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSpbQILwPXO2gkvvZxG:-KSpbQIM1M73prU2wdia:b-utk4hm) ([raw file](https://github.com/mozilla/treeherder/blob/9918595d685b683ad18b5b6bc6d8d3cc0bc3f128/tests/e2e/test_client_job_ingestion.py#L10)):*
> ```Python
> from tests.test_utils import post_collection
> from treeherder.client.thclient import client
> from treeherder.log_parser.parsers import StepParser
> ```

Can we add a test somewhere that the error summary data ends up in the cache after ingesting the job?

---

*[tests/model/derived/test_jobs_model.py, line 473 at r6](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSpnEboKW6FdblgJPsO:-KSpnEboKW6FdblgJPsP:bw9oejc) ([raw file](https://github.com/mozilla/treeherder/blob/9918595d685b683ad18b5b6bc6d8d3cc0bc3f128/tests/model/derived/test_jobs_model.py#L473)):*
> ```Python
>         'failure_lines': (FailureLine,
>                           create_failure_lines(Job.objects.get(
>                               guid=job_not_deleted["job_guid"]),
> ```

Indentation looks sort of weird. Maybe newline after `create_failure_lines(`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1871)*

**Comment by wlach** [comment]
Review status: 25 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/autoclassify/utils.py, line 51 at r6](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSpaF3rlxUnc3LMqaGj:-KSq0EoKpJhph1Jts5QT:b12968x) ([raw file](https://github.com/mozilla/treeherder/blob/9918595d685b683ad18b5b6bc6d8d3cc0bc3f128/tests/autoclassify/utils.py#L51)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> So I'm not sure why this patch doesn't remove the use of the artifacts model from here and the crossreference-error-lines code. Was the intent to do that in a followup?
</details>
Yeah, we're still storing the artifacts in case this needs to be reverted for some reason. I would anticipate pulling this out in a followup a couple days after we deploy if it sticks.

---

*[tests/e2e/test_client_job_ingestion.py, line 10 at r6](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSpbQILwPXO2gkvvZxG:-KSqhJMkF7rVC-27kgK-:b-kl1tmd) ([raw file](https://github.com/mozilla/treeherder/blob/9918595d685b683ad18b5b6bc6d8d3cc0bc3f128/tests/e2e/test_client_job_ingestion.py#L10)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Can we add a test somewhere that the error summary data ends up in the cache after ingesting the job?
</details>
Good idea, ridiculously enough we didn't have a unit test for the most common case (where we parsed the log) so I added one for that and checked the condition there.

---

*[tests/model/derived/test_jobs_model.py, line 473 at r6](https://reviewable.io:443/reviews/mozilla/treeherder/1871#-KSpnEboKW6FdblgJPsO:-KSqhGxNK-2RvBmcb2-0:b-896fix) ([raw file](https://github.com/mozilla/treeherder/blob/9918595d685b683ad18b5b6bc6d8d3cc0bc3f128/tests/model/derived/test_jobs_model.py#L473)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Indentation looks sort of weird. Maybe newline after `create_failure_lines(`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1871)*

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r7.
Review status: 25 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1871)*

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1871)*

**Comment by jgraham** [comment]
FWIW I started investigating changing autoclassify to use the new data structure, and this is somewhat annoying to deal with; I want more of the information from the text_log_error table than is provided in the bug suggestions pseudo-artifact, but I also want the bug suggestions. So I ended up gluing things back together again.

I know it's irritatingly late to suggest this, but is there merit to just putting the bug suggestions in the database, generating the search terms dynamically, and caching the entire response? i.e. add a `TextLogErrorBug` link table, add methods `clean_line` and `search terms` on `TextLogError` and put the whole `text_log_steps` endpoint in a cache? I think this would also simplify the client code for the failure summary panel since we could entirely remove the `bug_suggestions` endpoint and uses of it.

**Comment by jgraham** [comment]
Or, I guess we don't have to put anything in the database if we don't want; it can all go on the model as a set of computed properties which we include in responses, and cache the response.

**Comment by wlach** [comment]
I like your last suggestion. As with many other parts of the datasource-removal refactoring, this PR isn't intended to be what I think the "final" design should be. I expect there will be many followups to further clean things up and make them more logical, now that there isn't such a large cost to doing so.

**Pull request merged**
