### PR TITLE
Bug 1200796 - Locate perf-compare 'Recent' buttons correctly on Chrome

### PR DESCRIPTION
**Pull request by MikeLing**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1106)

### CODE REVIEW

**Comment by tojonmz** [comment]
In local testing the fix looks good to me on Chrome, nice Mike!

On Firefox, I notice that the dimensions of the container are calculated as 81.2167px. Not sure if it's really worth worrying about. I tried in inspector and it appeared I could target the child `button` with an 81px (it has a -1px margin) and then get an integer dimension.

Again, I'm not sure this is worth worrying about, I defer to Will :) I'll r+ it and let you guys decide.

Current :
floatingptwidthfirefox

Tweaking the child `button` with an 81px:
integerptwidthfirefox

Resulting dimension on the parent `div` receiving its new 80px width:
resultingdimension

Maybe also worthwhile tweaking the commit message to be shorter/imperative:

`Bug 1200796 - Locate perf-compare 'Recent' buttons correctly on Chrome`

**Comment by MikeLing** [comment]
Hi French @tojonmz , cause I don't have too much experience of front end(actually, my first css is write for perfherder), I'm curious about why this incorrectly located problem haven't shows up in Firefox when I first write it. Yesterday, I had test it on Safari and Chrome also and them shows problem both.  I can't tell why a css about 'width' will have different behavior between these browser. Is that mean I should test my PR on all these three?

**Comment by tojonmz** [comment]
@MikeLing I don't think it's worth worrying about. :) For reference I was investigating the values purely by manipulating them in inspector, I wasn't changing the source code and then reloading the page. At first glance it seemed the computed box wasn't the width I would have expected based on the added width property in the PR, so I was just poking around a bit. You can see the same floating point dimension on production or stage with that div I think on Firefox, so it's not related to your change.

Officially Treeherder supports Firefox and Chrome, so for me those are the only browsers I generally look at when making front end changes.

Occasionally I'll look at Opera or Safari but only for additional comparisons if there's some discrepancy in behavior between Chrome and Firefox. But not because I intend to fix something on Opera or Safari.

**Comment by wlach** [comment]
Merged in 66450c5400b4aa9425b431beeebf517b5682cd4b

**Pull request closed without merging**
