### PR TITLE
Bug 1718601 - Alerts View - Add copy alert ID button

### PR DESCRIPTION
**Pull request by esanuandra**

### CODE REVIEW

**Review by beatrice-acasandrei — APPROVED** [review]

**Comment by esanuandra** [comment]
Hey, @sarah-clements ! Could you please check this PR and merge it if it's all good? Thank you!

**Comment by esanuandra** [comment]
Clipboard icon appears when we hover over the alert summary's title
image

**Comment by sarah-clements** [comment]
> Clipboard icon appears when we hover over the alert summary's title
> image

Does the clipboard icon have custom styling? Looks a little odd to me.

**Comment by esanuandra** [comment]
> > Clipboard icon appears when we hover over the alert summary's title
> > image
> 
> Does the clipboard icon have custom styling? Looks a little odd to me.

I reused the component Clipboard from threeherder and changed the background to transparent. That's the only change. 
You're right, that screenshot looks odd. I made another one and the icon looks the same as when I run the changes from the branch. 
image

**Review by sarah-clements — APPROVED** [review]

**Pull request merged**
