### PR TITLE
Update Reactstrap version

### PR DESCRIPTION
**Pull request by yogmel**
Update Reactstrap version from 8.3.2 to 8.5.1.

### CODE REVIEW

**Comment by sarah-clements** [comment]
@yogmel Sorry I missed this Mellina. Can you rebase and push it so the tests will run on circleCI (we recently switched)?

**Comment by yogmel** [comment]
@sarah-clements no problem :) I have rebased but it looks like some test has not passed. It seems I don't have the configuration.

**Comment by sarah-clements** [comment]
> @sarah-clements no problem :) I have rebased but it looks like some test has not passed. It seems I don't have the configuration.

I think you rebased onto an old commit. Can you `fetch upstream` before rebasing (and check the git log to make sure you've rebased onto a recent commit) - we switched to circleCI at the end of december :)

**Comment by yogmel** [comment]
I'm pretty sure I rebased as I learned how to do it here, but I forgot it was not on `origin` haha
Now it looks right :)

**Review by sarah-clements — APPROVED** [review]

**Pull request merged**
