### PR TITLE
Bug 1760031 - use latest release/ branch for mozilla-vpn-client. r=ahal

### PR DESCRIPTION
**Pull request by jmaher**

### CODE REVIEW

**Comment by ahal** [comment]
Let's wait for concensus in https://bugzilla.mozilla.org/show_bug.cgi?id=1760031 before we land this PR

**Comment by jmaher** [comment]
sounds good- this should be a simple patch and safe to quickly deploy

**Review by ahal — APPROVED** [review]
Looks good to me with the caveat that I don't know how this works :)

**Comment by sarah-clements** [comment]
> I am sort of guessing how this will really work, but happy to test a bit more or address any feedback/questions.

Looks right to me :)

**Pull request merged**
