### PR TITLE
Bug 1467293 - convert _.filter() usages to ES6

### PR DESCRIPTION
**Pull request by eliottvincent**

### CODE REVIEW

**Comment by eliottvincent** [comment]
In the only usage of _.filter() I found, there were no second parameter: that means there is no predicate function running on the array (first parameter). Hence I can't understand why the _.filter() method is called.
But I still made the conversation to filter() from ES6 JS.

**Comment by edmorley** [comment]
Ah yes that does seem strange - and is likely an existing bug. @wlach any ideas?

**Comment by edmorley** [comment]
(I've also retriggered the selenium test - we have intermittent test failures at the moment: [bug 1465088](https://bugzilla.mozilla.org/show_bug.cgi?id=1465088))

**Comment by eliottvincent** [comment]
Ok the the CI didn't pass because the ES6 method .filter() returns an error if no function is passed in argument.

**Comment by edmorley** [comment]
Ah I retriggered without looking, thinking it was the intermittent failure - oops! :-)

**Comment by camd** [comment]
I *think* this usage of ``_.filter`` had been to weed out any elements that were null for some reason.  So if that's the case, we could pass a function of ``filter(item => item)`` which I think accomplishes that.  Let me test out that theory..  :)

**Comment by camd** [comment]
Yeah, just did a little test to be sure, and that works.  So I think that's what was intended.

**Comment by eliottvincent** [comment]
Ok sounds good to me, I will update the code with this "trick".

**Comment by eliottvincent** [comment]
It looks like Travis failed because of a timeout, @camd can you trigger it again?

**Comment by camd** [comment]
Thanks!  Looks like things passed now.

**Pull request merged**
