### PR TITLE
Tox : removed tests/extract

### PR DESCRIPTION
**Pull request by shubhank-saxena**
@armenzg shifted flake8 and pytest configuration to tox.ini file. Both of them are tested!

### CODE REVIEW

**Comment by armenzg** [comment]
Instead of trying to delete setup.cfg in one shot focus on handling flake8 well that way the PR will be smaller and less convoluted.

**Comment by shubhank-saxena** [comment]
Yes sir. We discussed about pyproject.toml file, but flake8 hasn't yet implemented it officially. I did try to check the changes. Will handle flake8 better. Pytest is working as expected!

**Comment by armenzg** [comment]
I don't want us to use `tox.ini`. If flake8 does not work with pyproject.toml then let's leave it within setup.cfg and file an upstream issue.
If pytest can work with pyproject.toml let's only pursue that.
Thanks!

**Comment by shubhank-saxena** [comment]
@armenzg both flake8 and pytest do not support ```pyproject.toml``` officially. I guess we will have to wait for their pending source PRs to get merged
https://gitlab.com/pycqa/flake8/-/issues/428
https://github.com/pytest-dev/pytest/issues/1556

**Pull request closed without merging**
