### PR TITLE
Bug 1570775 - remove all references to Mac OS X 10.10 from constants.js

### PR DESCRIPTION
**Pull request by worldomonation**
Review request:
@sarah-clements @camd 

Changes:
Removes all references to OS X 10.10 (and its variant representations) in Treeherder, since we are essentially out of 1010 machines.

### CODE REVIEW

**Comment by worldomonation** [comment]
Not sure why it's inheriting from the previous branch that I abandoned, will correct.

**Comment by worldomonation** [comment]
Rebased master to the parent repo, branched and applied the patch, then force pushed. It should be a clean state now, with only 1 commit.

**Comment by worldomonation** [comment]
Any possibility to have the TravisCI build be retriggered, since the failure is with docker container which seems unrelated to my changes.

**Comment by sarah-clements** [comment]
> Any possibility to have the TravisCI build be retriggered, since the failure is with docker container which seems unrelated to my changes.

I've restarted the test. Is this ready to be merged?

**Comment by worldomonation** [comment]
@sarah-clements assuming that it passes the checks, yes, it is ready to be reviewed and merged.

**Comment by worldomonation** [comment]
@sarah-clements I'm sorry, I was told by the sheriffs that this was premature.

Would it be better to revert the merge, or for me to put up a new patch reinstating the changes to effectively cancel them out?

**Comment by sarah-clements** [comment]
I'll revert it but then I'll need to do a prod push. We've switched to doing bi-weekly production pushes so there isn't a lot of time for commits to be on stage before they are merged.

**Pull request merged**
