### PR TITLE
Bug 1185520 - wrap the legacy oauth verification in drf authentication and permission classes

### PR DESCRIPTION
**Pull request by maurodoglio**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/797)

### CODE REVIEW

**Comment by edmorley** [comment]
Travis is failing with `ImportError: cannot import name objectstore`; note bug 1186357 will be removing the objectstore API endpoint soon, but only after it's no longer being used (there are still people submitting to it).

**Comment by maurodoglio** [comment]
This is weird, I removed the objectstore-related files in an attempt to rebase on top of latest master. I'll investigate what happened

**Comment by edmorley** [comment]
Reviewed 15 of 15 files at r1.
Review status: 13 of 15 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/webapp/api/auth.py, line 6 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-Juv5jthUvhIyc6G8c2f)** ([raw file](https://github.com/mozilla/treeherder/blob/d90270568e80c13bb4d5cb79d796b9373573e68e/treeherder/webapp/api/auth.py#L6)):</sup>
Newline before this import? :-)

---

<sup>**[treeherder/webapp/api/auth.py, line 27 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-Juv6_XldxTtkC4dWNVl)** ([raw file](https://github.com/mozilla/treeherder/blob/d90270568e80c13bb4d5cb79d796b9373573e68e/treeherder/webapp/api/auth.py#L27)):</sup>
If we make this a generator, rather than a list, the `all()` will bail sooner if params are missing, eg:
`return all(param in request.query_params for param in oauth_parameters)`

---

<sup>**[treeherder/webapp/api/auth.py, line 53 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-JuvAEqFrNDu1-TJ-o26)** ([raw file](https://github.com/mozilla/treeherder/blob/d90270568e80c13bb4d5cb79d796b9373573e68e/treeherder/webapp/api/auth.py#L53)):</sup>
I know this was just inherited from `oauth_required()`, but I think maybe `request.path` should either be on the same line as `request.get_host()`, or else all three be on separate lines? Though happy to go with what you prefer.

---

<sup>**[treeherder/webapp/api/auth.py, line 81 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-JuvC1jR-s8HYNHT937W)** ([raw file](https://github.com/mozilla/treeherder/blob/d90270568e80c13bb4d5cb79d796b9373573e68e/treeherder/webapp/api/auth.py#L81)):</sup>
The docs (http://www.django-rest-framework.org/api-guide/authentication/#custom-authentication) and the default implementation (https://github.com/tomchristie/django-rest-framework/blob/6e6fa893e46541219caab4e434bb370aeedff831/rest_framework/authentication.py#L105) both return None for the `auth` part of the tuple. I'm not sure I understand what it does and why we're using `my-token` instead? :-)

---

<sup>**[treeherder/webapp/api/jobs.py, line 95 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-Juv5HM1NbyWK9ajz0QA)** ([raw file](https://github.com/mozilla/treeherder/blob/cbefcae35527628c8b4f17869a9f205816a05ad3/treeherder/webapp/api/jobs.py#L95)):</sup>
Hmm was this a mistake before? I don't see why we'd be using `IsAuthenticated` for this method?

---

<sup>**[treeherder/webapp/api/permissions.py, line 8 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-Juv4FTLo2YREKnfTc1Q)** ([raw file](https://github.com/mozilla/treeherder/blob/d90270568e80c13bb4d5cb79d796b9373573e68e/treeherder/webapp/api/permissions.py#L8)):</sup>
This doesn't appear to be used?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/797)

**Comment by maurodoglio** [comment]
Review status: 12 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[treeherder/webapp/api/auth.py, line 81 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-JuvC1jR-s8HYNHT937W)** ([raw file](https://github.com/mozilla/treeherder/blob/d90270568e80c13bb4d5cb79d796b9373573e68e/treeherder/webapp/api/auth.py#L81)):</sup>
Nice catch! It's something I put there when I was testing/debugging.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/797)

**Comment by maurodoglio** [comment]
Review status: 11 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[treeherder/webapp/api/jobs.py, line 95 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-Juv5HM1NbyWK9ajz0QA)** ([raw file](https://github.com/mozilla/treeherder/blob/cbefcae35527628c8b4f17869a9f205816a05ad3/treeherder/webapp/api/jobs.py#L95)):</sup>
I think it was a mistake.

---

<sup>**[treeherder/webapp/api/permissions.py, line 8 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/797#-Juv4FTLo2YREKnfTc1Q)** ([raw file](https://github.com/mozilla/treeherder/blob/d90270568e80c13bb4d5cb79d796b9373573e68e/treeherder/webapp/api/permissions.py#L8)):</sup>
Right

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/797)

**Pull request merged**
