### PR TITLE
Bug 1420180 - Only register base_url and related fixtures for Selenium tests

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by davehunt** [comment]
> Is whatever these fixtures trigger in `pytest-selenium` meant to cause DB creation, or is that a bug too?

There's an autouse fixture here, which loads the initial data. Are you seeing DB creation when calling tests that do not include this module?

**Comment by edmorley** [comment]
Using the show fixtures/setup logs mode thing seemed to suggest the slowdown in the test in bug 1420180  was from DB migrations running.

**Comment by davehunt** [comment]
@edmorley so if the `base_url` fixture is called, the `liveserver` fixture is also called, and an instance of the application is started. Could this be the cause of the DB migrations running?

**Comment by edmorley** [comment]
Ah yes I guess it must run migrations. And presumably even though `base_url` is a `scope="session"` fixture, perhaps `liveserver` is not?

**Comment by davehunt** [comment]
It must be, because fixtures can only depend on other fixtures in the same or broader scope. A session scoped fixture cannot depend on a function scoped fixture.

**Comment by davehunt** [comment]
https://github.com/pytest-dev/pytest-django/blob/218be9676bff3af45db526e2cef72ecde347e59a/pytest_django/fixtures.py#L278-L318

**Comment by edmorley** [comment]
True, though something time consuming must be going on, since it slowed per test execution. This PR will at least mean that cost is only seen by the Selenium tests at least, though it's still there. Anyway just though it worth mentioning :-)

**Comment by davehunt** [comment]
`initial_data` is function scoped, so perhaps it's that? Otherwise, I'll look a little deeper into it shortly.

**Pull request merged**
