### PR TITLE
Bug 1648878 - Change fuzzy finder to accept Fuse.js 6's new enhanced search operators

### PR DESCRIPTION
**Pull request by KWierso**
Fuse.js 4.0 is adding support for search tokens, allowing us to do more precise searches. This commit upgrades to an unreleased version of Fuse.js with that support included, and switches to use it for Treeherder's Fuzzy Job Finder.

### CODE REVIEW

**Comment by KWierso** [comment]
https://github.com/krisk/Fuse/issues/356 describes the extended search options, which look to be exactly like fzf's syntax. Running this branch locally, I'm able to use all of them against the full job list, and it appears to be giving me the expected results.

**Comment by KWierso** [comment]
@camd I wouldn't want to merge this until that's in an official Fuse.js release (thus the draft PR), but figure I'd push up what I have if people want to play around with it now.

**Comment by camd** [comment]
Very interesting.  I look forward to it.  :)

**Comment by KWierso** [comment]
Looks like Kiro's skipping v4 in favor of v5, which should come out of beta within the next couple of weeks.

**Comment by KWierso** [comment]
v5 had some breaking changes to how results are returned, so this updates our usage of Fuse to accomodate that.

**Comment by KWierso** [comment]
An [indexing option](https://fusejs.io/api/indexing.html) was also recently added to Fuse to speed up searches, but I don't think the searching part is what's slow for us (rather, it's the rendering of possibly thousands of task names in the UI that takes forever). Might be worth a look in the future, though...

**Comment by camd** [comment]
@KWierso : Since this is a WIP, I can't merge it.  Is it ready for merge?

**Comment by KWierso** [comment]
Oops, forgot to switch it out of draft mode. Yeah, it should be ready for merge.

**Pull request merged**
