### PR TITLE
Bug 1271598 - Crash matcher based on literal signature matching.

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1481)

### CODE REVIEW

**Comment by wlach** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tests/autoclassify/test_classify_failures.py, line 240 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1481#-KHRGnaog5sKLiqfFpSJ:-KHRGnapcXo7w9nB7VyC:252837543) ([raw file](https://github.com/mozilla/treeherder/blob/9e575a2b45e906719920651df0a6e86fd15e523a/tests/autoclassify/test_classify_failures.py#L240)):*
> ```Python
> 
>     classified_failure = ClassifiedFailure()
>     classified_failure.save()
> ```

You can just do:

```py
classified_failure = ClassifiedFailure.objects.create()
```

here

---

*[tests/autoclassify/test_classify_failures.py, line 245 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1481#-KHRGvmoTOQZy8djUP0x:-KHRGvmoTOQZy8djUP0y:929538229) ([raw file](https://github.com/mozilla/treeherder/blob/9e575a2b45e906719920651df0a6e86fd15e523a/tests/autoclassify/test_classify_failures.py#L245)):*
> ```Python
>                          matcher=test_matcher.db_object,
>                          score=1.0)
>     match.save()
> ```

Likewise, no need to create and then save.

---

*[treeherder/model/models.py, line 658 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1481#-KHRS4iVva6HxjY3Whb6:-KHRS4iVva6HxjY3Whb7:1689735205) ([raw file](https://github.com/mozilla/treeherder/blob/9e575a2b45e906719920651df0a6e86fd15e523a/treeherder/model/models.py#L658)):*
> ```Python
>             if mark_best:
>                 self.best_classification = classification
>                 self.save()
> ```

I found out today that it's best only to update the fields that you need in this kind of operation, using update_fields. See https://bugzilla.mozilla.org/show_bug.cgi?id=1271723

---

*[treeherder/model/migrations/0021_add_index_failureline_signature.py, line 18 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1481#-KHRHSF32Clb1vlP5Ep3:-KHRHSF32Clb1vlP5Ep4:1226080143) ([raw file](https://github.com/mozilla/treeherder/blob/9e575a2b45e906719920651df0a6e86fd15e523a/treeherder/model/migrations/0021_add_index_failureline_signature.py#L18)):*
> ```Python
>             (signature(50));""",
>             """DROP INDEX failure_line_signature_idx ON failure_line;"""),
>     ]
> ```

This looks like yet another migration that's likely to be extremely slow and time out. We should probably run it manually and update the db accordingly, instead of relying on chief or heroku to deploy it. Also, why is this raw sql, and not reflected in the FailureLine model?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1481)*

**Comment by jgraham** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[treeherder/model/migrations/0021_add_index_failureline_signature.py, line 18 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1481#-KHRHSF32Clb1vlP5Ep3:-KHRVDRIh3afZaPV8-EC:976037316) ([raw file](https://github.com/mozilla/treeherder/blob/9e575a2b45e906719920651df0a6e86fd15e523a/treeherder/model/migrations/0021_add_index_failureline_signature.py#L18)):*
<details><summary><i>Previously, wlach (William Lachance) wrote…</i></summary>
> This looks like yet another migration that's likely to be extremely slow and time out. We should probably run it manually and update the db accordingly, instead of relying on chief or heroku to deploy it. Also, why is this raw sql, and not reflected in the FailureLine model?</details>
Because django doesn't support prefix indicies, so you need raw SQL to create one, and putting it in the model file means that the migration generation code will try to create an incorrect migration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1481)*

**Comment by jgraham** [comment]
Updated for review comments.

**Comment by wlach** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[treeherder/model/migrations/0021_add_index_failureline_signature.py, line 18 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1481#-KHRHSF32Clb1vlP5Ep3:-KHRZQErySBXYrut2TOl:1036878503) ([raw file](https://github.com/mozilla/treeherder/blob/9e575a2b45e906719920651df0a6e86fd15e523a/treeherder/model/migrations/0021_add_index_failureline_signature.py#L18)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Because django doesn't support prefix indicies, so you need raw SQL to create one, and putting it in the model file means that the migration generation code will try to create an incorrect migration.</details>
That makes sense, could you add some comments to the model file and this migration to clarify? BTW, I just pushed a new migration to the repository, so this will need to be rebased on that before you land.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1481)*

**Comment by jgraham** [comment]
Added some comments.

**Comment by wlach** [comment]
Reviewed 1 of 2 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, 6 of 6 files at r4.
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1481)*

**Pull request merged**
