### PR TITLE
Bug 1284432 - Use SQL ON DELETE to propogate job-related deletions.

### PR DESCRIPTION
**Pull request by jgraham**
This is expected to perform better than the django solution which has to
load the relationships before performing the deletions.

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1733)

### CODE REVIEW

**Comment by edmorley** [comment]
Thank you for digging into this - it looks like it's been a pain!

Could you explain a bit more as to why Django handles this case badly, and link to the upstream discussions/tickets about this? It seems like something we should encourage them to fix (even if only in parallel to us working around it in the meantime).

Also, I'm wondering if a custom field type wrapping FlexibleForeignKey would be preferable compared to hardcoding this in migrations? I can't believe others aren't also hitting this, there may be prior art around we can use?

Lastly, the way we've been doing cycle-data with the datasource tables was to manually delete the rows from the tables that had a foreign key on the parent table first. What are the disadvantages of just doing the same as that, but with the ORM this time?

Many thanks :-)

**Comment by jgraham** [comment]
> Could you explain a bit more as to why Django handles this case badly, and link to the upstream discussions/tickets about this? It seems like something we should encourage them to fix (even if only in parallel to us working around it in the meantime).

There are various discussions about this, and it is certainly a well-known issue. For example [1] and the linked issues. The underlying problem is that django handles cascading deletes by loading all the child objects to be deleted and deleting them in a way that causes any post-deletion code to be run. This is inherently slower than just asking the database to delete all the child objects when the parent disappears.

> Also, I'm wondering if a custom field type wrapping FlexibleForeignKey would be preferable compared to hardcoding this in migrations? I can't believe others aren't also hitting this, there may be prior art around we can use?

I agree others are hitting this, but I can't see prior art. I don't think that the Django custom field stuff is useful for what we need because it only seems to allow you to specify the datatype, not the full SQL used to construct the field in the first place. I would have to dig into the Django code to be sure however.

> Lastly, the way we've been doing cycle-data with the datasource tables was to manually delete the rows from the tables that had a foreign key on the parent table first. What are the disadvantages of just doing the same as that, but with the ORM this time?

Well it seems more complicated and potentially still slower; instead of letting the database propagate the deletion we have to manually do so. I suppose it will work if there is a reason to prefer that approach. What's your specific concern with this approach?

[1] https://groups.google.com/forum/#!topic/django-developers/FGDanrS9vlw

**Comment by edmorley** [comment]
> What's your specific concern with this approach?

Mainly that we're embedding functionality in the migrations files, when I see them as more just to migrate state, rather than to record it in the first place. This will also mean migration squashing will now become more manual.

That said, I guess once this lands, when we do hand-squash the migrations files in the future, much of this PR can be removed, since we won't be having to try and query for what the existing index names are.

> [1] https://groups.google.com/forum/#!topic/django-developers/FGDanrS9vlw

Ah this is helpful, thank you. It sounds like there is still room for improvement on the Django side - could you reply to that thread (or start a new one) explaining the issues we're having and asking if there could at least be an opt-in way for people to get the standard `ON DELETE CASCADE` behaviour simply by modifying the `on_delete` property, rather than needing to add it themselves?

**Comment by jgraham** [comment]
> Mainly that we're embedding functionality in the migrations files, when I see them as more just to migrate state, rather than to record it in the first place. This will also mean migration squashing will now become more manual.

Arguably that shipped sailed when we wanted to create prefix indexes on text columns, which also isn't supported by Django.

> could you reply to that thread (or start a new one) explaining the issues we're having and asking if there could at least be an opt-in way for people to get the standard ON DELETE CASCADE behaviour simply by modifying the on_delete property, rather than needing to add it themselves?

https://code.djangoproject.com/ticket/26989#ticket

**Comment by edmorley** [comment]
> Arguably that shipped sailed when we wanted to create prefix indexes on text columns, which also isn't supported by Django.

Yeah I agree; though similarly I also see those as something that are a workaround that would be good to replace with native functionality.

> https://code.djangoproject.com/ticket/26989#ticket

Awesome - thank you :-)

**Comment by edmorley** [comment]
Could you add the ticket link as a comment in the migrations file, and then we should be good to go :-)

**Comment by edmorley** [comment]
I've also filed a ticket for adding support for the FULLTEXT INDEXes:
https://code.djangoproject.com/ticket/26990

**Comment by edmorley** [comment]
@jgraham, should we land this or wontfix it?

**Comment by jgraham** [comment]
I don't know. Is cycle-data healthy these days?

**Comment by edmorley** [comment]
Cycle data is working at the moment (or at least the parts this helps are working) - and I think it would be best to wait until Django has native support for this (there has been small movements on the mailing list/issue tracker in the last year).

**Pull request closed without merging**
