### PR TITLE
Bug 1620326 - add pretty label for linux1804-64-tsan

### PR DESCRIPTION
**Pull request by worldomonation**
I'm bad with git, and also Travis wasn't showing tests passed, so I've deleted the branch and re-created it.

### CODE REVIEW

**Comment by worldomonation** [comment]
@sarah-clements this is the new PR - I closed the old one because I deleted the branch on remote.

**Comment by sarah-clements** [comment]
@armenzg Do you have any idea why this travis checks still show as pending (if you click into the details they've shown as passed)? @camd wasn't sure about why this was happening.

**Comment by armenzg** [comment]
> @armenzg Do you have any idea why the travis checks still show as pending (if you click into the details they've shown as passed)? @camd wasn't sure about why this was happening.

I noticed Travis having various issues last week:

- Not showing up at all
- Staying as pending
- Not showing the Retry job button

**Comment by sarah-clements** [comment]
@worldomonation can you try amending your commit and force pushing (not need to merge), just do a `git commit --amend` to make a minor change or do a rebase and force push.

**Comment by worldomonation** [comment]
I've force-pushed, let's see if anything change.

**Comment by worldomonation** [comment]
@sarah-clements  the force push seems to have worked!

**Pull request merged**
