### PR TITLE
Add a "repository" for Servo pull requests

### PR DESCRIPTION
**Pull request by SimonSapin**
Continuing from https://github.com/mozilla/treeherder/pull/4249

### CODE REVIEW

**Comment by SimonSapin** [comment]
Thanks for the review! I don’t have access to click the Merge button, though. Could you do that?

**Comment by edmorley** [comment]
@camd when approving a PR, it's possible to check if they have commit access by hovering their username in the PR and looking at the "contact card" that pops up. If it does not say "Member of ..., mozilla/treeherder" or similar, then they do not have commit access and as such we need to merge the PR at the same time :-) (in cases other than this one where their is an associated bug, if we merge the PR for someone, we need to also close the bug at the same time)

**Comment by SimonSapin** [comment]
https://treeherder.allizom.org/#/jobs?repo=servo-prs is now a thing, but it doesn’t show any push even though https://github.com/servo/servo/pulls/ has PRs newer than the merge :(

**Comment by SimonSapin** [comment]
It does show pushes now! I don’t know what changed.

**Pull request merged**
