### PR TITLE
Bug 1527855 - Switch to autoland as default repository

### PR DESCRIPTION
**Pull request by Archaeopteryx**

### CODE REVIEW

**Comment by edmorley** [comment]
@ionutgoldan should this Perfherder reference be changed too?
https://github.com/mozilla/treeherder/blob/8e88941f74bf62b8b11c212b52aa3873c0891711/ui/perfherder/helpers.js#L378

**Comment by edmorley** [comment]
@jmaher, should these SETA references by updated too? :-)
https://github.com/mozilla/treeherder/blob/8e88941f74bf62b8b11c212b52aa3873c0891711/treeherder/seta/update_job_priority.py#L31
https://github.com/mozilla/treeherder/blob/8e88941f74bf62b8b11c212b52aa3873c0891711/treeherder/seta/update_job_priority.py#L102

@Archaeopteryx, could you update this comment?
https://github.com/mozilla/treeherder/blob/8e88941f74bf62b8b11c212b52aa3873c0891711/tests/selenium/test_switch_app.py#L12

**Comment by jmaher** [comment]
I agree we should update the SETA code to reference and use autoland only- no better way to future proof it.

**Comment by ionutgoldan** [comment]
> 
> 
> @ionutgoldan should this Perfherder reference be changed too?
> 
> [treeherder/ui/perfherder/helpers.js](https://github.com/mozilla/treeherder/blob/8e88941f74bf62b8b11c212b52aa3873c0891711/ui/perfherder/helpers.js#L378)
> 
> Line 378 in [8e88941](/mozilla/treeherder/commit/8e88941f74bf62b8b11c212b52aa3873c0891711)
>  ? ['mozilla-inbound']

Yes, please do replace this with autoland.

**Comment by armenzg** [comment]
This has already landed.
https://github.com/mozilla/treeherder/commit/fa32411a401bfe10c5c6e2a84d0c2b65ecd9f73e#diff-1bb1fe510e4f97a85000f33acabc35f9

**Pull request closed without merging**
