### PR TITLE
Add Login and Info menus to ifv #5443

### PR DESCRIPTION
**Pull request by viicktur**
This adds the HelpMenu and Login components to to the ifv to make it consistent with the perfherder

### CODE REVIEW

**Comment by viicktur** [comment]
@camd or @sclements

**Comment by viicktur** [comment]
@camd @sarah-clements I am an outreachy applicant, i opened a pul request and discovered i have a failed test, please how do i go about this??

**Comment by sarah-clements** [comment]
> @camd @sarah-clements I am an outreachy applicant, i opened a pul request and discovered i have a failed test, please how do i go about this??

There are a few links to our documents in the Project Contribution Section under "a few tips" that show you how to run the test commands in your terminal so you can see what's failing. Clicking into the details of the line "continuous-integration/travis-ci/pr — The Travis CI build failed " above and then the test with the red x will show you what specifically failed.

**Comment by viicktur** [comment]
@sarah-clements i will get back to work on this

**Comment by sarah-clements** [comment]
Closing this since there hasn't been any activity or response. If you're interested in working on it again in the future, we can re-assign the bug to you.

**Pull request closed without merging**
