### PR TITLE
Bug 1278597 - Add job_id__in and repository filtering to /jobdetail/ endpoint

### PR DESCRIPTION
**Pull request by wlach**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1570)

### CODE REVIEW

**Comment by jgraham** [comment]
This looks fine… but I'm not sure why it will be possible to move away from the legacy API in the future but isn't possible now?

<details><summary><i>Previously, wlach (William Lachance) wrote…</i></summary>
> #### Bug 1278597 \- Add job\_id\_\_in and repository filtering to /jobdetail/ endpoint
</details>


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1570#-:-KJfs-iweb0xNA22HWhP:1833289035)*

**Comment by wlach** [comment]
Because the 'id' field for job in the main database doesn't correspond to the 'id' field in the per-project job tables. When we finally *do* move the jobs table to the main database, we'll be able to reference the 'id' field in the main database directly. But in fact we'll be able to do this without changing the user-facing API at all. Does that makes sense? 

<details><summary><i>Previously, jgraham wrote…</i></summary>
> This looks fine… but I'm not sure why it will be possible to move away from the legacy API in the future but isn't possible now?
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1570#-:-KJfusW-KMWWTdcjGutV:-1028684970)*

**Comment by jgraham** [comment]
Well it depends a little on how they are using the ids, right? In the future we will be able to vend a `Job.id` from all the APIs and use that for lookup. I guess that's an improvement over the situation today. However if people have "cached" old ids (e.g. through URLs pasted into bugs) then it will still break, right?

<details><summary><i>Previously, wlach (William Lachance) wrote…</i></summary>
> Because the 'id' field for job in the main database doesn't correspond to the 'id' field in the per-project job tables. When we finally *do* move the jobs table to the main database, we'll be able to reference the 'id' field in the main database directly. But in fact we'll be able to do this without changing the user-facing API at all. Does that makes sense? 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1570#-:-KJfvuj9SW6hs5sQRtcj:1650986240)*

**Comment by wlach** [comment]
Yeah, if we start using the ids from the new table, that will be a backwards incompatible change. I think we still want to do it, but we should warn broadly and loudly before we do.

<details><summary><i>Previously, jgraham wrote…</i></summary>
> Well it depends a little on how they are using the ids, right? In the future we will be able to vend a `Job.id` from all the APIs and use that for lookup. I guess that's an improvement over the situation today. However if people have "cached" old ids (e.g. through URLs pasted into bugs) then it will still break, right?
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1570#-:-KJfyPSx80cDD7pvgYuN:-1429616458)*

**Pull request merged**
