### PR TITLE
Bug 1364045 - Convert all unit tests to Jest

### PR DESCRIPTION
**Pull request by camd**
Also remove all Karma support and update the docs to only mention ``Jest``.

One of the test files was testing some AngularJS filters. I converted these tests to test the equivalent helper functions.

It was a little tricky getting ``fetch`` to work in all the tests.  These tests are mocking ``fetch`` calls with ``fetch-mock``.  There is a ``jest-fetch-mock`` but it does not look as good.  You have to specify the fetch responses in order, rather than mapped by the request itself.  So I decided to stick with ``fetch-mock``.  I filed an upstream issue with ``fetch-mock`` because I know that Ed would ask me to.  ;)  It's also the right thing to do... https://github.com/wheresrhys/fetch-mock/issues/413

### CODE REVIEW

**Comment by camd** [comment]
@edmorley : Thanks for the review and fixup suggestions!  I'm getting a few errors with those changes, though.  I'm trying to work through them now:

     FAIL  tests/ui/unit/context/pushes_test.jsx
        ● Test suite failed to run

    /Users/cdawson/Documents/gitspace/treeherder/node_modules/node-fetch/lib/index.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Stream from 'stream';
                                                                                                    ^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.<anonymous> (node_modules/fetch-mock/src/server.js:1:42)

**Comment by edmorley** [comment]
Oh strange. Those errors look to do with node-fetch's use of `.mjs` -- perhaps downgrade to node-fetch v1.7.3 for now (the last 1.x, before they added mjs file in the package).

**Comment by camd** [comment]
@edmorley - Great idea about the downgrade.  That seems to have fixed it.  :)

**Comment by edmorley** [comment]
(Renovate will open a PR to update `node-fetch` after this merges, however that will be a reminder for me to dig into the mjs issue at some point later)

**Pull request merged**
