### PR TITLE
 	Bug 1198786 - Stop storing performance artifacts

### PR DESCRIPTION
**Pull request by wlach**
They were never used for anything and take up a lot of space. They
also don't fit into the new performance model we're working on. We
can always bring back the useful bits later.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/916)

### CODE REVIEW

**Comment by edmorley** [comment]
Some pretty cool cleanup here! :-)

I didn't spend a huge amount of time looking at the correctness of `test_adapt_and_load()`, but looks ok at a glance.

The comment here refers to the now deleted `performance_artifact` table, so needs updating:
https://github.com/mozilla/treeherder/blob/29881f85d84dd07dd2b4af2a3cea8e326ad79ee3/treeherder/model/sql/template_schema/project.sql.tmpl#L315

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[tests/etl/test_perf_data_adapters.py, line 9 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxfiKl1Q2RxQCZHQEbI)** ([raw file](https://github.com/mozilla/treeherder/blob/7745bcd047a1c6fe065829f49d7537f1b6d05abc/tests/etl/test_perf_data_adapters.py#L9)):</sup>
Is there a reason why this is using unittest when most other things are using pytest?

---

<sup>**[tests/log_parser/test_tasks.py, line 155 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxfbqoakDYXyOU0LxqV)** ([raw file](https://github.com/mozilla/treeherder/blob/abab1ae7f8dd10274b33791da1e3bcf5d45267d1/tests/log_parser/test_tasks.py#L155)):</sup>
`jobs_with_local_talos_log()` seems to be unused now:
https://github.com/mozilla/treeherder/blob/90ba77e596e2c3329e0b840fe45e661e8e2a0370/tests/log_parser/test_tasks.py#L31

---

<sup>**[tests/model/derived/test_jobs_model.py, line 392 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxfaCTPBmf7hcN9CAq6)** ([raw file](https://github.com/mozilla/treeherder/blob/abab1ae7f8dd10274b33791da1e3bcf5d45267d1/tests/model/derived/test_jobs_model.py#L392)):</sup>
`ingest_talos_performance_data()` is now unused:
https://github.com/mozilla/treeherder/blob/90ba77e596e2c3329e0b840fe45e661e8e2a0370/tests/test_utils.py#L341

---

<sup>**[tests/model/derived/test_jobs_model.py, line 416 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-Jxfc9xP9CB5oyQYFTOm)** ([raw file](https://github.com/mozilla/treeherder/blob/abab1ae7f8dd10274b33791da1e3bcf5d45267d1/tests/model/derived/test_jobs_model.py#L416)):</sup>
`get_all_series_signatures` seems to be unused now:
https://github.com/mozilla/treeherder/blob/3bd486709101948b0bc8206d20696a6aee958fb3/treeherder/model/sql/jobs.json#L408

---

<sup>**[treeherder/etl/perf_data_adapters.py, line 184 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxfcWcUmmgUaAFMhEV2)** ([raw file](https://github.com/mozilla/treeherder/blob/7745bcd047a1c6fe065829f49d7537f1b6d05abc/treeherder/etl/perf_data_adapters.py#L184)):</sup>
The `job_id`, `obj`, `name` and `testname` parameters are now unused.

---

<sup>**[treeherder/model/sql/jobs.json, line 361 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxfeIe5pbBPQTHweFQ-)** ([raw file](https://github.com/mozilla/treeherder/blob/7745bcd047a1c6fe065829f49d7537f1b6d05abc/treeherder/model/sql/jobs.json#L361)):</sup>
Leading space added

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/916)

**Comment by edmorley** [comment]
> Is there a reason why this is using unittest when most other things are using pytest?

This needn't block the landing of this; was more of an aside.

**Comment by wlach** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[tests/etl/test_perf_data_adapters.py, line 9 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxfiKl1Q2RxQCZHQEbI)** ([raw file](https://github.com/mozilla/treeherder/blob/7745bcd047a1c6fe065829f49d7537f1b6d05abc/tests/etl/test_perf_data_adapters.py#L9)):</sup>
So not particularly at the moment, but for bug 1192976 it's desirable for it to be a unittest instead of a standard pytest, since the test setup method will be useful for seperating out some database initialization from the rest of the test.

From reading the documentation, I don't think there's really any imperative to use one style exclusively.

---

<sup>**[tests/model/derived/test_jobs_model.py, line 0 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-Jxfc9xP9CB5oyQYFTOm)** ([raw file](https://github.com/mozilla/treeherder/blob/abab1ae7f8dd10274b33791da1e3bcf5d45267d1/tests/model/derived/test_jobs_model.py#L0)):</sup>
This really has nothing to do with performance artifacts, let's remove this in bug 1192976.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/916)

**Comment by wlach** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/model/sql/jobs.json, line 361 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxfeIe5pbBPQTHweFQ-)** ([raw file](https://github.com/mozilla/treeherder/blob/7745bcd047a1c6fe065829f49d7537f1b6d05abc/treeherder/model/sql/jobs.json#L361)):</sup>
Not sure what you mean here? My diff looks ok... I think this might just be reviewable being weird...

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/916)

**Comment by edmorley** [comment]
Reviewed 2 of 3 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/etl/perf_data_adapters.py, line 347 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxkYj4E0Mzh67ve6Wne)** ([raw file](https://github.com/mozilla/treeherder/blob/7745bcd047a1c6fe065829f49d7537f1b6d05abc/treeherder/etl/perf_data_adapters.py#L347)):</sup>
Now that we're not passing `obj` to `_add_performance_placeholder()`, we can remove this too - unless the `validate()` provides some value for the series data too?

---

<sup>**[treeherder/etl/perf_data_adapters.py, line 377 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/916#-JxkYGSvjpS0RdZYUBzU)** ([raw file](https://github.com/mozilla/treeherder/blob/7745bcd047a1c6fe065829f49d7537f1b6d05abc/treeherder/etl/perf_data_adapters.py#L377)):</sup>
Same here

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/916)

**Pull request merged**
