### PR TITLE
Upgrade fuze version and corresponding changes

### PR DESCRIPTION
**Pull request by SuyashSalampuria**
In reference with #6125

### CODE REVIEW

**Comment by SuyashSalampuria** [comment]
@sarah-clements @KWierso I think fuze is ready to be upgraded
Please give your initial reviews

**Comment by KWierso** [comment]
Yeah, looks like your tests pass. If you can run the UI with your changes applied locally and the Add New Jobs (Search) modal still works for you, that's good enough for me.

**Comment by SuyashSalampuria** [comment]
Fully works for me @KWierso @armenzg

**Comment by armenzg** [comment]
Thank you @SuyashSalampuria !

**Pull request merged**
