### PR TITLE
Bug 1197186 project configuration

### PR DESCRIPTION
**Pull request by maurodoglio**
Please review only the last commit.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/901)

### CODE REVIEW

**Comment by edmorley** [comment]
The Travis run is failing with `ImportError: No module named wsgi`.
`.gitignore` needs updating so `settings/local.py` doesn't get checked in.

**Comment by edmorley** [comment]
Out of curiosity, what do you keep in `pycharm_django_settings.py`?

**Comment by maurodoglio** [comment]
oh that file is not mine :stuck_out_tongue:

**Comment by edmorley** [comment]
Ok, but what's in it? :-)
(I'm a believer in checking useful things into the repo and not having lots of handy scripts on each devs machine)

**Comment by edmorley** [comment]
@camd, what's in `pycharm_django_settings.py`? :-)
(I think we should try checking as many useful things into the repo rather than having lots of handy scripts on each dev's machine)

**Comment by camd** [comment]
@edmorley - that file had some settings values that were particular to pycharm to make the debugger work with Vagrant and the treeherder service.  

Though..  I don't even have that file anymore in my repo.  It stopped working on one of the PyCharm updates and I just gave up using it.  I hadn't needed the debugger bad enough to walk their tight rope again.

Please feel free to remove that reference.  If I create one again, I'll check it in.  I guess if it's useful... then... people might like to use it.  :)

**Comment by edmorley** [comment]
So I think we're going to need to split this up into two parts, so we can coordinate more safely with the puppet changes. At the moment, stage/prod uses `local.py` too (the sooner we can get rid of the file everywhere, incl locally, the better IMO), so when this lands they'll break until puppet is made to move the file to the new location.

I suggest adding a try-except to `base.py` (in addition to the one it does for the local.py in the same directory) that loads also tries loading `local.py` from the old location. In addition, we probably want both listed in `.gitignore` for now, to avoid modified working directory type errors during deploy. Then puppet can be updated, and we can land part 2, which removes the 2nd try-except in base.py as well as the old `.gitignore` entry.

Regarding directory structure, given we're trying to move away from `local.py`, I wonder if `treeherder/config/settings/base.py` is a bit too nested? (Given it will soon be on it's own in the directory). So perhaps it should go in the parent directory? Happy to leave this to your judgement however.

**Comment by edmorley** [comment]
The path for local.py also needs to be updated in the following places:
https://github.com/mozilla/treeherder/blob/d5ae8deb9f041ce538eee1a5d8d05c60f09e56be/.coveragerc#L9
https://github.com/mozilla/treeherder/blob/ad3dc73715b844039fbbb03976029a6ec01685e1/puppet/manifests/vagrant.pp#L48

**Comment by edmorley** [comment]
> that file had some settings values that were particular to pycharm to make the debugger work with Vagrant and the treeherder service.

Ah, thank you :-)

**Comment by edmorley** [comment]
Replaced by #1048.

**Pull request closed without merging**
