### PR TITLE
 Bug 1112407 - Remove the "Revision URL List" feature since it doesn't display all changesets

### PR DESCRIPTION
**Pull request by KWierso**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/677)

### CODE REVIEW

**Comment by edmorley** [comment]
There's quite a bit more dead code that can be removed, eg:
https://github.com/mozilla/treeherder/blob/d5ae8deb9f041ce538eee1a5d8d05c60f09e56be/ui/js/directives/resultsets.js#L15-L31
https://github.com/mozilla/treeherder/blob/d5ae8deb9f041ce538eee1a5d8d05c60f09e56be/ui/js/services/main.js#L41
https://github.com/mozilla/treeherder/blob/29a704cc907ec8a64be02dc38d6bff5f555b5771/ui/index.html#L188-L191

**Comment by KWierso** [comment]
Can I just remove that entire directive in that first link? Removing the range you linked to leaves it an empty function.

**Comment by edmorley** [comment]
> Can I just remove that entire directive in that first link? Removing the range you linked to leaves it an empty function.

Yeah - if you could make that change + squash + rebase on master, that should pretty much be it :-)

**Comment by maurodoglio** [comment]
@KWierso any update on this?

**Comment by edmorley** [comment]
Fixed up and merged in:
https://github.com/mozilla/treeherder/commit/c06ba00cd6c8e9eca9fe93554956bf132674d464

**Pull request closed without merging**
