### PR TITLE
Performance artifact submission

### PR DESCRIPTION
**Pull request by wlach**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/971)

### CODE REVIEW

**Comment by camd** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/etl/perf.py, line 31 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-V1eDtVAcff3hun5Gs)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L31)):</sup>
This might be nicer stored in our ``/schemas`` folder so you could point people to it in docs and elsewhere and they could do their own validation.


---

<sup>**[treeherder/etl/perf.py, line 96 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-V2FMXSifhernpJGjd)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L96)):</sup>
same for ``/schemas`` folder here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/971)

**Comment by camd** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/etl/perf.py, line 116 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-VLVI0tnJEtReN7YBk)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L116)):</sup>
You could also use a dict comprehension here:
    transformed_properties = {k:v for k, v in properties.iteritems() if k in significant_keys}


---

<sup>**[treeherder/etl/perf.py, line 149 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-VWusWManRvms6Fsxc)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L149)):</sup>
There is a lot of copy and paste here from the ``load_talos_artifacts``.  Seems like it could be refactored a bit to use shared code.


---

<sup>**[treeherder/etl/perf.py, line 232 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-VVy6aL_o72RwY3qwv)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L232)):</sup>
You don't do anything with the get for this.  I suppose this is just to create and avoid an exception if it already exists?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/971)

**Comment by wlach** [comment]
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[treeherder/etl/perf.py, line 31 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-V1eDtVAcff3hun5Gs)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L31)):</sup>
I didn't think about that, awesome idea. :)


---

<sup>**[treeherder/etl/perf.py, line 116 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-VLVI0tnJEtReN7YBk)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L116)):</sup>
Yeah that would be more concise. I'll change it.


---

<sup>**[treeherder/etl/perf.py, line 149 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-VWusWManRvms6Fsxc)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L149)):</sup>
I'd prefer not to spend time on this, the talos code will be going away in the relatively near future.


---

<sup>**[treeherder/etl/perf.py, line 232 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-VVy6aL_o72RwY3qwv)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L232)):</sup>
Correct.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/971)

**Comment by camd** [comment]
Reviewed 1 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

<sup>**[treeherder/etl/perf.py, line 33 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-tOk2opsqTRFkX4icU)** ([raw file](https://github.com/mozilla/treeherder/blob/69dcc137af01442b81184cd720320a2af3e469af/treeherder/etl/perf.py#L33)):</sup>
Since ``schemas`` is off the root, you can do something like this, rather than all the relative ``..`` stuff:

    file_path = os.path.join("schemas", filename)

But your call.  :)


---

<sup>**[treeherder/etl/perf.py, line 149 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/971#-K-VWusWManRvms6Fsxc)** ([raw file](https://github.com/mozilla/treeherder/blob/05da2674710094dec4bdf050ff8e67ba9c38ac11/treeherder/etl/perf.py#L149)):</sup>
sounds good to me.  I've been in the same boat.  :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/971)

**Pull request merged**
