### PR TITLE
Bug 1437116 - Change "full-user-credentials" scope to "taskcluster-credentials"

### PR DESCRIPTION
**Pull request by helfi92**
Do **not** merge yet!

Will be ready when:
- [x] `taskcluster-credentials` is created on the IAM side
- [x] https://github.com/taskcluster/taskcluster-login/pull/77 is merged

### CODE REVIEW

**Comment by edmorley** [comment]
Many thanks! Flag me for review (via Bugzilla means I get reminders etc, so marginally preferred) when the dependant pieces are ready :-)

**Comment by edmorley** [comment]
For taskcluster-tools it seems to be experiencing something like the issue mentioned above.

eg when I visit this page:
https://tools.taskcluster.net/auth/roles/mozilla-group:active_scm_level_3

The spinner keeps going, and in the console I see:
`Could not renew login:  Object { error: "consent_required", ...`

I'd want to confirm this won't happen to Treeherder too (we can always test out on prototype).

**Comment by helfi92** [comment]
> The silent renewal fails, but they don't get logged out straight away (thanks to #3228), and instead once the 24 hours is up, the UI changes to logged out and they have to perform a full login (with new permissions prompt)?

Correct.

> Is there separate handling for the 24 hours case? I'm just thinking the Django API /user/ endpoint is only hit on pageload, so if the user keeps the tab open, will it still know that it's logged out?

Created https://github.com/mozilla/treeherder/pull/3233 to handle this. This would probably help.

**Comment by helfi92** [comment]
@edmorley You okay if I merge this one now?

**Comment by edmorley** [comment]
Yup!

**Pull request merged**
