### PR TITLE
Bug 1311465 - Replace uses of django-memoize with django's default cache

### PR DESCRIPTION
**Pull request by wlach**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1937)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[treeherder/model/error_summary.py, line 4 at r1](https://reviewable.io:443/reviews/mozilla/treeherder/1937#-KUU-BFAvIXkoijFIWcA:-KUU-BFAvIXkoijFIWcB:birr6wk) ([raw file](https://github.com/mozilla/treeherder/blob/5cef814f0f7670c12bc847d04a361aea4e8a5f13/treeherder/model/error_summary.py#L4)):*
> ```Python
> import re
> 
> from memoize import memoize
> ```

Do you want to remove this from the requirements.txt?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1937)*

**Comment by edmorley** [comment]
With the requirements.txt change, this is ready to land yeah?

**Comment by wlach** [comment]
Patches have since landed which also use django memoize, so we'd need to modify that code to use the django cache as well. I guess it makes sense to do that as part of this bug, so we can hold off on landing this.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1937#-:-KV5RaEB00u9ta6_LYlA:b-nty7ui)*

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[treeherder/model/models.py, line 594 at r2](https://reviewable.io:443/reviews/mozilla/treeherder/1937#-KVVhvopz3DdLTZ4_Ii_:-KVVhvoqKuddhud54Kh4:b-6h1dcw) ([raw file](https://github.com/mozilla/treeherder/blob/7146ae6ac60f7640bb3fa87b1aff5eca0d4a14a2/treeherder/model/models.py#L594)):*
> ```Python
>         for exclusion_profile in ExclusionProfile.objects.all():
>             exclusion_profile.save()
> ```

Why is this safe to remove?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1937)*

**Comment by wlach** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[treeherder/model/models.py, line 594 at r2](https://reviewable.io:443/reviews/mozilla/treeherder/1937#-KVVhvopz3DdLTZ4_Ii_:-KVVj5g8tLOn9qstbO1C:byqnnsu) ([raw file](https://github.com/mozilla/treeherder/blob/7146ae6ac60f7640bb3fa87b1aff5eca0d4a14a2/treeherder/model/models.py#L594)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Why is this safe to remove?
</details>
The calls to exclusion profile's save() method will take care of invalidating the cache.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1937)*

**Pull request merged**
