### PR TITLE
BUG 1600744 : Docker image and host share node_modules subdirectory

### PR DESCRIPTION
**Pull request by shubhank-saxena**
@armenzg @klahnakoski I have tried to fix this issue! Kindly do let me know if any further changes are required!

### CODE REVIEW

**Comment by klahnakoski** [comment]
@shubhank-saxena let me check this out...

**Comment by shubhank-saxena** [comment]
> The frontend docker container does not start on windows. I do recall pointing out in a previous PR that `sh` does not work on windows, but I guess that was ignored and merged anyway?
> 
> ```
> frontend           | ✖ ｢wdm｣: Time: 1328ms
> frontend           |
> frontend           | ERROR in Entry module not found: Error: Can't resolve 'sh' in '/app'
> frontend           |
> frontend           | ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:5000 (webpack)/hot/dev-server.js sh
> frontend           | Module not found: Error: Can't resolve 'sh' in '/app'
> frontend           | ℹ ｢wdm｣: Failed to compile.
> ```
> 
> The `yarn build` and `yarn start` appear to work on windows, but the resulting page (localhost:5000) shows nothing. I am not sure if node web service is connecting to the backend (localhost:8000).

To work around this, maybe we can remove that command from docker-compose and have RUN command in our new frontend dockerfile

**Comment by shubhank-saxena** [comment]
@klahnakoski I have made the changes! Let me know if it works or not!

**Comment by shubhank-saxena** [comment]
@klahnakoski 
- [x] Now working with [minified](https://github.com/mozilla/treeherder/blob/master/docs/installation.md#using-the-minified-ui)
- [x] Working in docker image ```docker-compose up --build```
- [x] Tests are implemented the same way they were going on (no changes)

Unfortunately, I don't have Windows Pro with me. Is there any machine on which I can try windows specific issues?

**Comment by shubhank-saxena** [comment]
> I think `EXPOSE 8000` should read `EXPOSE 5000`.
> 
> I still see no instructions for
> 
>     * what to run when working on the frontend
> 
>     * what to run when working on the backend
> 
>     * Running all services in docker except frontend
> 
>     * running just the frontend in docker

Sir there isn't any need for new instructions. Everything is working the same way that it was previously.

**Pull request closed without merging**
