### PR TITLE
 Bug 1270627 - Support release promotion jobs 

### PR DESCRIPTION
**Pull request by hfkang**
- Uptake Monitoring
- Checksums Builder
- Bouncer Submission
- Release Promotion Updates
- Version Bump
- Bouncer Aliases

These jobs are to be processed from buildbot logs, instead of pushes from treeherder

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1540)

### CODE REVIEW

**Comment by edmorley** [comment]
Many thanks for the PR :-)

Looks good - could you just add some tests to:
https://github.com/mozilla/treeherder/blob/master/tests/etl/test_buildbot.py

Also please rebase, squash, and use a commit message like:
"Bug 1270627 - Support release promotion jobs" (or similar)

**Comment by edmorley** [comment]
Thank you for updating the PR :-)

All platforms also have to be added to `ui/js/values.js` too. However I wonder if the existing "other" platform might be a better name than "all"?

Also, should the already supported "Update Verify" job be moved with the rest of these? "Update Verify" is also currently categorised as a unit test, rather than a build. I don't know what's most appropriate for all of these.

**Comment by hfkang** [comment]
I've changed the platform to "other" for now, since the platform is a little ambiguous on these jobs. 
Also it seems job_type is no longer being used anywhere, so I've removed it entirely.

**Comment by edmorley** [comment]
Many thanks - FF merged as https://github.com/mozilla/treeherder/commit/0d9ae7a6b2b2555f700c53ffd2aa39b376f1260e and https://github.com/mozilla/treeherder/commit/3b2d48d319380e500e43812f7fecbf28c861fb1a

**Pull request closed without merging**
