### PR TITLE
Bug 1249407 - Adding some checks to ensure correct resultset rendered

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1320)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by edmorley** [comment]
The Travis failures are due to indentation issues:
https://travis-ci.org/mozilla/treeherder/jobs/112280313#L236

Review comments at:
https://bugzilla.mozilla.org/show_bug.cgi?id=1249407#c12
(So I don't glance at this in the future and think it's missing a review :-))

**Comment by martiansideofthemoon** [comment]
@edmorley , I highly doubt this will work / needs to be fixed. I think we can close this PR if @wlach agrees

**Comment by edmorley** [comment]
Ok let's close for now - we can always reopen if the discussion in the bug proves otherwise :-)

**Pull request closed without merging**
