### PR TITLE
Fix a bug in bugdetails route that breaks page with invalid bug number

### PR DESCRIPTION
**Pull request by sarah-clements**
Tested as follows:
1) from the main IFV route - click on a bug (shows expected graph and table)
2) from a url of bugdetails view with a valid bug number (shows expected graph and table)
3) from a url of bugdetails view with an invalid bug number (shows the messaged added from this pr)

### CODE REVIEW

**Comment by sarah-clements** [comment]
I'll also add in error boundaries when I work on improving error handling for the whole app (on my TODO list).

**Comment by camd** [comment]
I tried this locally and when I clicked on ``details`` for one of the bugs, I got an error message on the console saying: ``original.lines is undefined``

My URL was: http://localhost:5000/intermittent-failures.html#/bugdetails?startday=2018-06-06&endday=2018-06-13&tree=trunk&bug=1464541

**Comment by camd** [comment]
Making the bug in the URL something invalid did the same thing.  @sarah-clements: would you take a look?

**Comment by sarah-clements** [comment]
@camd Ah, I should've mentioned: the backend change from my previous commit that modified the failures endpoint to include error lines hasn't been pushed to production yet so you'll need to run the server locally to avoid that undefined message.

**Comment by edmorley** [comment]
`yarn start` uses the proxy feature of webpack-dev-server, so requests still go to localhost, but are then proxied to prod/stage.

**Comment by camd** [comment]
oh sorry, my bad...  Hrm, then seems like it should have worked with ``yarn start:stage``.  I must have flubbed something...  :)

**Comment by camd** [comment]
You know, I'm going to claim temporary insanity on this one.  It's now working against stage.  Not sure what I did wrong before.  So, please just nevermind me...  :)  I was able to test your cases and they worked well.

**Pull request merged**
