### PR TITLE
Bug 1851253 - store new failure lines in database for persistent stor…

### PR DESCRIPTION
**Pull request by jmaher**
…age across reboots.

### CODE REVIEW

**Comment by jmaher** [comment]
I will be looking into more unittests and running some more local tests; I wanted to make sure all the CI automation ran before polishing this up

**Comment by jmaher** [comment]
the strategy here is to use a database backed cache (instead of redis that we are using now- which is non persistent).  When the system is restarted or redeployed, we will retain our cache as it is backed by a database (same DB that we store TH data in).  This could be used for other things, but for now it will only be used for the line_cache that determines what we have seen.

**Review by Archaeopteryx — APPROVED** [review]

**Comment by jmaher** [comment]
as this was backed out, I have looked what might be the cause.  I am honestly not sure, there is little to no code here.

The database cache creates a table and stores the cache values via pickle in a longtext field.  This can be up to 4GB in size (effectively not a limit- or we would have had a limit with redis in memory as well) - I would be surprised if we were using >50MB of data.

my thoughts are to put in the plumbing for multiple caches, but not setup the database cache.  Ensure that lands successfully.  Then try the database again.  @Archaeopteryx does this sound reasonable to you?

**Comment by Archaeopteryx** [comment]
SGTM.

**Pull request merged**
