### PR TITLE
Add field for searchable data in the commit table

### PR DESCRIPTION
**Pull request by osujipius**
This PR fixes mozilla/perfcompare#795

The commit table is modified to include a new field `search_data` that will be used to hold all searchable data related to relevant records

```
push = models.ForeignKey(Push, on_delete=models.CASCADE, related_name="commits")
revision = models.CharField(max_length=40, db_index=True)
author = models.CharField(max_length=150)
comments = models.TextField()
search_data = models.TextField(blank=True, null=True)
```

### CODE REVIEW

**Comment by julienw** [comment]
hey @osujipius, would you please edit the PR so that it's against the repository https://github.com/Carla-Moz/treeherder/? You should be able to edit it at the top of the page, and pick it frop the dropdown selection box.

Thanks!

**Comment by osujipius** [comment]
> hey @osujipius, would you please edit the PR so that it's against the repository https://github.com/Carla-Moz/treeherder/? You should be able to edit it at the top of the page, and pick it frop the dropdown selection box.
> 
> Thanks!

Oh sure!
But I can't seem to find it in the dropdown box

**Comment by osujipius** [comment]
@julienw I think it might mean me closing this and reopening it against Carla's fork
Does that work?

**Comment by julienw** [comment]
(moved to https://github.com/Carla-Moz/treeherder/pull/7)

**Pull request closed without merging**
