### PR TITLE
Correct Tests of CommitHistory.jsx

### PR DESCRIPTION
**Pull request by SuyashSalampuria**

### CODE REVIEW

**Comment by SuyashSalampuria** [comment]
@camd Can we merge it

**Comment by camd** [comment]
Oh, I hadn't noticed the tests were failing.

**Comment by camd** [comment]
The failures are in Python tests which have no bearing on this change.  Another Travis issue.  I may merge without them if they keep failing for no reason.

**Comment by SuyashSalampuria** [comment]
> he failures are in Python t



> The failures are in Python tests which have no bearing on this change. Another Travis issue. I may merge without them if they keep failing for no reason.

The last two tests - shell and nodeJS12.13.0  are failing on every PR

**Pull request merged**
