### PR TITLE
Bug 1276030 - Refetch all job data after a long period of inactivity

### PR DESCRIPTION
**Pull request by wlach**
Specifically, if there have been 15+ minutes of *not* polling (indicating
the machine has gone to sleep, or similar) we should not poll for new jobs.
In the case that we've loaded many result sets, this can generate an
extremely time consuming set of queries, and almost certainly the user doesn't
care about the results in this case.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1523)

### CODE REVIEW

**Comment by camd** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ui/js/models/resultsets_store.js, line 942 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1523#-KJNPUcxtTREj78KwhzU:-KJNPUcxtTREj78KwhzV:228267149) ([raw file](https://github.com/mozilla/treeherder/blob/bc0e4d39b88c6624d22067a678c26a3e8d95c693/ui/js/models/resultsets_store.js#L942)):*
> ```JavaScript
>                     );
>                     $q.all(jobsPromiseList).then(function(resultSetJobList) {
>                         var lastModifiedTimes = _.filter(_.flatten(
> ```

it seems like the ``_.filter`` and ``_.flatten`` here are unnecessary.  The list from ``_.map`` will already be flat.  And filter has no predicate, so it'll just return everything.

Though I could definitely be missing something!  :)  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1523)*

**Comment by wlach** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ui/js/models/resultsets_store.js, line 942 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1523#-KJNPUcxtTREj78KwhzU:-KJb47V4ecMPVPv5JLrM:711932298) ([raw file](https://github.com/mozilla/treeherder/blob/bc0e4d39b88c6624d22067a678c26a3e8d95c693/ui/js/models/resultsets_store.js#L942)):*
<details><summary><i>Previously, camd wrote…</i></summary>
> it seems like the ``_.filter`` and ``_.flatten`` here are unnecessary.  The list from ``_.map`` will already be flat.  And filter has no predicate, so it'll just return everything.
> 
> Though I could definitely be missing something!  :)  
</details>
By default _.filter will omit falsey values, so if getLastModifiedJobTime returns undefined, it won't be included. However, you're right that flatten shouldn't be necessary... I think that's a relic of an earlier iteration on this patch. I'll remove it before landing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1523)*

**Comment by wlach** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ui/js/models/resultsets_store.js, line 942 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1523#-KJNPUcxtTREj78KwhzU:-KJfvybFYf3uWe0MPEW2:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/bc0e4d39b88c6624d22067a678c26a3e8d95c693/ui/js/models/resultsets_store.js#L942)):*
<details><summary><i>Previously, wlach (William Lachance) wrote…</i></summary>
> By default _.filter will omit falsey values, so if getLastModifiedJobTime returns undefined, it won't be included. However, you're right that flatten shouldn't be necessary... I think that's a relic of an earlier iteration on this patch. I'll remove it before landing.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1523)*

**Comment by wlach** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ui/js/models/resultsets_store.js, line 942 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1523#-KJNPUcxtTREj78KwhzU:-KJfw21gqSWbCPf-nuQj:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/bc0e4d39b88c6624d22067a678c26a3e8d95c693/ui/js/models/resultsets_store.js#L942)):*
<details><summary><i>Previously, wlach (William Lachance) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1523)*

**Pull request merged**
