### PR TITLE
Bug 1468305 - convert _.chunk() usages to ES6

### PR DESCRIPTION
**Pull request by eliottvincent**

### CODE REVIEW

**Comment by edmorley** [comment]
With the recent changes on `master`, this PR now has conflicts. Could you rebase (preferred over a merge) and force push to the PR to update? :-)

**Comment by camd** [comment]
I wonder if this needs another rebase.  I'm hitting the same error as with the ``_.union`` PR:

    TypeError: "b is not iterable"

Do you see this on the Alerts tab?  This PR doesn't even touch that tab, so that's odd.  Makes me think it's unrelated.

**Comment by camd** [comment]
These errors are unrelated to these changes.  So I'll go ahead and merge.  It's only because this is currently based on a bad existing commit.

**Comment by eliottvincent** [comment]
@camd Ok I understand. I was searching for the error you noticed but couldn't figure to trigger it.

**Pull request merged**
