### PR TITLE
Bug 1419846 - Move tier menu to top

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

**Comment by wlach** [comment]
Exciting screenshot of new placement:

screen shot 2017-11-22 at 1 51 19 pm

**Comment by edmorley** [comment]
Tiers seem like another kind of filter. Should they just be inside the top level "Filters" menu instead?

**Comment by wlach** [comment]
The argument the other way is that tiers are such an important concept that they deserve their own menu, but I don't have a strong opinion. Certainly moving everything to filters would be a more disruptive change for people used to looking for a "tiers" menu (which I think would be many).

**Comment by edmorley** [comment]
Makes sense :-)

**Pull request merged**
