### PR TITLE
Bug 1193804 - Break up treeherder.css - info-panel.css

### PR DESCRIPTION
**Pull request by tojonmz**
This fixes part 6 of Bugzilla bug [1193804](https://bugzilla.mozilla.org/show_bug.cgi?id=1193804).

This splits up the css for the Info panel (aka. pluginpanel.html) into a separate file, `treeherder-info-panel.css`.

I did a bunch of other cleanup, removed unused classes, converted to 2 space indent, and commented and re-ordered the entries so they were easier to find. The appearance of the Info panel and its controls, should be unchanged:

infopanel

Tested on OSX 10.10.5:
Release **43.0a1 (2015-09-18)**
Chrome Latest Release **45.0.2454.93 (64-bit)**

Everything seems fine in local testing.

Adding @camd for review.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/985)

### CODE REVIEW

**Comment by tojonmz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[ui/css/treeherder.css, line 308 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlI34KvkgQV8yBDxiR)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L308)):</sup>
I'm going to purge this comment in `treeherder.css` before landing.

---

<sup>**[ui/css/treeherder.css, line 482 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlF5r2QJA580N1zPN_)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L482)):</sup>
`.navbar-sub` appears to be unused, so removed.

---

<sup>**[ui/css/treeherder.css, line 567 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlD9E6s6o9Sdle_w5x)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L567)):</sup>
`.shadowed-panel` appears unused, so removed.

---

<sup>**[ui/css/treeherder.css, line 569 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlDLSSZDGHXI_hfDIJ)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L569)):</sup>
This was commented out for quite some time, so removed.

---

<sup>**[ui/css/treeherder.css, line 599 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlDypHEDtpA1QUVq46)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L599)):</sup>
`.bottom-menu-group` appeared to be unused, so removed.

---

<sup>**[ui/css/treeherder.css, line 834 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlEHmPJe2sTJP_WQR4)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L834)):</sup>
`.plugin_controls` appeared unused, so removed.

---

<sup>**[ui/css/treeherder.css, line 848 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlJpnkYNz5xsq0CRXI)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L848)):</sup>
These above and below were all tidied up and appear as non-inline in the new file.

---

<sup>**[ui/css/treeherder.css, line 927 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlEU1z2hbMHDCPMokT)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L927)):</sup>
This was kept, but maybe we can remove this `!important` since bug 1094466 is now fixed. But let's do it in a follow up.

---

<sup>**[ui/index.html, line 17 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlFT16p0S3WJq72cuP)** ([raw file](https://github.com/mozilla/treeherder/blob/0c0fe7c1fca7ab2946f864277cbba14bd51ff9a2/ui/index.html#L17)):</sup>
At least in a local web-server/vagrant, to get the correct css inheritance for the Similar Jobs tab 'job' buttons (left column), the new **info-panel** needs to precede **job-buttons** as I've done here. Otherwise `.btn-similar-jobs` overrides the background property on `.btn-(color)` and we end up with blank buttons in the Similar Jobs spreadsheet.

I'm not sure if this is specific to local testing, or not. But I think we are ok and it would be pretty obvious in testing if it was re-ordered later.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/985)

**Comment by camd** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/985)

**Comment by tojonmz** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[ui/css/treeherder.css, line 308 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlI34KvkgQV8yBDxiR)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L308)):</sup>
Done.

---

<sup>**[ui/css/treeherder.css, line 482 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlF5r2QJA580N1zPN_)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L482)):</sup>
Done.

---

<sup>**[ui/css/treeherder.css, line 567 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlD9E6s6o9Sdle_w5x)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L567)):</sup>
Done.

---

<sup>**[ui/css/treeherder.css, line 569 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlDLSSZDGHXI_hfDIJ)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L569)):</sup>
Done.

---

<sup>**[ui/css/treeherder.css, line 599 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlDypHEDtpA1QUVq46)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L599)):</sup>
Done.

---

<sup>**[ui/css/treeherder.css, line 834 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlEHmPJe2sTJP_WQR4)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L834)):</sup>
Done.

---

<sup>**[ui/css/treeherder.css, line 848 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlJpnkYNz5xsq0CRXI)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L848)):</sup>
Done.

---

<sup>**[ui/css/treeherder.css, line 927 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlEU1z2hbMHDCPMokT)** ([raw file](https://github.com/mozilla/treeherder/blob/afe16b0c000296877595706fc000a074f8d9e8e5/ui/css/treeherder.css#L927)):</sup>
Done in the context of this PR.

---

<sup>**[ui/index.html, line 17 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/985#-JzlFT16p0S3WJq72cuP)** ([raw file](https://github.com/mozilla/treeherder/blob/0c0fe7c1fca7ab2946f864277cbba14bd51ff9a2/ui/index.html#L17)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/985)

**Comment by tojonmz** [comment]
Everything is resolved above on reviewable, rebasing now, will merge shortly.

**Pull request merged**
