### PR TITLE
Bug 1697108- Move TIME_TO_MATURE constant from secretery_tool.py to s…

### PR DESCRIPTION
**Pull request by Kaushal-Dhungel**
…ettings.py

This pull request fixes 1697108.

### CODE REVIEW

**Comment by airimovici** [comment]
It seems like an unrelated javascript test is failing. We would need to force rerun the checks

**Comment by Kaushal-Dhungel** [comment]
@airimovici I have no idea why this test is failing. Should I do something??

**Comment by ionutgoldan** [comment]
> @airimovici I have no idea why this test is failing. Should I do something??

Since migrating our CI from Travis to Circle CI, the tests experience intermittent failures for no real reason. I've re run the failed ones. Hopefully, they'll pass this time.

**Comment by Kaushal-Dhungel** [comment]
@ionutgoldan thank you.

**Review by ionutgoldan — APPROVED** [review]

**Comment by ionutgoldan** [comment]
@Kaushal-Dhungel thank you for your PR & time! 🎉

**Pull request merged**
