### PR TITLE
Bug 1164491 - Make resultset and jobs api queryable in th-client.

### PR DESCRIPTION
**Pull request by vaibhavmagarwal**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/591)

### CODE REVIEW

**Comment by tojonmz** [comment]
@vaibhavmagarwal this looks like a duplicate PR to https://github.com/mozilla/treeherder/pull/543, or am I missing something?

**Comment by vaibhavmagarwal** [comment]
@tojonmz, yes it is a duplicate.... I made some mistake in pushing to github repo, and somehow https://github.com/mozilla/treeherder/pull/543 got closed and I am unable to open it....

**Comment by vaibhavmagarwal** [comment]
Closing this in order to repoen https://github.com/mozilla/treeherder/pull/543

**Comment by vaibhavmagarwal** [comment]
This was a duplicate because I accidentally closed PR #543, I have now figured out a way to reopen that, so closing this. Please ignore this.

**Pull request closed without merging**
