### PR TITLE
Bug 1551959 - Add updated platform names for OS X 10.10 and 10.14

### PR DESCRIPTION
**Pull request by camd**

### CODE REVIEW

**Comment by camd** [comment]
@jmaher : I did my best to extrapolate what I thought they should be.  How does this look?  :)

**Comment by rvandermeulen** [comment]
Is this going to cause issues for ESR60, assuming it's still using the macosx64 naming convention until EOL?

**Comment by jmaher** [comment]
I think to :ryanVM's point, we should keep the old stuff and add the new, I think the values used for 1010 and 1014 are spot on.

**Comment by camd** [comment]
Ahh, great point.  Thanks for catching that, @rvandermeulen.  :)  OK, here is just the additive items.

**Pull request merged**
