### PR TITLE
Bug 1266062 - Move bug job map and job notes to ORM from datasource

### PR DESCRIPTION
**Pull request by wlach**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1568)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[treeherder/model/models.py, line 628 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KJfsv9UfXOMTJiWoGj9:-KJfsv9UfXOMTJiWoGjA:-620848257) ([raw file](https://github.com/mozilla/treeherder/blob/d1cd3121fe3960554948931975a162532f06b243/treeherder/model/models.py#L628)):*
> ```Python
>     job = FlexibleForeignKey(Job)
>     bug_id = models.PositiveIntegerField(db_index=True)
>     submit_timestamp = models.DateTimeField(auto_now_add=True)
> ```

It is somewhat backwards incompatible, but elsewhere we have called this `created`.j

---

*[treeherder/model/models.py, line 669 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KJftsMsQ55LzX9PPxrD:-KJftsMsQ55LzX9PPxrE:1183047372) ([raw file](https://github.com/mozilla/treeherder/blob/d1cd3121fe3960554948931975a162532f06b243/treeherder/model/models.py#L669)):*
> ```Python
>             # if we have a user, then update the autoclassification relations
>             if self.user:
>                 jm.update_autoclassification_bug(self.job.project_specific_id,
> ```

This seems to be the only reason that the jobs model is used here? It wouldn't be *so* hard to make the autoclassification stuff a method on `Job`, which would need the artifact model (until we get rid of the bug_suggestions artifacts), but not actually the job model.

I'm also OK with doing that later though.

---

*[treeherder/model/models.py, line 691 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KJfv-8KcUK3z7iidhBR:-KJfv-8KcUK3z7iidhBS:-1414288537) ([raw file](https://github.com/mozilla/treeherder/blob/d1cd3121fe3960554948931975a162532f06b243/treeherder/model/models.py#L691)):*
> ```Python
>     user = models.ForeignKey(User, null=True)  # null if autoclassified
>     text = models.TextField()
>     timestamp = models.DateTimeField(auto_now_add=True)
> ```

Again, renaming this `created` would give the illusion of consistency._g

---

*[treeherder/webapp/api/note.py, line 14 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KJfwydrsOjW2eOpVnm_:-KJfwydsHYGKVUV8ugHO:118917114) ([raw file](https://github.com/mozilla/treeherder/blob/d1cd3121fe3960554948931975a162532f06b243/treeherder/webapp/api/note.py#L14)):*
> ```Python
> 
>     @staticmethod
>     def _get_note_as_dict(note):
> ```

I wonder if these `_as_dict` methods should go in the model?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Comment by wlach** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[treeherder/model/models.py, line 628 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KJfsv9UfXOMTJiWoGj9:-KKO5Nq6np-t6GX5fCqQ:1566578205) ([raw file](https://github.com/mozilla/treeherder/blob/d1cd3121fe3960554948931975a162532f06b243/treeherder/model/models.py#L628)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> It is somewhat backwards incompatible, but elsewhere we have called this `created`.j
</details>
Changed. API's still return old values just to be safe.

---

*[treeherder/model/models.py, line 669 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KJftsMsQ55LzX9PPxrD:-KKO5GgFWZEkaTxQIH52:1732039790) ([raw file](https://github.com/mozilla/treeherder/blob/d1cd3121fe3960554948931975a162532f06b243/treeherder/model/models.py#L669)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> This seems to be the only reason that the jobs model is used here? It wouldn't be *so* hard to make the autoclassification stuff a method on `Job`, which would need the artifact model (until we get rid of the bug_suggestions artifacts), but not actually the job model.
> 
> I'm also OK with doing that later though.
</details>
Yeah, I'd prefer to leave that for later.

---

*[treeherder/model/models.py, line 691 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KJfv-8KcUK3z7iidhBR:-KKO5JDA0oQEg6pf09v2:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/d1cd3121fe3960554948931975a162532f06b243/treeherder/model/models.py#L691)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Again, renaming this `created` would give the illusion of consistency._g
</details>
Done.

---

*[treeherder/webapp/api/note.py, line 14 \[r2\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KJfwydrsOjW2eOpVnm_:-KKO5TLEeLyILQXLAB4Z:650081700) ([raw file](https://github.com/mozilla/treeherder/blob/d1cd3121fe3960554948931975a162532f06b243/treeherder/webapp/api/note.py#L14)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I wonder if these `_as_dict` methods should go in the model?
</details>
I don't think so, as they really only pertain to the API. Django has a utility method to do a straight up conversion of a model to a dictionary (which we unfortunately can't use here if we want to preserve API backwards compat).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Comment by jgraham** [comment]
Reviewed 3 of 16 files at r1, 2 of 19 files at r3, 2 of 14 files at r4, 4 of 11 files at r5.
Review status: 6 of 16 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[treeherder/model/models.py, line 629 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtTTOFi8n8jfP6cOoI:-KKtTTOGkPb1tg5UofdG:-316278996) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/models.py#L629)):*
> ```Python
>     job = FlexibleForeignKey(Job)
>     bug_id = models.PositiveIntegerField(db_index=True)
>     created = models.DateTimeField(default=timezone.now)
> ```

Is there a reason not to use `auto_now_add=True` to set the default?

---

*[treeherder/model/models.py, line 662 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtxh36NXBTUQWp94ib:-KKtxh378rnZizAA-i_f:1483841755) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/models.py#L662)):*
> ```Python
>                             self.job.project_specific_id,
>                             self.bug_id,
>                             self.submit_timestamp,
> ```

s/`submit_timestamp`/`created`

---

*[treeherder/model/models.py, line 692 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtUeU0THpeWdvWn4Wq:-KKtUeU143msKnU-YFUG:-936839550) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/models.py#L692)):*
> ```Python
>     user = models.ForeignKey(User, null=True)  # null if autoclassified
>     text = models.TextField()
>     created = models.DateTimeField(default=timezone.now)
> ```

Again could use `auto_now_add` unless I misunderstood a requirement.

---

*[treeherder/model/derived/jobs.py, line 390 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtncLoS9XGGIH0mwyw:-KKtncLpHBowMHERpmZx:1082068055) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L390)):*
> ```Python
>         default value
>         """
>         notes = JobNote.objects.filter(
> ```

Use `.first()` here to ensure we don't do two queries.

---

*[treeherder/model/derived/jobs.py, line 445 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKttwh5kSJ1Ey7Ak9xn:-KKttwh5kSJ1Ey7Ak9xo:1777285607) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L445)):*
> ```Python
>             # one and after a verification if there is already one not supplied by the
>             # autoclassifier
>             if not JobNote.objects.filter(job__repository__name=self.project,
> ```

I might be tempted to put this query in a method to reuse here and below.

---

*[treeherder/model/derived/jobs.py, line 461 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtuA6tx5ZoKzNlGzEg:-KKtuA6tx5ZoKzNlGzEh:-900946654) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L461)):*
> ```Python
>             # one and after a verification if there is already one not supplied by the
>             # autoclassifier
>             if not (any(note.failure_classification != autoclassification
> ```

I am not convinced this makes the code more readable. Maybe structure the method as a set of conditions each of which return early if they are not met? Or not if you think that's not clearer then don't :)

---

*[treeherder/model/derived/jobs.py, line 521 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtv0xu4vrkB2jJvP1H:-KKtv0xu4vrkB2jJvP1I:1123787322) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L521)):*
> ```Python
>             return
> 
>         if user is None:
> ```

`verified = user is not None`

---

*[treeherder/model/derived/jobs.py, line 545 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtxsYKXQsXdA5yZoCk:-KKtxsYLdUwt98YD1hfr:-2089681139) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L545)):*
> ```Python
>         for bug_number in bug_numbers:
>             BugJobMap.objects.create(job=job, bug_id=bug_number,
>                                      submit_timestamp=datetime.datetime.now(),
> ```

Let this use the default value (or at least use the right column name).

---

*[treeherder/webapp/api/bug.py, line 23 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKuF4Rm9Lx4bM_HW9qc:-KKuF4RnU8e9tWsEZAfC:-1203692320) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/bug.py#L23)):*
> ```Python
>         job = Job.objects.get(repository__name=project,
>                               project_specific_id=job_id)
>         created, _ = BugJobMap.objects.get_or_create(
> ```

Should be `_, created`

---

*[treeherder/webapp/api/bug.py, line 47 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKuFAyDXuz-C_rMFIoe:-KKuFAyDXuz-C_rMFIof:-2122299454) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/bug.py#L47)):*
> ```Python
> 
>     @staticmethod
>     def _get_bug_job_map_as_dict(bug_job_map):
> ```

Write as a serializer, perhaps.

---

*[treeherder/webapp/api/note.py, line 14 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKu0laYQSIhXMnJHBFe:-KKu0laZp0pFRwwvKTZr:-687775216) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/note.py#L14)):*
> ```Python
> 
>     @staticmethod
>     def _get_note_as_dict(note):
> ```

Isn't the right way to do this to add a `Serializer` for `JobNote` instances?

---

*[treeherder/webapp/api/note.py, line 18 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKu0Dz4_-oHWErt8SMv:-KKu0Dz568qsXRSLk3Ba:1399733542) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/note.py#L18)):*
> ```Python
>             'id': note.id,
>             'job_id': note.job.project_specific_id,
>             'failure_classification_id': note.failure_classification.id,
> ```

I don't know if django is smart enough to make this work without loading the `FailureClassification` object. You could just use `failure_classification_id`.

---

*[treeherder/webapp/api/note.py, line 51 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKu2a7r1k_YnHIP3fD4:-KKu2a7r1k_YnHIP3fD5:-1519347429) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/note.py#L51)):*
> ```Python
>             raise ParseError(detail="The job_id parameter must be an integer")
> 
>         job = Job.objects.get(repository__name=project,
> ```

Maybe this deserves a class method on `Job`?

---

*[treeherder/webapp/api/note.py, line 80 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKu3RLfUa1LtZSaf-ri:-KKu3RLgayicI15BDoJg:1726220805) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/note.py#L80)):*
> ```Python
>         Delete a note entry
>         """
>         note = JobNote.objects.get(id=pk)
> ```

`get` is return or raise. You could use `first` I suppose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Comment by jgraham** [comment]
Reviewed 5 of 16 files at r1, 2 of 19 files at r3, 1 of 14 files at r4, 6 of 11 files at r5.
Review status: 14 of 16 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[tests/webapp/api/test_bug_job_map_api.py, line 80 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKxA56eGFhJaB47qdeI:-KKxA56geR2PeHt_GvlV:-232298667) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/tests/webapp/api/test_bug_job_map_api.py#L80)):*
> ```Python
>     # verify that API works with different combinations of job_id= parameters
>     for job_range in [(0, 1), (0, 2), (0, 9)]:
>         param = "?" + "&".join(["job_id={}".format(job.project_specific_id)
> ```

You can pass params in to `webapp.get` as a dict.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Comment by wlach** [comment]
Review status: 14 of 16 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[treeherder/model/models.py, line 629 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtTTOFi8n8jfP6cOoI:-KKwRToyXb7gRKcL_aer:-1814465868) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/models.py#L629)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Is there a reason not to use `auto_now_add=True` to set the default?
</details>
Yes, because auto_now_add can't be overridden, which we need for (at very least) migrating old data. 

---

*[treeherder/model/models.py, line 692 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtUeU0THpeWdvWn4Wq:-KKweTKVPYq9bQ0VyV83:-1582418045) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/models.py#L692)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Again could use `auto_now_add` unless I misunderstood a requirement.
</details>
See above.

---

*[treeherder/model/derived/jobs.py, line 390 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtncLoS9XGGIH0mwyw:-KKwgWjPcnIlxZiuP61Z:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L390)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Use `.first()` here to ensure we don't do two queries.
</details>
Done.

---

*[treeherder/model/derived/jobs.py, line 445 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKttwh5kSJ1Ey7Ak9xn:-KKwh-EQcisP0R8upq7l:-407911895) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L445)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I might be tempted to put this query in a method to reuse here and below.
</details>
I am not sure... the query is relatively simple. Also it will be much shorter once we can reference job objects directly, instead of needing both project specific id + repository.

---

*[treeherder/model/derived/jobs.py, line 461 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtuA6tx5ZoKzNlGzEg:-KKwhej48zc9oaDn_1dD:921682579) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L461)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I am not convinced this makes the code more readable. Maybe structure the method as a set of conditions each of which return early if they are not met? Or not if you think that's not clearer then don't :)
</details>
Sounds good. Changed!

---

*[treeherder/model/derived/jobs.py, line 521 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtv0xu4vrkB2jJvP1H:-KKwi-0sLDY5bD4mi1hH:65119458) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L521)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> `verified = user is not None`
</details>
Actually now that I look at it, I think we can just take this variable out altogether and just see whether user is defined below.

---

*[treeherder/webapp/api/bug.py, line 23 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKuF4Rm9Lx4bM_HW9qc:-KKx-4_7KG4v0x8UVFEV:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/bug.py#L23)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Should be `_, created`
</details>
Done.

---

*[treeherder/webapp/api/bug.py, line 47 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKuFAyDXuz-C_rMFIoe:-KKxIIeeCNvgZ1OFnHhm:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/bug.py#L47)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Write as a serializer, perhaps.
</details>
Done.

---

*[treeherder/webapp/api/note.py, line 14 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKu0laYQSIhXMnJHBFe:-KKx-6J7Vwkej09lq6ma:1508483905) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/note.py#L14)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Isn't the right way to do this to add a `Serializer` for `JobNote` instances?
</details>
Yes, though it was a little tricky. :) Done.

---

*[treeherder/webapp/api/note.py, line 18 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKu0Dz4_-oHWErt8SMv:-KKxIDySX6u1MqHkc-ji:857966333) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/note.py#L18)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I don't know if django is smart enough to make this work without loading the `FailureClassification` object. You could just use `failure_classification_id`.
</details>
Not relevant now that we're using a serializer ^^^

---

*[treeherder/webapp/api/note.py, line 51 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKu2a7r1k_YnHIP3fD4:-KKx-E9GRNIhqJPTY7q7:85300297) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/note.py#L51)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Maybe this deserves a class method on `Job`?
</details>
Let's just finish migrating jobs out of datasource, then this will be easy.

---

*[treeherder/webapp/api/note.py, line 80 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKu3RLfUa1LtZSaf-ri:-KKx-LjEtBf2InHh6TgJ:-426435104) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/webapp/api/note.py#L80)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> `get` is return or raise. You could use `first` I suppose.
</details>
Yeah, I rewrote this to do try/except.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Comment by wlach** [comment]
Review status: 1 of 22 files reviewed at latest revision, 15 unresolved discussions.

---

*[tests/webapp/api/test_bug_job_map_api.py, line 80 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKxA56eGFhJaB47qdeI:-KKxIdYzIczYUvJ_3qFC:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/tests/webapp/api/test_bug_job_map_api.py#L80)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> You can pass params in to `webapp.get` as a dict.
</details>
Done.

---

*[treeherder/model/models.py, line 662 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtxh36NXBTUQWp94ib:-KKxIjebz6XoRlRfGqRV:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/models.py#L662)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> s/`submit_timestamp`/`created`
</details>
Done.

---

*[treeherder/model/derived/jobs.py, line 545 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKtxsYKXQsXdA5yZoCk:-KKxIgaW6vTUMHbUBM94:-1032357627) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L545)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Let this use the default value (or at least use the right column name).
</details>
Not relevant after some refactoring.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Comment by wlach** [comment]
Ok, I updated this to use serializers instead of custom functions. I also made the following modifications to the API's:

Bug Job Map API:

* submit_timestamp -> created (using standard javascript date instead of unix timestmap)
* type: removed (was never used, autoclassify information was per-job)

Note API:

* note_timestamp -> created (using standard javascript date instead of unix timestamp)
* note -> text
* active_status: removed (was never used)

I will announce these changes on the newsgroup before landing on production, though I believe we're the only consumers.

---

Review status: 1 of 22 files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-:-KKxImKz11VYu2EZTnTa:-1956035566)*

**Comment by jgraham** [comment]
Reviewed 1 of 19 files at r3, 3 of 15 files at r7, 17 of 17 files at r8.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[treeherder/model/models.py, line 704 \[r8\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KL3IlUcvD65BLueZuDp:-KL3IlUdE38eZj6eoGV5:-1245545804) ([raw file](https://github.com/mozilla/treeherder/blob/069431b1d4331b5852153d5232be552723a83b14/treeherder/model/models.py#L704)):*
> ```Python
>                             self.job.project_specific_id,
>                             self.bug_id,
>                             self.submit_timestamp,
> ```

s/`submit_timestamp`/`created`/

---

*[treeherder/model/derived/jobs.py, line 445 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKttwh5kSJ1Ey7Ak9xn:-KL3J032fAhvyrRCndhz:984457806) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L445)):*
<details><summary><i>Previously, wlach (William Lachance) wrote…</i></summary>
> I am not sure... the query is relatively simple. Also it will be much shorter once we can reference job objects directly, instead of needing both project specific id + repository.
</details>
Yes, well, in the meantime I think `JobNote.for_project_job(project, job)` would be clearer than repeating this in a number of places, but I'm not going to insist.

---

*[treeherder/model/derived/jobs.py, line 544 \[r8\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KL3JePKSANYQS23qgIS:-KL3JePKSANYQS23qgIT:113735145) ([raw file](https://github.com/mozilla/treeherder/blob/069431b1d4331b5852153d5232be552723a83b14/treeherder/model/derived/jobs.py#L544)):*
> ```Python
>                                      user=user)
> 
>         if not user:
> ```

I think the old code was somewhat clearer about the actual meaning than simply `user is None` which is sort of an implementation detail.

---

*[treeherder/model/management/commands/migrate_bugjobmap_jobnote.py, line 26 \[r8\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KL3Ruk1z98OTwsTZWgZ:-KL3Ruk2DE_3LDcZG7BH:351358817) ([raw file](https://github.com/mozilla/treeherder/blob/069431b1d4331b5852153d5232be552723a83b14/treeherder/model/management/commands/migrate_bugjobmap_jobnote.py#L26)):*
> ```Python
>             repository=repository).values_list('id',
>                                                'project_specific_id')
>         job_id_mapping = dict((project_specific_id, job_id) for
> ```

You totally don't have to change this, but dict literals are arguably more idiomatic i.e.

     {project_specific_id: job_id for job_id, project_specific_id in job_id_pairs}

---

*[treeherder/webapp/api/serializers.py, line 190 \[r8\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KL3PGzIapVJJAO3z_B-:-KL3PGzJKSYtHuMNPzK-:-446007546) ([raw file](https://github.com/mozilla/treeherder/blob/069431b1d4331b5852153d5232be552723a83b14/treeherder/webapp/api/serializers.py#L190)):*
> ```Python
>     job_id = serializers.SlugRelatedField(
>         slug_field="project_specific_id", source="job",
>         queryset=models.Job.objects.all())
> ```

Are these `queryset` things actually needed? It seems like it could be replaced with `read_only=True` unless we also use this for input.

Unrelated: can we have one param per line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Comment by wlach** [comment]
Review status: 1 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[treeherder/model/models.py, line 704 \[r8\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KL3IlUcvD65BLueZuDp:-KLGYkeNoWlI_wChtOW5:-499146009) ([raw file](https://github.com/mozilla/treeherder/blob/069431b1d4331b5852153d5232be552723a83b14/treeherder/model/models.py#L704)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> s/`submit_timestamp`/`created`/
</details>
Done.

---

*[treeherder/model/derived/jobs.py, line 445 \[r5\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KKttwh5kSJ1Ey7Ak9xn:-KLGYsUKQLWB6Io6WIvV:410767741) ([raw file](https://github.com/mozilla/treeherder/blob/3e2a10def9565452613a8ddb6e8d540d279ec25e/treeherder/model/derived/jobs.py#L445)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Yes, well, in the meantime I think `JobNote.for_project_job(project, job)` would be clearer than repeating this in a number of places, but I'm not going to insist.
</details>
It really won't be long until everything is in the ORM, I promise. :)

---

*[treeherder/model/derived/jobs.py, line 544 \[r8\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KL3JePKSANYQS23qgIS:-KLGYBXUkRpFJThbzXBn:-944622165) ([raw file](https://github.com/mozilla/treeherder/blob/069431b1d4331b5852153d5232be552723a83b14/treeherder/model/derived/jobs.py#L544)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I think the old code was somewhat clearer about the actual meaning than simply `user is None` which is sort of an implementation detail.
</details>
I do agree that it was clearer, though it was also more convoluted.  I'll add a one-line comment explaining it and change to `user is None`.

---

*[treeherder/model/management/commands/migrate_bugjobmap_jobnote.py, line 26 \[r8\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KL3Ruk1z98OTwsTZWgZ:-KLGZzJauCSpTgn4BiMl:-1592846077) ([raw file](https://github.com/mozilla/treeherder/blob/069431b1d4331b5852153d5232be552723a83b14/treeherder/model/management/commands/migrate_bugjobmap_jobnote.py#L26)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> You totally don't have to change this, but dict literals are arguably more idiomatic i.e.
> 
>      {project_specific_id: job_id for job_id, project_specific_id in job_id_pairs}
</details>
Yeah, that does look better. Changed.

---

*[treeherder/webapp/api/serializers.py, line 190 \[r8\]](https://reviewable.io:443/reviews/mozilla/treeherder/1568#-KL3PGzIapVJJAO3z_B-:-KLGeHNdJ5eCg4WgUt9m:144580180) ([raw file](https://github.com/mozilla/treeherder/blob/069431b1d4331b5852153d5232be552723a83b14/treeherder/webapp/api/serializers.py#L190)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Are these `queryset` things actually needed? It seems like it could be replaced with `read_only=True` unless we also use this for input.
> 
> Unrelated: can we have one param per line?
</details>
You are right, we do not need those. Removed (and changed to param-per-line).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Comment by jgraham** [comment]
Reviewed 1 of 21 files at r9, 3 of 15 files at r10, 17 of 17 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/treeherder/1568)*

**Pull request merged**
