### PR TITLE
Bug 1140349 - Remove the objectstore

### PR DESCRIPTION
**Pull request by camd**
**Phase 2 of Objectstore removal**

This branch removes all objectstore code with one exception (see below).  After this branch has been merged, we should then delete all the Objectstore databases and objectstore records from the ``datasource`` table.  That work is handled in [Bug 1178227](https://bugzilla.mozilla.org/show_bug.cgi?id=1178227)

Exception:  We retained the POST to ``/objectstore/`` for backward compatibility.  But it executes the same job ingestion code as POSTing to the ``/jobs/`` endpoint.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/660)

### CODE REVIEW

**Comment by maurodoglio** [comment]
If  I understand correctly the objects get stuck in a loading state because this line was deleted https://github.com/mozilla/treeherder/pull/660/files#diff-a03f6e7c1747a7ef236e211422cc7c5eL1379.

**Comment by camd** [comment]
@maurodoglio - So, this is kind of confusing.  This is part 2 of the feature commits.  

The first commit will still ingest from the objectstore, and it still has that line.  But still the OS records get orphaned as "loading".  That is in the ``drain-objectstore`` branch and in this PR: https://github.com/mozilla/treeherder/pull/689

This PR/branch is part 2.  It removes all the code pertaining to the objectstore, including the line you mentioned.  But when we push this change, all the data in the OS will already have been ingested, so that's ok.

**Comment by edmorley** [comment]
We can also delete `contenttype` from here:
https://github.com/mozilla/treeherder/blob/2d087edaeab07b1fe680d211413a37090792f309/tests/model/sql/test_models.py#L22

---

Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 26 unresolved discussions, all commit checks successful.

---

<sup>**[tests/conftest.py, line 163 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDi0ZazP13Q5S9vNxa)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/tests/conftest.py#L163)):</sup>
The `contenttype` argument can also be removed here.

---

<sup>**[tests/model/derived/test_jobs_model.py, line 56 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDiQX6LHT9E4L1X9m5)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/tests/model/derived/test_jobs_model.py#L56)):</sup>
We can also remove the function `test_bad_contenttype()`

---

<sup>**[tests/test_utils.py, line 156 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDnZwyv4fQlZQmPBp4)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/tests/test_utils.py#L156)):</sup>
This function is now unused :-)

---

<sup>**[treeherder/client/thclient/client.py, line 501 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDmDdTS1ehBaqY32p9)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/client/thclient/client.py#L501)):</sup>
We can remove `endpoint_base` (and handle in the individual functions).

---

<sup>**[treeherder/client/thclient/client.py, line 563 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDm3telhw9QdgaQiZR)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/client/thclient/client.py#L563)):</sup>
Let's remove the `'jobs'` argument here too

---

<sup>**[treeherder/etl/common.py, line 136 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDoFixoqrNsYxb9k4w)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/etl/common.py#L136)):</sup>
s/or it/or else/  ?

And a comma before "and finally"?

---

<sup>**[treeherder/etl/common.py, line 137 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDoNV_KIqX3T-EMGcF)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/etl/common.py#L137)):</sup>
s/there was/there were/

---

<sup>**[treeherder/model/derived/base.py, line 54 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDjtBlFtagUwyu8iIH)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L54)):</sup>
I think we can remove this conditional entirely: both objectstore and jobs records will have the same oauth credentials, so it doesn't matter which we use - and shortly we'll be deleting the objectstore entries anyway, at which point the conditional will be even more redundant.

---

<sup>**[treeherder/model/derived/base.py, line 65 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkBCMFlOe5jkqISug)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L65)):</sup>
We can remove the `contenttype` parameter here too :-)

---

<sup>**[treeherder/model/derived/base.py, line 79 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkHk2R90Hq8laVbO_)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L79)):</sup>
And here :-)

---

<sup>**[treeherder/model/derived/base.py, line 150 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkPL1Ijl_c7LRYX44)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L150)):</sup>
And here :-)

---

<sup>**[treeherder/model/derived/base.py, line 165 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkSewwgGCDLiHPM5M)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L165)):</sup>
And here :-)

---

<sup>**[treeherder/model/derived/jobs.py, line 166 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDn6c-N3TSKaURlwsP)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L166)):</sup>
This is unused

---

<sup>**[treeherder/model/derived/jobs.py, line 985 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDpmT9qXHhSKhn_Z1u)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L985)):</sup>
Let's use `self.CT_JOBS` further down the call chain and remove the argument here.

---

<sup>**[treeherder/model/derived/jobs.py, line 989 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDrdRo4xygsdazQr8T)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L989)):</sup>
This isn't an issue with your PR; but amusingly I've just spotted we never set `raise_errors` to True anywhere (including in the tests, so presumably they would never trigger an exception...). Could you file a bug for this? :-)

---

<sup>**[treeherder/model/derived/jobs.py, line 998 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDsNs8BwA-X_R5vPoZ)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L998)):</sup>
This example structure is for the objectstore format; would be good to update it to match the normal non-objectstore format now :-)

---

<sup>**[treeherder/model/derived/jobs.py, line 1081 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDtBxae9gRENW44BZ1)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1081)):</sup>
This will be unused with the edits below

---

<sup>**[treeherder/model/derived/jobs.py, line 1107 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDsBXsrvJQHx_4rQXi)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1107)):</sup>
This can also be removed. `json_blob` was only ever in the data structure from the objectstore iirc.

---

<sup>**[treeherder/model/derived/jobs.py, line 1148 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDszH838UEnxbcbgX-)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1148)):</sup>
This can be removed too; iirc only the objectstore datum has a key called `id`

---

<sup>**[treeherder/model/derived/jobs.py, line 1286 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDsfn67WdpNBNumkYi)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1286)):</sup>
`json_blob` is objectstore only

Removing this and the one above also makes `JobData.from_json` unused.

In addition, I've noticed we have two seemingly identical JobData classes?!
https://github.com/mozilla/treeherder/search?utf8=%E2%9C%93&q=class+JobData%28dict%29&type=Code
Would you mind filing a bug for that? :-)

---

<sup>**[treeherder/model/derived/jobs.py, line 2021 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkqt_zR5rfGAnoJ_q)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L2021)):</sup>
`contenttype` can be remove here too (and the value shoved lower down the call chain)

---

<sup>**[treeherder/model/derived/jobs.py, line 2023 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDudBepJ12aIRdjceI)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L2023)):</sup>
I guess we could just hardcode the `contenttype = "jobs"` in the stored SQL and remove entirely from here?

---

<sup>**[treeherder/model/management/commands/cycle_data.py, line 71 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDpY9DXPj6Da6XT_HV)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/management/commands/cycle_data.py#L71)):</sup>
Lets put this on one line :-)

---

<sup>**[treeherder/model/management/commands/init_datasources.py, line 38 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDl82AiFaj4BBaFMKZ)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/management/commands/init_datasources.py#L38)):</sup>
And here :-)

---

<sup>**[treeherder/model/models.py, line 204 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDjfR96FcHiVB07Tp3)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/models.py#L204)):</sup>
And the `contenttype` here

---

<sup>**[treeherder/model/models.py, line 218 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDjgbQeuUumsMZB5WE)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/models.py#L218)):</sup>
And here

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/660)

**Comment by camd** [comment]
oh cool, yeah.  On line 13 as well.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/660)

**Comment by camd** [comment]
Review status: 37 of 44 files reviewed at latest revision, 26 unresolved discussions, all commit checks successful.

---

<sup>**[tests/conftest.py, line 163 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDi0ZazP13Q5S9vNxa)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/tests/conftest.py#L163)):</sup>
Done.

---

<sup>**[tests/model/derived/test_jobs_model.py, line 56 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDiQX6LHT9E4L1X9m5)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/tests/model/derived/test_jobs_model.py#L56)):</sup>
Done.

---

<sup>**[tests/test_utils.py, line 156 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDnZwyv4fQlZQmPBp4)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/tests/test_utils.py#L156)):</sup>
Done.

---

<sup>**[treeherder/client/thclient/client.py, line 501 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDmDdTS1ehBaqY32p9)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/client/thclient/client.py#L501)):</sup>
I'd rather keep ``endpoint_base`` in this class for now.  Perhaps we could investigate removing it later?  This is used in the mechanism for the chunking and it might require some more in-depth changes than just dead code removal.  Is that cool by you?

---

<sup>**[treeherder/client/thclient/client.py, line 563 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDm3telhw9QdgaQiZR)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/client/thclient/client.py#L563)):</sup>
suggest deferring this removal till later, too.

---

<sup>**[treeherder/etl/common.py, line 136 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDoFixoqrNsYxb9k4w)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/etl/common.py#L136)):</sup>
Done.

---

<sup>**[treeherder/etl/common.py, line 137 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDoNV_KIqX3T-EMGcF)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/etl/common.py#L137)):</sup>
Done.

---

<sup>**[treeherder/model/derived/base.py, line 54 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDjtBlFtagUwyu8iIH)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L54)):</sup>
good call.  :)

---

<sup>**[treeherder/model/derived/base.py, line 65 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkBCMFlOe5jkqISug)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L65)):</sup>
Done.

---

<sup>**[treeherder/model/derived/base.py, line 79 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkHk2R90Hq8laVbO_)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L79)):</sup>
Done.

---

<sup>**[treeherder/model/derived/base.py, line 150 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkPL1Ijl_c7LRYX44)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L150)):</sup>
Done.

---

<sup>**[treeherder/model/derived/base.py, line 165 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkSewwgGCDLiHPM5M)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/base.py#L165)):</sup>
Done.

---

<sup>**[treeherder/model/derived/jobs.py, line 166 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDn6c-N3TSKaURlwsP)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L166)):</sup>
Done.

---

<sup>**[treeherder/model/derived/jobs.py, line 985 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDpmT9qXHhSKhn_Z1u)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L985)):</sup>
Done.

---

<sup>**[treeherder/model/derived/jobs.py, line 989 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDrdRo4xygsdazQr8T)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L989)):</sup>
good call.  Created: https://bugzilla.mozilla.org/show_bug.cgi?id=1184795

---

<sup>**[treeherder/model/derived/jobs.py, line 2021 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDkqt_zR5rfGAnoJ_q)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L2021)):</sup>
Done.

---

<sup>**[treeherder/model/derived/jobs.py, line 2023 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDudBepJ12aIRdjceI)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L2023)):</sup>
I hard coded this to ``jobs`` in the ``derived/base.py`` file.  

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/660)

**Comment by camd** [comment]
Reviewed 1 of 7 files at r2.
Review status: 38 of 44 files reviewed at latest revision, 26 unresolved discussions, all commit checks successful.

---

<sup>**[tests/conftest.py, line 163 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDi0ZazP13Q5S9vNxa)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/tests/conftest.py#L163)):</sup>
Actually, ends up this is a ``not null`` field in the DB.  I created bug https://bugzilla.mozilla.org/show_bug.cgi?id=1185030 to handle removing this field from the DB/model at a later time.  For now I need to just give it the default value of "jobs".  

---

<sup>**[treeherder/model/derived/jobs.py, line 1081 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDtBxae9gRENW44BZ1)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1081)):</sup>
Done.

---

<sup>**[treeherder/model/derived/jobs.py, line 1125 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDsBXsrvJQHx_4rQXi)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1125)):</sup>
Done.

---

<sup>**[treeherder/model/derived/jobs.py, line 1148 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDszH838UEnxbcbgX-)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1148)):</sup>
Done.

---

<sup>**[treeherder/model/derived/jobs.py, line 1304 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDsfn67WdpNBNumkYi)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1304)):</sup>
You bet:
https://bugzilla.mozilla.org/show_bug.cgi?id=1185039

---

<sup>**[treeherder/model/management/commands/cycle_data.py, line 71 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDpY9DXPj6Da6XT_HV)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/management/commands/cycle_data.py#L71)):</sup>
Done.

---

<sup>**[treeherder/model/management/commands/init_datasources.py, line 38 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDl82AiFaj4BBaFMKZ)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/management/commands/init_datasources.py#L38)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/660)

**Comment by camd** [comment]
Review status: 38 of 44 files reviewed at latest revision, 26 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/model/derived/jobs.py, line 1016 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDsNs8BwA-X_R5vPoZ)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L1016)):</sup>
Done.

---

<sup>**[treeherder/model/models.py, line 204 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDjfR96FcHiVB07Tp3)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/models.py#L204)):</sup>
I'd rather wait on these till we address the "remove contenttype" bug 1185030

---

<sup>**[treeherder/model/models.py, line 218 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JuDjgbQeuUumsMZB5WE)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/models.py#L218)):</sup>
I'd rather wait on these till we address the "remove contenttype" bug 1185030

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/660)

**Comment by camd** [comment]
Hi Ed: I believe I have addressed all your commit comments.  There were a couple places where I left ``contenttype`` un-touched because it would have opened a can of worms I'd rather address in a later PR.  This branch is (as of this writing) running on Stage.  Looks pretty good to me.  :)

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/660)

**Comment by edmorley** [comment]
Could you remove the dist directory changes and rebase against master? It currently doesn't apply cleanly after bug 1183575 landed. After that if you set r?emorley again on the bug, I'll take a final look :-)

**Comment by camd** [comment]
ahh, right right.  Will do.  I suppose I should have pushed a different branch to stage created from this one, with a grunt build added on.

**Comment by edmorley** [comment]
Reviewed 1 of 44 files at r1, 4 of 7 files at r2, 18 of 18 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[treeherder/model/derived/jobs.py, line 169 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/660#-JukBVAR0_F8frbBzqiD)** ([raw file](https://github.com/mozilla/treeherder/blob/42922b523424735ba0482902ce41ff742bdc16e3/treeherder/model/derived/jobs.py#L169)):</sup>
There's one further usage of `jobs_execute()` that needs renaming to `execute()`, in rewrite_perf_data.py :-)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/660)

**Pull request merged**
