### PR TITLE
Update MarkupSafe

### PR DESCRIPTION
**Pull request by sarah-clements**
@ionutgoldan I've tried updating the MarkupSafe hashes but for some reason some formatting changes have been picked up too. I don't really understand why.... I can also see that the same importlib-metadata error has occurred as [here](https://github.com/mozilla/treeherder/pull/6952#issuecomment-758894278), but we're still using pip-tools v 5.4 as far as I can see. @armenzg do you have any thoughts on whats happening?

I used venv per [here](https://github.com/mozilla/treeherder/blob/master/tests/README.md#install-into-virtual-environment), and then used [these](https://github.com/mozilla/treeherder/blob/master/requirements/README.md#upgrading) commands (except used --upgrade-package instead of --upgrade flag) here to update MarkupSafe.

@ionutgoldan If you figure out how to update MarkupSafe hashes and get all tests passing then go ahead and merge the pr - I can give a retroactive review.

### CODE REVIEW

**Comment by airimovici** [comment]
I created this PR: https://github.com/mozilla/treeherder/pull/7008 for updating the markupsafe hashes and all the tests are passing. I only applied the patch that Ionut provided in the [bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1690215).

**Comment by ionutgoldan** [comment]
> @ionutgoldan I've tried updating the MarkupSafe hashes but for some reason some formatting changes have been picked up too. I don't really understand why.... I can also see that the same importlib-metadata error has occurred as [here](https://github.com/mozilla/treeherder/pull/6952#issuecomment-758894278), but we're still using pip-tools v 5.4 as far as I can see. [...]

Yeah, I've tried these exact changes & stumbled upon the same problem. That's why I only updated the hashes for the `markupsafe` dependency. Didn't need to touch the dev.txt file, as it doesn't include it.

> I used venv per [here](https://github.com/mozilla/treeherder/blob/master/tests/README.md#install-into-virtual-environment), and then used [these](https://github.com/mozilla/treeherder/blob/master/requirements/README.md#upgrading) commands (except used --upgrade-package instead of --upgrade flag) here to update MarkupSafe.
I haven't upgraded MarkupSafe, only updated its hashes.

> @ionutgoldan If you figure out how to update MarkupSafe hashes and get all tests passing then go ahead and merge the pr - I can give a retroactive review.

Alex Irimovici submitted a [PR 7008](https://github.com/mozilla/treeherder/pull/7008) for that. Maybe we can close this PR in favor of his?

**Comment by sarah-clements** [comment]
> I haven't upgraded MarkupSafe, only updated its hashes. Basically, I ditched not only `--upgrade` flag, but `--upgrade-package` also.
> 
Is this what command you ran?
`pip-compile --generate-hashes --output-file requirements/common.txt requirements/common.in`?

**Comment by armenzg** [comment]
In all honestly, it's always been very excessive the matter for hashes. Treeherder is the only project where I've seen this. Pinning the versions is more than sufficient to accomplish the purpose of using the same set of dependencies between development and production.
 
Requiring hashes means that we do not trust packages installed via pip and most Python services in the internet are unaware if dangerous Python packages have been installed.

I'm glad you figured it out.

**Pull request closed without merging**
