### PR TITLE
Bug 1671209 -  Add text to "Help" dropdown in treeherder/perfherder

### PR DESCRIPTION
**Pull request by Sparsh-Bansal**
To improve usability and accessibility, I have added  `"Help and Resources"` text in the dropdown menu.

### CODE REVIEW

**Comment by sarah-clements** [comment]
Hi, please request to be assigned to a before working on it. You can do that by adding a comment in the bugzilla bug. Thanks!

**Comment by kimberlythegeek** [comment]
@Sparsh-Bansal Just a little thing, but the text should probably be to the left of the ? icon.

**Comment by sarah-clements** [comment]
> @Sparsh-Bansal Just a little thing, but the text should probably be to the left of the (?) icon.
> 
> Otherwise looks good!

Could we just remove the icon altogether?

**Comment by Sparsh-Bansal** [comment]
> > @Sparsh-Bansal Just a little thing, but the text should probably be to the left of the (?) icon.
> > Otherwise looks good!
> 
> Could we just remove the icon altogether?

Yeah ! Just text(without a icon) will look compatible with other dropdown menus.

**Comment by Sparsh-Bansal** [comment]
@kimberlythegeek  Should I add the icon on the right or it is just fine ?

**Comment by Sparsh-Bansal** [comment]
> @kimberlythegeek Should I add the icon on the right or it is just fine ?

@kimberlythegeek Please review it.

**Review by sarah-clements — APPROVED** [review]

**Pull request merged**
