### PR TITLE
Bug suggestions take 3

### PR DESCRIPTION
**Pull request by camd**
Fixes [Bug 1080760](https://bugzilla.mozilla.org/show_bug.cgi?id=1080760)
Follow-on to [PR 525](https://github.com/mozilla/treeherder/pull/525)

This generates bug suggestions for ``text_log_summary`` artifacts submitted to the ``artifact``  REST endpoint.  It schedules those asynchronously with ``celery``.

If a job is submitted to through the ``job`` REST endpoint and it contains a ``text_log_summary`` artifact with it, then the ``Bug suggestions`` artifact is created immediately (not asynchronously).  I created [Bug 1163253](https://bugzilla.mozilla.org/show_bug.cgi?id=1163253) to address possibly making that ``jobs`` endpoint asynchronous as well.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/518)

### CODE REVIEW

**Comment by edmorley** [comment]
I'm probably missing something obvious, but why do we create the artefact synchronously when the jobs endpoint is used, but asynchronously when the artefact one is used? The commit message explains the what, but not the why? :-)

Could you add to the commit message something explaining what the different routes are (ie: artefact vs job endpoint) and who uses each? (ie: which does the log parser use?) It will help me review, since I don't entirely follow at the moment.

We also need tests for all of the permutations, particularly to ensure we don't do busy-work if the bug suggestions are already generated (eg from the log parser) :-)

**Comment by edmorley** [comment]
There also seems to be a big perf hit both on the web transaction time and the non-web.
Unless I'm misunderstanding the changes here, this PR should be mostly a no-op in terms of perf for the short term (unless there's a bug), since until submitters like taskcluster start giving us the text log summary, we're using the same code paths as before, surely?

**Comment by edmorley** [comment]
Perhaps splitting this up more will help us see where the problem is? eg: add support to the artefacts and jobs endpoint parts separately. It will definitely make the review easier, and we can then also deploy the parts in turn to stage to see perf on new relic.

**Comment by edmorley** [comment]
Master has now been deployed to stage again (since stage was slightly broken due to wlach's follow-up fix not being on this branch). Perhaps we should land on master + push to stage just the refactor for now, and then we can confirm it was this PR and not the refactor that caused the perf hit.

**Comment by camd** [comment]
@edmorley : I changed the code so that submitting a job to the /jobs endpoint that has a ``text_log_summary`` artifact will schedule the asynchronous generation of the ``Bug suggestions`` artifact.  Your idea was a good one, thanks!

**Comment by camd** [comment]
@edmorley : I updated the commit message to be accurate.  There are two new ways to generate bug suggestions now and both have tests.  There are existing tests for the old way (via our ingestion with buildbot).

**Comment by edmorley** [comment]
Thank you for the changes so far :-)

What I meant by listing the permutations was something a bit more detailed, like:

1) Posting to the jobs endpoint
  (a) Posting a job with a log URL set but no artifacts [this is what the buildbot jobs do]. So we need to generate everything.
  (b) Posting a job with a log URL set, with parsed status set to parsed, a text_log_summary artifact, but no "Bug suggestions" artifact [the desired future state for Taskcluster]. So we need to generate only the "Bug suggestions" artifact.
  (c) Posting a job with a log URL set, with parsed status set to parsed, a text_log_summary and a "Bug suggestions" artifact, so no further generation of artifacts required [this case is likely not to be used by many submitters]

2) Posting to the artifacts endpoint
  (a) Posting just a text_log_summary artfact. We need to generate the "Bug suggestions" artifact if it doesn't exist (in case it was somehow submitting prior to the text_log_summary artifact), but not if it doesn't. [Not sure how many submitters will hit this case, since many will just provide the artifact along with the job, on the jobs endpoint].
  (b) Posting both a text_log_summary and a "Bug suggestions" artifact. No further artifact generation required. [This is the case that our log parser will hit]

I've also noticed that we don't currently enforce that someone doesn't submit a job with a log parsed status of "pending" but also provide a text_log_summary - since at the moment, we'll re-parse the log anyway. Or alternatively, I wonder if we stop allowing them to specify the log parse status themselves, and we make the determination based on whether they provide the "text_log_summary"?

By listing the permutations out above, it seems that we're missing a few tests (this is what I meant by https://github.com/mozilla/treeherder/pull/518#issuecomment-101073108):
* Checking that posting a job to the jobs endpoint with both a text_log_summary and "Bug suggestions" artifact doesn't try to generate another "Bug suggestions" artifact.
* Checking that posting both a text_log_summary and "Bug suggestions" artifact to the artifacts endpoint doesn't try to generate another "Bug suggestions" artifact.
* Checking that posting a job to the jobs endpoint with a parsed status of "parsed" doesn't try to parse the log.
* Checking that posting a job to the jobs endpoint with a parsed status of "pending" but with an artifact called "text_log_summary" is either disallowed or we update the parse status to "parsed" and don't re-parse the log.

---

Reviewed files:
- bin/run_celery_worker_log_parser @ r1
- tests/conftest.py @ r1
- tests/e2e/test_client_job_ingestion.py @ r1
- tests/sample_data/artifacts/text_log_summary.json @ r1
- tests/sampledata.py @ r1
- tests/webapp/api/test_artifact_api.py @ r1
- tests/webapp/api/test_note_api.py @ r1
- treeherder/model/derived/artifacts.py @ r1
- treeherder/model/derived/jobs.py @ r1
- treeherder/model/error_summary.py @ r1
- treeherder/model/tasks.py @ r1
- treeherder/settings/base.py @ r1
- treeherder/webapp/api/artifact.py @ r1

---

<sup>**[treeherder/model/derived/jobs.py, line 1349 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpDMMJoqkHkUd7046Rj)** ([raw file](https://github.com/mozilla/treeherder/blob/bad3811e3e915e29d0f1a2fe9fdce0de95957991/treeherder/model/derived/jobs.py#L1349)):</sup>
As a name, is async_artifact_list too generic? How about "async_error_summary_list" or something similar?

---

<sup>**[treeherder/model/derived/jobs.py, line 1605 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpDLYHi2a-RrXRuNJmq)** ([raw file](https://github.com/mozilla/treeherder/blob/bad3811e3e915e29d0f1a2fe9fdce0de95957991/treeherder/model/derived/jobs.py#L1605)):</sup>
I think we also need to check that a "Bug suggestions" artefact wasn't provided here (like we do if people instead use the artifacts API). At the moment, we'll schedule the async job even if they've provided one.

---

<sup>**[treeherder/model/tasks.py, line 179 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpDJvl34y6gEOJVWsPu)** ([raw file](https://github.com/mozilla/treeherder/blob/bad3811e3e915e29d0f1a2fe9fdce0de95957991/treeherder/model/tasks.py#L179)):</sup>
This needs to be "populate-error-summary" I think?

---

<sup>**[treeherder/webapp/api/artifact.py, line 92 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpDJLYsqVZGSzHvqUjK)** ([raw file](https://github.com/mozilla/treeherder/blob/bad3811e3e915e29d0f1a2fe9fdce0de95957991/treeherder/webapp/api/artifact.py#L92)):</sup>
I think the load_job_artefacts() call should be before we schedule the async job, to avoid races? (Where the text_log_summary hasn't quite been stored yet, so the async error_summary job has nothing to use to generate the summary)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 6 of 13 files reviewed, 4 unresolved discussions, some commit checks broke.

---

<sup>**[treeherder/model/derived/jobs.py, line 1349 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpDMMJoqkHkUd7046Rj)** ([raw file](https://github.com/mozilla/treeherder/blob/bad3811e3e915e29d0f1a2fe9fdce0de95957991/treeherder/model/derived/jobs.py#L1349)):</sup>
wfm.  :)  Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 6 of 13 files reviewed, 4 unresolved discussions, some commit checks broke.

---

<sup>**[treeherder/model/derived/jobs.py, line 1605 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpDLYHi2a-RrXRuNJmq)** ([raw file](https://github.com/mozilla/treeherder/blob/bad3811e3e915e29d0f1a2fe9fdce0de95957991/treeherder/model/derived/jobs.py#L1605)):</sup>
yep, good call.  I moved it into the ``error_summary`` library so we can check it in a centralized place.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 6 of 13 files reviewed, 4 unresolved discussions, some commit checks broke.

---

<sup>**[treeherder/model/tasks.py, line 179 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpDJvl34y6gEOJVWsPu)** ([raw file](https://github.com/mozilla/treeherder/blob/bad3811e3e915e29d0f1a2fe9fdce0de95957991/treeherder/model/tasks.py#L179)):</sup>
shoot.  right you are!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 6 of 13 files reviewed, 4 unresolved discussions, some commit checks broke.

---

<sup>**[treeherder/webapp/api/artifact.py, line 92 \[r1\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpDJLYsqVZGSzHvqUjK)** ([raw file](https://github.com/mozilla/treeherder/blob/bad3811e3e915e29d0f1a2fe9fdce0de95957991/treeherder/webapp/api/artifact.py#L92)):</sup>
Yep, good point.  Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by edmorley** [comment]
Review status: all files reviewed, 5 unresolved discussions, all commit checks successful.
Reviewed files:
- docs/submitting_data.rst @ r4
- tests/e2e/test_client_job_ingestion.py @ r4
- tests/model/derived/test_artifacts_model.py @ r3
- tests/webapp/api/test_artifact_api.py @ r4
- treeherder/model/derived/artifacts.py @ r3
- treeherder/model/derived/jobs.py @ r3
- treeherder/model/error_summary.py @ r4
- treeherder/model/tasks.py @ r4
- treeherder/settings/base.py @ r4
- treeherder/webapp/api/artifact.py @ r3

---

<sup>**[docs/submitting_data.rst, line 528 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-Jpg9nG-tp7rVIYEqMPi)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/docs/submitting_data.rst#L528)):</sup>
s/in in/in/

---

<sup>**[tests/e2e/test_client_job_ingestion.py, line 166 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpgElFG6lFCLoDHiJ7G)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/tests/e2e/test_client_job_ingestion.py#L166)):</sup>
I think we need to 'assert len(artifacts) == 2', since the 'assert set(..)' below wouldn't catch us accidentally generating two bug suggestions artifacts, since set() removes duplicates.

---

<sup>**[tests/e2e/test_client_job_ingestion.py, line 171 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpgDsl0kOr45VHg6lzj)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/tests/e2e/test_client_job_ingestion.py#L171)):</sup>
This test description says we're testing that we didn't parse the log (since the log was already parsed), but I can't see where we're asserting that we did not call the mock parse log?
eg like the 'assert mock_parse.called is False' of the next test.

---

<sup>**[tests/e2e/test_client_job_ingestion.py, line 240 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpgBScVUS7DQ8o1rChL)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/tests/e2e/test_client_job_ingestion.py#L240)):</sup>
I think we also need to assert that the log url parse status is now set to parsed (instead of pending). Currently the docstring of this test says we do that, but it's not being tested.

---

<sup>**[treeherder/model/error_summary.py, line 210 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpgGGSeZ34ceGNa-4Bn)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/treeherder/model/error_summary.py#L210)):</sup>
If I change ``x['job_guid'] not in bs_guid_list`` to ``True`` all of the tests still pass. It seems like we should get failures for this? Is a test broken or are we missing a test?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 10 of 15 files reviewed, 5 unresolved discussions, some commit checks pending.

---

<sup>**[tests/e2e/test_client_job_ingestion.py, line 166 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpgElFG6lFCLoDHiJ7G)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/tests/e2e/test_client_job_ingestion.py#L166)):</sup>
right you are.  Fixed

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 10 of 15 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[tests/e2e/test_client_job_ingestion.py, line 171 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpgDsl0kOr45VHg6lzj)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/tests/e2e/test_client_job_ingestion.py#L171)):</sup>
Rats..  right you are again.  Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 10 of 15 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[docs/submitting_data.rst, line 474 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-Jpg9nG-tp7rVIYEqMPi)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/docs/submitting_data.rst#L474)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 10 of 15 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[tests/e2e/test_client_job_ingestion.py, line 231 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpgBScVUS7DQ8o1rChL)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/tests/e2e/test_client_job_ingestion.py#L231)):</sup>
I've been a bit sloppy here.  I refactored the tests to have a consistent battery of tests against each scenario (with different expected values).  This makes sure we test the same things (in most cases) for each scenario.  Thanks for catching this.  Sorry you had to...  :(

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
Review status: 10 of 15 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[treeherder/model/error_summary.py, line 210 \[r4\]](https://reviewable.io:443/reviews/mozilla/treeherder/518#-JpgGGSeZ34ceGNa-4Bn)** ([raw file](https://github.com/mozilla/treeherder/blob/76ea38295d6c58ca12cc8bdb37c15babd3b6e78e/treeherder/model/error_summary.py#L210)):</sup>
This was fixed by my refactor of the tests.  Now it catches the error because it detects that ``get_error_summary_artifacts`` was called when it should not have been.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Comment by camd** [comment]
done

---

Review status: 10 of 15 files reviewed, 5 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/treeherder/518)

**Pull request merged**
