### PR TITLE
support marking NEW failures as FC_id=6

### PR DESCRIPTION
**Pull request by jmaher**

### CODE REVIEW

**Comment by jmaher** [comment]
a simple patch to use existing unused classification spot for NEW failures;  Doing this would allow for filtering on these failures which could be done by default on try :)

I had trouble testing this locally (log parsing was not ingesting stuff), so I would want to test on staging

**Comment by marco-c** [comment]
If we do this, we probably have to update mozci to take this classification into account

**Review by Archaeopteryx — APPROVED** [review]
1. This should have tests because it's easy to miss unclassified would have another state.
2. Reach out how to ingest locally. The `PULSE_URL` needs to be set as does `PROJECTS_TO_INGEST` of which the ingested task should be part of.

**Comment by jmaher** [comment]
@marco-c what work will be needed for mozci?  I assume any place in the code that references classification should be looked at.  Do you have concerns with this type of approach?

**Comment by marco-c** [comment]
> @marco-c what work will be needed for mozci? I assume any place in the code that references classification should be looked at. Do you have concerns with this type of approach?

Yeah, we just need to double check all the code locations that use classifications. It's possible we will end up not needing to do anything.

**Comment by jmaher** [comment]
current state is:
1) I had to modify a few more places in the source tree after testing locally;  this seems to work well for new and existing failures as well as adding annotations to failures.  I assume testing annotating as intermittent covers all the cases.
2) tests- I have a basic test added, but it required a good bit of changes to the test data.  Test data had old dates, that is the biggest modification- also I wanted to associate jobs with unique pushes and mark them as failures- it appears I can do this without affecting the other tests.

I am not 100% done; I want to ensure I have clean changes and no unnecessary changes.  Likewise I want to see if there are ways to get more coverage.  Probably something like:
1) adding a classification to a NEW failure
2) UI filter by new failure

**Comment by jmaher** [comment]
@Archaeopteryx can you give this another look.  I didn't make changes to the product, more to the tests.  A few things to keep in mind:
1) we only do NEW failure counting on m-c and autoland, so I needed to change the branch used in the tests to test this.
2) changing the branch required changes in computed job signatures, as well as data that had hard coded branches.

If you have other ideas, I am open.  I personally would like another test written for filtering, but given how much time I have put into this, I am inclined to get this in and do that test later

**Review by Archaeopteryx — APPROVED** [review]

**Pull request merged**
