### PR TITLE
Bug 1207648 - Remove temporary migration code and schemas

### PR DESCRIPTION
**Pull request by wlach**
* We needed to allow the respository and last_updated fields to be null
  temporarily while we waited to run a migration, but this is no longer
  necessary
* Also remove temporary migration script, it's no longer needed

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/1337)

### CODE REVIEW

**Comment by camd** [comment]
Looks like the tests aren't passing.

**Comment by camd** [comment]
The code looks good to me.  And it looks like the tests failed because they stalled.  So I restarted them.  :)  We'll see if they pass this time.  I've had this happen with Travis before.

**Comment by wlach** [comment]
There was an issue with the original PR anyway, fixed and rerunning tests.

**Comment by wlach** [comment]
Ok, I think we're good now!

**Pull request merged**
