### PR TITLE
Bug 1191481 - Add windows 10 support

### PR DESCRIPTION
**Pull request by Callek**
Add support for win 10

[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/846)

### CODE REVIEW

**Comment by rvandermeulen** [comment]
Can we kill two birds with one stone and add 32-bit support while we're at it?

**Comment by Callek** [comment]
@rvandermeulen - if its a requirement, sure. But I don't see us (releng) enabling win10 32 bit anytime soon.

**Comment by rvandermeulen** [comment]
I'm just saying that it'd be trivial to add now and avoid having to worry about it later. And given that the tendency is to completely forget about doing things like this until jobs are already running, it would be nice to be ahead of the curve for once :)

**Comment by Callek** [comment]
Added 32 bit support as suggested...

**Comment by edmorley** [comment]
Merged manually in https://github.com/mozilla/treeherder/commit/5ae5c4909d183f0f7d6c7c0dc31c2afe6e03b876

**Pull request closed without merging**
