### PR TITLE
Bug 1532230 - Disable nudge feature

### PR DESCRIPTION
**Pull request by ionutgoldan**

### CODE REVIEW

**Comment by ionutgoldan** [comment]
I didn't remove the entire implementation of the nudge feature, so it'll be easier to re enable its better version. But if you require, I can't drop it completely so the code will be cleaner.

**Comment by camd** [comment]
@sarah-clements : What do you think about a UI change with this?

**Comment by sarah-clements** [comment]
> @sarah-clements : What do you think about a UI change with this?

I agree with using a tooltip to explain that it's been disabled. We don't want anyone filing bugs thinking it's broken. :)

**Comment by ionutgoldan** [comment]
> 
> 
> > @sarah-clements : What do you think about a UI change with this?
> 
> I agree with using a tooltip to explain that it's been disabled. We don't want anyone filing bugs thinking it's broken. :) But I'd also file a bug to re-enable it at some point and reference all relevant bug numbers as a code comment so it doesn't stay there indefinitely if this feature isn't enabled anytime soon.

Done that :)
@sarah-clements could you check my updates? Thanks!

**Comment by sarah-clements** [comment]
Looks good - I'll merge it.

**Pull request merged**
