### PR TITLE
Bug 1332732 - Improve ergonomics around cancelling jobs

### PR DESCRIPTION
**Pull request by wlach**
* Pop up a dialog to confirm action
* Confirm that request to cancel was sent to server

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/treeherder/2101)

### CODE REVIEW

**Comment by staktrace** [comment]
I would very much prefer not having to deal with a confirmation dialog on every job cancellation. It's already painful enough as it is to cancel multiple jobs (bug 1217570).

**Comment by edmorley** [comment]
Yeah I think it may be best to exclude the prompt

**Comment by wlach** [comment]
It worries me a bit to not at least prompt when performing a destructive action (it seemed like an oversight), but I can leave it out.

**Comment by wlach** [comment]
Updated

**Comment by edmorley** [comment]
Perhaps the prompt is something that can be added once bug 1217570 is added :-)

**Pull request merged**
