### PR TITLE
webrender pgo isn't a thing anymore

### PR DESCRIPTION
**Pull request by sylvestre**
it has been replaced by shippable

### CODE REVIEW

**Comment by sylvestre** [comment]
@armenzg does it work for you?

**Comment by sarah-clements** [comment]
@sylvestre Can you rebase and I'll merge it?

**Comment by sarah-clements** [comment]
@sylvestre This needs a rebase too please.

**Comment by jmaher** [comment]
redoing this in https://github.com/mozilla/treeherder/pull/7401

**Pull request closed without merging**
