### PR TITLE
Bug 1171575 - Remove unused cancel_all function from controller.js

### PR DESCRIPTION
**Pull request by vaibhavmagarwal**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder/771)

### CODE REVIEW

**Comment by tojonmz** [comment]
Drive by..  just to ensure we've encompassed everything for removal? :)
https://github.com/mozilla/treeherder/search?utf8=%E2%9C%93&q=cancel

**Comment by vaibhavmagarwal** [comment]
I am not sure about other areas, since I have not read through all of TH code :)
But I have confidence, that this function is not used.

**Comment by edmorley** [comment]
Whilst this function is unused, I wonder if in fact this is the better location for the similar functions that are used? ie: in the future should we support "cancel all" for non-buildbot? If so, the functionality needs to be more generic than just in buildapi.js

I'll defer to @camd on this, since iirc he wrote the cancel job code :-)

**Comment by vaibhavmagarwal** [comment]
The cancelAllJobs() function that is currently being used is in jobs.js: https://github.com/mozilla/treeherder/blob/09a5a1dc2da6e59d39e34d24b4db97306a56044d/ui/js/controllers/jobs.js#L193

**Comment by camd** [comment]
After taking a look (gosh, we have a lot of ``cancelAll`` type of funcitons) it looks like the one @vaibhavmagarwal  mentions in jobs.js is the main one.  It, in turn calls other model/service functions to do its work.  

But this one in question was added long ago by me and, I think, never used.  Having it in the ``plugins/controller.js`` would be the wrong place anyway.

Good find, @vaibhavmagarwal !  :)

**Pull request merged**
