### PR TITLE
Bug 1700946 - Record status change

### PR DESCRIPTION
**Pull request by airimovici**

### CODE REVIEW

**Review by ionutgoldan — APPROVED** [review]
LGTM!

**Comment by ionutgoldan** [comment]
Hi @sarah-clements! Could you also take a look over this PR?
Thanks in advance!

**Comment by airimovici** [comment]
@sarah-clements This won't have any impact on the database as it produces no sql changes

**Review by sarah-clements — APPROVED** [review]

**Comment by sarah-clements** [comment]
I'll do a prod deploy on Thursday.

**Comment by ionutgoldan** [comment]
Cool, thanks Sarah!

**Pull request merged**
