### PR TITLE
disabled a11y eslint rules

### PR DESCRIPTION
**Pull request by pachicodes**
Removed 'jsx-a11y/control-has-associated-label' from 2 files and code change @camd @sarah-clements

### CODE REVIEW

**Comment by sarah-clements** [comment]
Sorry for the delay in reviewing @pachicodes. Please remove the first commit for bug 1421273. When working on patches or features, we keep them to a single-purpose branch (typically named for that purpose) only without any unrelated commits. So this eslint task should only have commits related to this specific task. Let me know once you've done that and I'll take another look.

**Comment by pachicodes** [comment]
Hi @sarah-clements  thank you
I am not sure how to do that so I will do some research and get back to you

**Comment by armenzg** [comment]
@pachicodes you can try this:
`git revert b53f557dac5393ec0fec4ec9f6e51d5e3399fef1`

We will squash all commits upon landing so don't worry if you will still see 3 commits for this PR.

**Comment by sarah-clements** [comment]
> @pachicodes you can try this:
> `git revert b53f557dac5393ec0fec4ec9f6e51d5e3399fef1`
> 
> We will squash all commits upon landing so don't worry if you will still see 3 commits for this PR.

We aren't merging this pr.

**Pull request closed without merging**
