### PR TITLE
Bug 1616215 - Warn when user filters by option or repository

### PR DESCRIPTION
**Pull request by esanuandra**

### CODE REVIEW

**Comment by ionutgoldan** [comment]
This is a follow up for [PR 6158](https://github.com/mozilla/treeherder/pull/6158), which has been closed due to Octavian's leave.

**Comment by airimovici** [comment]
@sarah-clements  Initially, Octavian implemented the task as you said (by not including the "unsupported" words in the `fetchAlertSummary` call), but after reviewing it and using this feature I noticed there are some of the terms that are "unsupported" that may become irritating for the user when they are not included (options like `32`, `64`, `raptor` etc.). That's why I suggested a change: not to change the call and delete the unsupported terms, but to warn that using them may filter too much out.

I think that the warning message should be enough of a heads-up without being too intrusive into the filtering that the user wanted to do.

**Comment by sarah-clements** [comment]
> @sarah-clements Initially, Octavian implemented the task as you said (by not including the "unsupported" words in the `fetchAlertSummary` call), but after reviewing it and using this feature I noticed there are some of the terms that are "unsupported" that may become irritating for the user when they are not included (options like `32`, `64`, `raptor` etc.). That's why I suggested a change: not to change the call and delete the unsupported terms, but to warn that using them may filter too much out.
> 
> I think that the warning message should be enough of a heads-up without being too intrusive into the filtering that the user wanted to do.

Ok, but what if someone's search ONLY contains unsupported words? We probably shouldn't even call `fetchAlertSummaries` at all then right?

**Comment by airimovici** [comment]
> 
> 
> > @sarah-clements Initially, Octavian implemented the task as you said (by not including the "unsupported" words in the `fetchAlertSummary` call), but after reviewing it and using this feature I noticed there are some of the terms that are "unsupported" that may become irritating for the user when they are not included (options like `32`, `64`, `raptor` etc.). That's why I suggested a change: not to change the call and delete the unsupported terms, but to warn that using them may filter too much out.
> > I think that the warning message should be enough of a heads-up without being too intrusive into the filtering that the user wanted to do.
> 
> Ok, but what if someone's search ONLY contains unsupported words? We probably shouldn't even call `fetchAlertSummaries` at all then right?

The way it's implemented right now it does not alter the `fetchAlertSummary` call at all. Some unsupported terms (like options) may be contained in test names or suite names (that are supported when filtering), so the user still gets value from that.

**Comment by sarah-clements** [comment]
> > > @sarah-clements Initially, Octavian implemented the task as you said (by not including the "unsupported" words in the `fetchAlertSummary` call), but after reviewing it and using this feature I noticed there are some of the terms that are "unsupported" that may become irritating for the user when they are not included (options like `32`, `64`, `raptor` etc.). That's why I suggested a change: not to change the call and delete the unsupported terms, but to warn that using them may filter too much out.
> > > I think that the warning message should be enough of a heads-up without being too intrusive into the filtering that the user wanted to do.
> > 
> > 
> > Ok, but what if someone's search ONLY contains unsupported words? We probably shouldn't even call `fetchAlertSummaries` at all then right?
> 
> The way it's implemented right now it does not alter the `fetchAlertSummary` call at all. Some unsupported terms (like options) may be contained in test names or suite names (that are supported when filtering), so the user still gets value from that.

Ah ok, I didn't notice the change in implementation had occurred (didn't look like it was doing that with Octavian's initial pr). This looks good to me.

**Pull request merged**
