### PR TITLE
Docs: `yarn run foo` -> `yarn foo`

### PR DESCRIPTION
**Pull request by wlach**
The run is redundant.

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by wlach** [comment]
Yeah I noticed that Shruti was unnecessarily doing yarn run foo, and she mentioned she learned that from the docs. :)

**Comment by edmorley** [comment]
Ah spotted some more (though don't feel obliged to fix):
```
$ rg 'yarn run'
bin\post_compile
9:yarn run build
35:# required once `yarn run build` has run. The buildpack cache will still

docs\common_tasks.rst
123:     SERVICE_DOMAIN=https://treeherder.mozilla.org yarn run build

docs\deployment.rst
13:* Run ``yarn run build`` to create the ``dist`` directory.

docs\installation.rst
76:    vagrant ~/treeherder$ yarn run start:local
```

**Comment by wlach** [comment]
Went ahead and fixed the other cases of it. :)

**Comment by wlach** [comment]
Went ahead and fixed the other cases of it. :)

**Pull request merged**
